### ISSUE TITLE
Failed Processing: "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by scrublullz** [kevoreilly/CAPEv2#1015]
Ubuntu 20.04LTS

I am running into some sporadic failed processing.  I am not sure which way to go for troubleshooting.

When manually running `process.py` I am getting back the following errors:

sha256: `ba3d1fb401a53a1da40202df1c45465aebf15cca8e7d9e217961b088e8bcdbf0 `
```
Traceback (most recent call last):
  File "process.py", line 446, in <module>
    main()
  File "process.py", line 436, in main
    process(task=task, report=args.report, capeproc=args.caperesubmit, memory_debugging=args.memory_debugging)
  File "process.py", line 109, in process
    RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 626, in __init__
    process["calls"].begin_reporting()
  File "/opt/CAPEv2/utils/../modules/processing/behavior.py", line 265, in begin_reporting
    for arg in ent["arguments"]:
TypeError: 'NoneType' object is not subscriptable
```

sha256: `b605b9404f41d89620a86649c20f69c3408a98f1ac0e154b582a33b32aa38861 `
```
2022-07-19 06:33:11,042 [Task 11086] [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "network_p2p": 'dict' object is not callable
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 538, in run
    result = sig.on_complete()
  File "/opt/CAPEv2/utils/../modules/signatures/network_p2p.py", line 46, in on_complete
    for tcp in self.results("network", {}).get("tcp", []):
TypeError: 'dict' object is not callable
Traceback (most recent call last):
  File "process.py", line 446, in <module>
    main()
  File "process.py", line 436, in main
    process(task=task, report=args.report, capeproc=args.caperesubmit, memory_debugging=args.memory_debugging)
  File "process.py", line 109, in process
    RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 626, in __init__
    process["calls"].begin_reporting()
  File "/opt/CAPEv2/utils/../modules/processing/behavior.py", line 265, in begin_reporting
    for arg in ent["arguments"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by doomedraven** [comment]
read the head of issue template and report properly or any issue is invalid

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/community/commit/00063c3c634d9f375d236b70e6e852638da526ba#diff-78fd79c9a57ea7b0f0c29d4a37e55ecabdee056ad01b1e76b4275e367c9aad77
