### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by rebaker501** [kevoreilly/CAPEv2#1244]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version - I am 
- [x] I did read the README! - Many times
- [x] I checked the documentation and found no answer - Many times
- [x] I checked to make sure that this issue has not already been filed - tried that
- [x] I'm reporting the issue to the correct repository (for multi-repository projects) - yes
- [x] I have read and checked all configs (with all optional parts) - yes

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

Can never get it running.

# Current Behavior

What is the current behavior?

Will not start. I've reinstalled and gone through every install method you have listed (the ordering is different in the docs compared to github readme) on Ubuntu 22.04 LTS with current updates. Also tried one time with apt install KVM before cape2.sh install. Was getting lots of pyre2 errors on fresh 22.04 but that was remedied by installing cmake and build-essential before launching cape2.sh.

This is what I get every time when trying to start. Tried manually adding modules in one install, same issue. Another person tried to install, same issue. Looks to be a DB permission issue, so I tried to open up the permissions. I've worked on this on and off for 50+ hours at this point and 20+ fresh installs. Journalctl -u cape.service produces the same log entries as below.

Here is the log:

python3 -m poetry run python cuckoo.py
Traceback (most recent call last):
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 560, in __init__
    Base.metadata.create_all(self.engine)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4740, in create_all
    bind._run_ddl_visitor(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3079, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2082, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 520, in traverse_single
    return meth(obj, **kw)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 833, in visit_metadata
    metadata.dispatch.before_create(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 875, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1210, in _on_metadata_create
    t._on_metadata_create(target, bind, **kw)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2016, in _on_metadata_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1909, in create
    bind._run_ddl_visitor(self.EnumGenerator, self, checkfirst=checkfirst)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2082, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 520, in traverse_single
    return meth(obj, **kw)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1950, in visit_enum
    self.connection.execute(CreateEnumType(enum))
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1353, in _execute_ddl
    ret = self._execute_context(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public

[SQL: CREATE TYPE status_type AS ENUM ('banned', 'pending', 'running', 'completed', 'distributed', 'reported', 'recovered', 'failed_analysis', 'failed_processing', 'failed_reporting')]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/cuckoo.py", line 25, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 28, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 27, in <module>
    db = Database()
  File "/opt/CAPEv2/lib/cuckoo/common/utils.py", line 716, in __call__
    self._instances[self] = super(Singleton, self).__call__(*args, **kwargs)
  File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 562, in __init__
    raise CuckooDatabaseError(f"Unable to create or connect to database: {e}")
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public

[SQL: CREATE TYPE status_type AS ENUM ('banned', 'pending', 'running', 'completed', 'distributed', 'reported', 'recovered', 'failed_analysis', 'failed_processing', 'failed_reporting')]
(Background on this error at: https://sqlalche.me/e/14/f405)
# Failure Information (for bugs)

Never been this stuck on an issue before.

**Comment by rebaker501** [comment]
Found solution in issues...

https://github.com/kevoreilly/CAPEv2/issues/1204
