### ISSUE TITLE
Libvirt Install Issue 

### ISSUE THREAD

**Issue by phoenixml** [kevoreilly/CAPEv2#1295]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username
cape
## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior
Running cuckoo.py
Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

# Current Behavior
```
ubuntu@ip-172-31-21-22:/opt/CAPEv2/extra$ pip3 install libvirt-python
Defaulting to user installation because normal site-packages is not writeable
Collecting libvirt-python
  Using cached libvirt-python-8.10.0.tar.gz (240 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: libvirt-python
  Building wheel for libvirt-python (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      running bdist_wheel
      running build
      running build_py
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hzjjfmi1/libvirt-python_c0346843f95645659538cd817c3074e4/setup.py", line 337, in <module>
          setup(name = 'libvirt-python',
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-hzjjfmi1/libvirt-python_c0346843f95645659538cd817c3074e4/setup.py", line 152, in run
          check_minimum_libvirt_version()
        File "/tmp/pip-install-hzjjfmi1/libvirt-python_c0346843f95645659538cd817c3074e4/setup.py", line 43, in check_minimum_libvirt_version
          subprocess.check_call(["pkg-config",
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version=0.9.11', 'libvirt']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libvirt-python
  Running setup.py clean for libvirt-python
Failed to build libvirt-python
Installing collected packages: libvirt-python
  Running setup.py install for libvirt-python ... error
  error: subprocess-exited-with-error

  × Running setup.py install for libvirt-python did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      Package libvirt was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libvirt.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libvirt' found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hzjjfmi1/libvirt-python_c0346843f95645659538cd817c3074e4/setup.py", line 337, in <module>
          setup(name = 'libvirt-python',
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/lib/python3.10/distutils/command/install.py", line 619, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-hzjjfmi1/libvirt-python_c0346843f95645659538cd817c3074e4/setup.py", line 152, in run
          check_minimum_libvirt_version()
        File "/tmp/pip-install-hzjjfmi1/libvirt-python_c0346843f95645659538cd817c3074e4/setup.py", line 43, in check_minimum_libvirt_version
          subprocess.check_call(["pkg-config",
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version=0.9.11', 'libvirt']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> libvirt-python

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I am running Cukoo.py as listed in the documentation : "sudo -u cape poetry run python cuckoo.py"
 ```
Cuckoo Sandbox 2.2-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

OPTIONAL! Missed dependency: pip3 install https://github.com/CAPESandbox/peepdf/archive/20eda78d7d77fc5b3b652ffc2d8a5b0af796e3dd.zip#egg=peepdf==0.4.2
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/DissectMalware/batch_deobfuscator
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/CAPESandbox/httpreplay
2023-01-03 11:23:39,039 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-01-03 11:23:39,040 [root] CRITICAL: CuckooDependencyError: Unable to import libvirt
```
2. I tried to install the missing library via pip3 install libvirt-python and getting the reported above error
## Context
I tried to read this issue here but unfortunately was removed 
https://github.com/kevoreilly/CAPEv2/discussions/949 the same steps https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh#L964

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04, Windows 10, macOS 10.12.3

## Failure Logs

Please include any relevant log snippets or files here.
```
I might be screwed because I am using ubuntu 22.04 ? instead of 20 ?
```

Thank you heaps for your help.

**Comment by doomedraven** [comment]
you are totally wrong on what you doing. go and read kvm-qemu and cape2 scripts to uinderstand what are you doing. ubuntu 22 is fine

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/blob/master/installer/cape2.sh#L994

**Comment by phoenixml** [comment]
I saw this script and tried to running manually from extra folder. Hmm I will try to run the command from the cape.sh It might didn't executed when I ran it on the first install, anyway I will run it again as mentioned in the script thanks @doomedraven for pointing it out cheers.

**Comment by phoenixml** [comment]
It dosent have anything to do with the script or the which command executed , from the downloaded libvirt it is failing while it is in the building process.
Its still showing the same problem and it is related to the pkg.
 
I was able to replicate that by building manually and having the same error:


```
libvirt-python$ sudo python3 setup.py build
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
running build
running build_py
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
Traceback (most recent call last):
  File "/opt/CAPEv2/libvirt-python/setup.py", line 337, in <module>
    setup(name = 'libvirt-python',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/CAPEv2/libvirt-python/setup.py", line 152, in run
    check_minimum_libvirt_version()
  File "/opt/CAPEv2/libvirt-python/setup.py", line 43, in check_minimum_libvirt_version
    subprocess.check_call(["pkg-config",
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version=0.9.11', 'libvirt']' returned non-zero exit status 1.
```
Since this is not directly related to this project I will close this issue here and check with the libvirt module developers. Thanks

**Comment by doomedraven** [comment]
that just doesn't work that way, devs here and there doesn't have nothing to see with your bug. see kvm-qemu it does preconfiguration before you can install python version, you can't just jump and run one random command

**Comment by doomedraven** [comment]
as example https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh#L510-L531
is why i told before go and read those screen, start understand what it does before using it

**Comment by phoenixml** [comment]
Agreed that's why I ran the kvm-qemu.sh before and then I ran pip libvirt-python but also didnt work.
What actually worked for me and installed libvirt is:
 Fixes from http://ask.xmodulo.com/compile-virt-manager-debian-ubuntu.html
    1. ImportError: No module named libvirt
    $ ./kvm-qemu.sh libvirt
and I have the service running successfully. 
![image](https://user-images.githubusercontent.com/14360476/210463230-4f496b13-904e-4884-ac20-dcd214a4d50d.png)

But still after I ran:
`sudo -u cape poetry run python3 cuckoo.py --debug`
I am getting: 
```
2023-01-04 00:22:55,564 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-01-04 00:22:55,565 [root] CRITICAL: CuckooDependencyError: Unable to import libvirt
```
I will continue reading with the documentation and I think I must first prepare the windows host and then I will come back to tackle this error.
thanks @doomedraven  👍

**Comment by doomedraven** [comment]
sorry for that, but your link is "garbage" due to that it goes against what im doing in my scripts. so you even probably got the qemu or libvirt from apt and that defeated all anti purpose that i have implemented

all the answers are in scripts, you just can't go and install random tool from apt or pip, there is a huge banner in kvm-qemu against that. is why i pointed to read the scripts. that is my last answer here

**Comment by phoenixml** [comment]
I updated the link was not the correct one and I didn't use apt or pip I used the script and I pass it the option libvirt to it with the user as I showed in the steps above. 
I leave this final comment here for future reference since the documentation is lacking of pointing to the troubleshooting notes in the script you shared earlier https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh
