### ISSUE TITLE
Unhandled exception in vbe_extract->decode_file

### ISSUE THREAD

**Issue by stamparm** [kevoreilly/CAPEv2#1302]
```
Traceback (most recent call last):                                                                                                                                                                         
  File "/capev2/utils/../lib/cuckoo/common/integrations/file_extra_info.py", line 457, in vbe_extract                                                                            
    decoded = vbe_decode_file(file, data)                                                                                                                                                                  
  File "/capev2/utils/../lib/cuckoo/common/integrations/vbe_decoder.py", line 277, in decode_file                                                                                
    encoded_data = re.findall(r"#@~\^......==(.+)......==\^#~@", contents)                                                                                                                                 
  File "/usr/lib/python3.8/re.py", line 241, in findall                                                                                                                                                    
    return _compile(pattern, flags).findall(string)                                                                                                                                                        
TypeError: cannot use a string pattern on a bytes-like object 
```

**Comment by doomedraven** [comment]
thanks fix is part of https://github.com/kevoreilly/CAPEv2/pull/1299
