### ISSUE TITLE
something broke in regards to the plugins, looks to appear to be related to one note

### ISSUE THREAD

**Issue by VVelox** [kevoreilly/CAPEv2#1331]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

.CAPE is generated in the report.json as well as pdf generation etc works.

# Current Behavior

Appears that this is breaking lots of other modules futher down the line. Been looking through this and I am fairly certain this was a change some place in the last two or three weeks. Been looking through and nothing has stood our yet.  But definitely some change in the last few weeks since it did not break when I updated earlier this month.

```
2023-01-25 16:07:49,286 [Task 95108] [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "CAPE": 'Config' object has no attribute 'office_one'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 243, in process
    data = current.run()
  File "/opt/CAPEv2/utils/../modules/processing/CAPE.py", line 362, in run
    self.process_file(
  File "/opt/CAPEv2/utils/../modules/processing/CAPE.py", line 193, in process_file
    static_file_info(
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/file_extra_info.py", line 246, in static_file_info
    generic_file_extractors(
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/file_extra_info.py", line 433, in generic_file_extractors
    if not getattr(selfextract_conf, funcname).get("enabled", False):
AttributeError: 'Config' object has no attribute 'office_one'
```

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Update to the newest from git.
2. Run the relevant poetry commands to make sure everything is up to date.
3. Enable PDF or lite json.
4. Restart and watch the logs.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | a5f5a23ec9e209ad2f0983413444489f798f543b
| OS version       | Ubuntu 20.04, Windows 10

## Failure Logs

All the subsequent errors appear to be releated to the first.

The Suricata PCAP errors can be ignored. No dirty line or the like in use, so no PCAPs is to be expected.

```
2023-01-25 15:50:24,796 [Task 95093] [root] INFO: Reports generation completed
2023-01-25 15:51:08,956 [Task 95090] [root] INFO: Processing analysis data for Task #95090
2023-01-25 15:51:10,011 [Task 95090] [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "CAPE": 'Config' object has no attribute 'office_one'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 243, in process
    data = current.run()
  File "/opt/CAPEv2/utils/../modules/processing/CAPE.py", line 362, in run
    self.process_file(
  File "/opt/CAPEv2/utils/../modules/processing/CAPE.py", line 193, in process_file
    static_file_info(
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/file_extra_info.py", line 246, in static_file_info
    generic_file_extractors(
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/file_extra_info.py", line 433, in generic_file_extractors
    if not getattr(selfextract_conf, funcname).get("enabled", False):
AttributeError: 'Config' object has no attribute 'office_one'
2023-01-25 15:51:13,121 [Task 95090] [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/CAPEv2/storage/analyses/95090/dump.pcap"
2023-01-25 15:51:13,122 [Task 95090] [modules.processing.suricata] WARNING: Unable to Run Suricata: Pcap file /opt/CAPEv2/storage/analyses/95090/dump.pcap does not exist. Did you run analysi
s with live connection?
2023-01-25 15:51:17,906 [Task 95090] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Malheur": 'target'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 715, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/malheur.py", line 153, in run
    if results["target"]["category"] in ["pcap"]:
KeyError: 'target'
2023-01-25 15:51:17,951 [Task 95090] [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate summary HTML report: 'dict object' 
has no attribute 'CAPE'
2023-01-25 15:51:18,093 [Task 95090] [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'dict o
bject' has no attribute 'CAPE'
2023-01-25 15:51:18,171 [Task 95090] [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Unable to open summary HTML report to convert to PDF: E
nsure reporthtmlsummary is enabled in reporting.conf
2023-01-25 15:51:18,172 [Task 95090] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "RunStatistics": object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 715, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/runstatistics.py", line 93, in run
    detail["dropped_files"] = self.getDroppedFileCount(results)
  File "/opt/CAPEv2/utils/../modules/reporting/runstatistics.py", line 19, in getDroppedFileCount
    return len(results.get("dropped"))
TypeError: object of type 'NoneType' has no len()
2023-01-25 15:51:18,263 [Task 95090] [root] INFO: Reports generation completed

```

**Comment by VVelox** [comment]
Ohh! Derp!

https://github.com/kevoreilly/CAPEv2/commit/30128f1d6143d1c75570d592dd4ac7bc8e96b278

When copying config stuff into place post update accidentally missed that item being added.

Apparently it does not handle undef nicely.

**Comment by doomedraven** [comment]
yeah those configs are headache. so please read readme that i added yesterday in conf folder to simplify your life https://github.com/kevoreilly/CAPEv2/tree/master/conf

**Comment by VVelox** [comment]
@doomedraven Ohh! Cool. Need to look into that.

On a related note, apparently it looks like the missing config item was not causing the latter dropped file errors. Looks like in some cases if nothing is dropped, then that hash is not created, resulting in that alert.

Got a PR to fix that here... https://github.com/kevoreilly/community/pull/336  :)
