### ISSUE TITLE
TrId error

### ISSUE THREAD

**Issue by blacksnape** [kevoreilly/CAPEv2#135]
Hi,
I have a problem with TrID in processing:

ERROR    lib.cuckoo.core.plugins: Failed to run the processing module "TrID":
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 228, in process
    data = current.run()
  File "/opt/CAPEv2/utils/../modules/processing/trid.py", line 31, in run
    output = subprocess.check_output([ trid_binary, "-d:%s" % definitions, self.file_path], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/CAPEv2/data/trid/trid', '-d:/opt/CAPEv2/data/trid/triddefs.trd', '/opt/CAPEv2/storage/binaries/7f59bf0b9a1a27b3ab586a0c8a8cd523fcc1d530a0231de8df1e09e8e3387016']' died with <Signals.SIGABRT: 6>.
2020-03-20 09:24:10,909 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "TrID":
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 228, in process
    data = current.run()
  File "/opt/CAPEv2/utils/../modules/processing/trid.py", line 31, in run
    output = subprocess.check_output([ trid_binary, "-d:%s" % definitions, self.file_path], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/CAPEv2/data/trid/trid', '-d:/opt/CAPEv2/data/trid/triddefs.trd', '/opt/CAPEv2/storage/binaries/7f59bf0b9a1a27b3ab586a0c8a8cd523fcc1d530a0231de8df1e09e8e3387016']' died with <Signals.SIGABRT: 6>.

**Comment by doomedraven** [comment]
that is problem with trid and your server itself not cape

```
sudo rm -f /usr/lib/locale/locale-archive
sudo locale-gen --no-archive
```
