### ISSUE TITLE
Proccessing errors

### ISSUE THREAD

**Issue by RoemIko** [kevoreilly/CAPEv2#1388]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!
* Free support from doomedraven ended - no whiskey, no support. For updates check the documentation.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✔ ] I am running the latest version
- [ ✔] I did read the README!
- [✔ ] I checked the documentation and found no answer
- [✔ ] I checked to make sure that this issue has not already been filed
- [✔ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ✔] I have read and checked all configs (with all optional parts)

# Expected Behavior

I wanted to see the same results as the public cape instance, like file details and downloading sysmon/evtx files. but they dont appear for me. I think its because of the processing errors i have been getting.

# Current Behavior

It generates some errors and i think thats the reason why i cant download the collected data. However if cd into the dir where analysis results are i can see the zip files of the evtx files and such.

# Failure Information (for bugs)

I think some of the errors are caused by a pcap file which doesnt exists

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 9cca711f4f7c250f2b150c4ea9e62dd6b5e35cc0
| OS version       | Ubuntu 22.04

## Failure Logs
`/opt/CAPEv2/logs/processing.log
```
2023-02-22 15:01:48,140 [root] INFO: Processing analysis data
2023-02-22 15:06:53,660 [Task 1] [root] INFO: Processing analysis data for Task #1
2023-02-22 15:06:53,704 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to load the processing module "<class 'modules.processing.CAPE.CAPE'>": CAPE.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 211, in process
    current = module(self.results)
TypeError: CAPE.__init__() takes 1 positional argument but 2 were given
2023-02-22 15:06:54,186 [Task 1] [modules.processing.network] WARNING: The PCAP file does not exist at path "/opt/CAPEv2/storage/analyses/1/dump.pcap"
2023-02-22 15:06:54,187 [Task 1] [modules.processing.suricata] WARNING: Unable to Run Suricata: Pcap file /opt/CAPEv2/storage/analyses/1/dump.pcap does not exist. Did you run analysis with live connection?
2023-02-22 15:06:54,188 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "extract_overlay_data": 'extract_overlay_data' object has no attribute 'key'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 249, in process
    return {current.key: data}
AttributeError: 'extract_overlay_data' object has no attribute 'key'
2023-02-22 15:08:34,697 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Malheur": 'target'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 719, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/malheur.py", line 153, in run
    if results["target"]["category"] in ["pcap"]:
KeyError: 'target'
2023-02-22 15:08:52,983 [Task 1] [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate summary HTML report: 'dict object' has no attribute 'CAPE'
2023-02-22 15:08:53,039 [Task 1] [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'dict object' has no attribute 'CAPE'
2023-02-22 15:08:53,531 [Task 1] [root] INFO: Reports generation completed
```

**Comment by doomedraven** [comment]
all the problem is due to `CAPE.__init__()` but that is old code. you linking that you are on latest commit and that you updated, but code that runs in your project is 2 weeks old https://github.com/kevoreilly/CAPEv2/commit/a0ef25e879cddf536583eca4811e2e1dbf7ef775. update your side properly

**Comment by RoemIko** [comment]
i deleted the /opt/capev2/ folder, is there something else i have to do in order to update it properly?

**Comment by doomedraven** [comment]
normally `git pull` is enough. if you have some private mods you have more instructions in readme

**Comment by RoemIko** [comment]
you mean a `git pull` from the `/opt/CAPEv2` directory?
