### ISSUE TITLE
VM Not automatically starting once file is sent for analysis

### ISSUE THREAD

**Issue by Dylan818** [kevoreilly/CAPEv2#1439]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)
- [x] I'm aware that configs now are in `custom/conf/`

# Expected Behavior

After uploading a file for analysis (Web interface/CLI), the configured VM will automatically switch on and run the uploaded file. 

# Current Behavior

After uploading a file for analysis, the latest log will just be that the machine has been acquired, but the VM will not open on its own. If left alone, the analysis will fail. However, if the VM is manually started (and logged in), the analysis will proceed as normal.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit file for analysis (Web/CLI)
2. Wait for VM to open after analysis
3. VM does not open and analysis fails

## Context

Operating system: Ubuntu 22.04 TLS
File uploaded: Simple windows executable file
Libvirtd.service is not running, when it is restarted/started, qemu-kvm is not connected. When qemu-kvm is connected, then libvirtd.service stops.

| Question         | Answer
|------------------|--------------------
| Git commit       | 47e89bc1fbadf29d95fd74bb4531cf5ca6730942
| OS version       | Ubuntu 22.04.2 TLS
| VM OS             | Windows 7

## Failure Logs

Please include any relevant log snippets or files here.
2023-03-16 11:20:59,082 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-03-16 11:20:59,107 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2023-03-16 11:20:59,109 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks
2023-03-16 11:21:28,594 [lib.cuckoo.core.scheduler] INFO: Task #23: File already exists at '/opt/CAPEv2/storage/binaries/b776a6a3603507d6f9bab2956c917acb9da14196d9fca4bdf8d88391bed270b0'
2023-03-16 11:21:28,594 [lib.cuckoo.core.scheduler] INFO: Task #23: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_0qvp1c6h/test1.exe'
2023-03-16 11:21:28,605 [lib.cuckoo.core.scheduler] INFO: Task #23: acquired machine cuckoo1 (label=cuckoo1, arch=x86, platform=windows)
2023-03-16 11:26:34,211 [lib.cuckoo.core.scheduler] ERROR: Timeout hit while for machine cuckoo1 to change status
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 353, in launch_analysis
    machinery.start(self.machine.label)
  File "/opt/CAPEv2/modules/machinery/kvm.py", line 28, in start
    super(KVM, self).start(label)
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 437, in start
    self._wait_status(label, self.RUNNING)
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 334, in _wait_status
    raise CuckooMachineError(f"Timeout hit while for machine {label} to change status")
lib.cuckoo.common.exceptions.CuckooMachineError: Timeout hit while for machine cuckoo1 to change status
libvirt: Domain Config error : Requested operation is not valid: domain is not running
2023-03-16 11:26:34,219 [lib.cuckoo.core.scheduler] ERROR: Error dumping memory virtual machine cuckoo1: Requested operation is not valid: domain is not running
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 482, in dump_memory
    self.vms[label].coreDump(path, flags=libvirt.VIR_DUMP_MEMORY_ONLY)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/libvirt.py", line 1337, in coreDump
    raise libvirtError('virDomainCoreDump() failed')
libvirt.libvirtError: Requested operation is not valid: domain is not running

**Comment by doomedraven** [comment]
Requested operation is not valid: domain is not running
