### ISSUE TITLE
analyzer.py raises MemoryError exception when analyzing QBot DLLs

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1535]
# Expected Behavior

To make sure my new instance of CAPE is working correctly, I downloaded a few samples of QBot from VirusTotal and ran them through the sandbox.

https://www.virustotal.com/gui/file/60711919ef00c7bff67dbeb8dfa743525c23a10becdf14d1214ce6dbf94d2f5b/
https://www.virustotal.com/gui/file/daeb738bde541678e8728c0b5cbb41e8d640b987771e5623c700868adaa516f3/

# Current Behavior

# Failure Information (for bugs)

`analyzer.py` raises a `MemoryError` exception (see the logs below)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit the sample to the sandbox

## Context

| Question                     | Answer
|-------------------------|--------------------
| Git commit                  | 705ea08c24b069fa2bb609b5f9f643fd9479bc4e
| Host OS version          | Ubuntu 22.04 LTS
| Guest OS version        | Windows 10 build 19044
| Guest Python version | 3.11.3

## Failure Logs

```text
2023-05-20 22:02:47,723 [root] INFO: Date set to: 20230522T15:51:03, timeout set to: 200
2023-05-22 15:51:03,000 [root] DEBUG: Starting analyzer from: C:\tmpyg6psi76
2023-05-22 15:51:03,000 [root] DEBUG: Storing results at: C:\PFzRUz
2023-05-22 15:51:03,000 [root] DEBUG: Pipe server name: \\.\PIPE\PyouPaNpR
2023-05-22 15:51:03,000 [root] DEBUG: Python path: C:\Program Files (x86)\Python311-32
2023-05-22 15:51:03,000 [root] INFO: Analysis package "dll" has been specified
2023-05-22 15:51:03,000 [root] DEBUG: Importing analysis package "dll"...
2023-05-22 15:51:03,012 [root] DEBUG: Initializing analysis package "dll"...
2023-05-22 15:51:03,012 [root] DEBUG: New location of moved file: C:\Users\resacted\AppData\Local\Temp\daeb738bde541678e872.dll
2023-05-22 15:51:03,012 [root] INFO: Analyzer: Package modules.packages.dll does not specify a DLL option
2023-05-22 15:51:03,012 [root] INFO: Analyzer: Package modules.packages.dll does not specify a DLL_64 option
2023-05-22 15:51:03,012 [root] INFO: Analyzer: Package modules.packages.dll does not specify a loader option
2023-05-22 15:51:03,012 [root] INFO: Analyzer: Package modules.packages.dll does not specify a loader_64 option
2023-05-22 15:51:03,012 [root] ERROR: Traceback (most recent call last):
```
```python
  File "C:\tmpyg6psi76\analyzer.py", line 1379, in <module>
    success = analyzer.run()
              ^^^^^^^^^^^^^^
  File "C:\tmpyg6psi76\analyzer.py", line 422, in run
    copy("dll\\capemon.dll", CAPEMON32_NAME)
  File "C:\Program Files (x86)\Python311-32\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files (x86)\Python311-32\Lib\shutil.py", line 276, in copyfile
    _copyfileobj_readinto(fsrc, fdst, min(file_size, COPY_BUFSIZE))
  File "C:\Program Files (x86)\Python311-32\Lib\shutil.py", line 178, in _copyfileobj_readinto
    with memoryview(bytearray(length)) as mv:
                    ^^^^^^^^^^^^^^^^^
MemoryError
Traceback (most recent call last):
  File "C:\tmpyg6psi76\analyzer.py", line 1379, in <module>
    success = analyzer.run()
              ^^^^^^^^^^^^^^
  File "C:\tmpyg6psi76\analyzer.py", line 422, in run
    copy("dll\\capemon.dll", CAPEMON32_NAME)
  File "C:\Program Files (x86)\Python311-32\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files (x86)\Python311-32\Lib\shutil.py", line 276, in copyfile
    _copyfileobj_readinto(fsrc, fdst, min(file_size, COPY_BUFSIZE))
  File "C:\Program Files (x86)\Python311-32\Lib\shutil.py", line 178, in _copyfileobj_readinto
    with memoryview(bytearray(length)) as mv:
                    ^^^^^^^^^^^^^^^^^
MemoryError
```
```text
2023-05-22 15:51:03,012 [root] WARNING: Folder at path "C:\PFzRUz\debugger" does not exist, skipping
2023-05-22 15:51:03,012 [root] WARNING: Folder at path "C:\PFzRUz\tlsdump" does not exist, skipping
2023-05-22 15:51:03,012 [root] INFO: Analysis completed
```

**Comment by seanthegeek** [comment]
Ignore me. Somehow my conf files got overwritten.
