### ISSUE TITLE
Hanging at running status, then failed_analysis !!

### ISSUE THREAD

**Issue by AnduinBrian** [kevoreilly/CAPEv2#1557]
# Prerequisites

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Run and get report for a redline malware sample.

# Current Behavior

Hang at status *running* for 3 - 4 min and change to *failed_analysis*
Sometime the status is *reported*, but there is an error "The specified analysis does not exist or not finished yet" 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run cuckoo.py with cli: "python3 cuckoo.py"
2. go to web interface and submit
3. wait and more wait
4. *failed_analysis*

## Context

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04 LTS

## Failure Logs

cuckoo.py:
```
OPTIONAL! Missed dependency: pip3 install https://github.com/CAPESandbox/peepdf/archive/20eda78d7d77fc5b3b652ffc2d8a5b0af796e3dd.zip#egg=peepdf==0.4.2
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/DissectMalware/batch_deobfuscator
OPTIONAL! Missed dependency: poetry run pip install -U git+https://github.com/CAPESandbox/httpreplay
2023-05-30 09:29:32,507 [root] INFO: Updated running task ID 13 status to failed_analysis
2023-05-30 09:29:32,606 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager with max_analysis_count=0, max_machines_count=10, and max_vmstartup_count=5
2023-05-30 09:29:32,874 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2023-05-30 09:29:32,876 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks
2023-05-30 09:29:53,064 [lib.cuckoo.core.scheduler] INFO: Task #14: File already exists at '/opt/CAPEv2/storage/binaries/7ec9f0098df015190615ac77ffdfb043c93e2c91326c1be3316a1d00ee8b1154'
2023-05-30 09:29:53,064 [lib.cuckoo.core.scheduler] INFO: Task #14: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_ip9wdaa2/inject.exe'
2023-05-30 09:29:53,079 [lib.cuckoo.core.scheduler] INFO: Task #14: acquired machine cuckoo1 (label=Win10, arch=x64, platform=windows)
2023-05-30 09:35:25,203 [lib.cuckoo.core.scheduler] ERROR: Timeout hit while for machine Win10 to change status
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 337, in launch_analysis
    machinery.start(self.machine.label)
  File "/opt/CAPEv2/modules/machinery/virtualbox.py", line 73, in start
    self._wait_status(label, self.SAVED)
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 334, in _wait_status
    raise CuckooMachineError(f"Timeout hit while for machine {label} to change status")
lib.cuckoo.common.exceptions.CuckooMachineError: Timeout hit while for machine Win10 to change status
2023-05-30 09:35:25,311 [lib.cuckoo.core.scheduler] WARNING: Task #14: Unable to stop machine Win10: Trying to stop an already stopped vm Win10
2023-05-30 09:35:25,322 [lib.cuckoo.core.scheduler] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 452, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 428, in launch_analysis
    raise CuckooDeadMachine()
lib.cuckoo.core.scheduler.CuckooDeadMachine
2023-05-30 09:35:25,330 [lib.cuckoo.core.scheduler] INFO: Task #14: File already exists at '/opt/CAPEv2/storage/binaries/7ec9f0098df015190615ac77ffdfb043c93e2c91326c1be3316a1d00ee8b1154'
2023-05-30 09:35:25,330 [lib.cuckoo.core.scheduler] INFO: Task #14: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_ip9wdaa2/inject.exe
```

**Comment by doomedraven** [comment]
your vm is not configured properly. or your took snapshot in wrong state or agent is not running

**Comment by AnduinBrian** [comment]
I see, i can run the sample now.
The report appear in storage/<id> folder but dont show up on web

**Comment by doomedraven** [comment]
for that you need to check web or processing output, maybe you didn't enable/install mongo/es? maybe you added something that breaks it, there is tons of possibilities. i need more details

check out `logs` for processing logs

**Comment by AnduinBrian** [comment]
I will do some debug at background first. Thanks for the answer

**Comment by doomedraven** [comment]
you are welcome, let us know what it was, so other maybe can find that useful
