### ISSUE TITLE
KeyError: (<weakref at 0x7fbf4a8f5d68; to 'function' at 0x7fbf43b9dd90 (go)>,) 

### ISSUE THREAD

**Issue by helios4281** [kevoreilly/CAPEv2#156]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Cuckoo to proceed with its execution

# Current Behavior

Exited with the error below:

# Failure Information (for bugs)

Exception ignored in: <bound method Database.del of <lib.cuckoo.core.database.Database object at 0x7fbefcf22828>>
Traceback (most recent call last):
File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 447, in del
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2039, in dispose
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 251, in recreate
File "", line 2, in init
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 221, in init
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/event/base.py", line 150, in _update
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 392, in _update
File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: (<weakref at 0x7fbf4a8f5d68; to 'function' at 0x7fbf43b9dd90 (go)>,) 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

first installation of cuckoo.  i ran cape2.sh, seems to be installing well.  but when i execute it, i have the above error.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | na
| OS version       | Ubuntu 18.04.4 LTS

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
That is sqlalchemy problem,
You skipped whole template of questions that could help us help you solving
the issue having all core details

Try tro resintall/upgrade sqlalchemy

**Comment by doomedraven** [comment]
closing due to  lack of feedback, let us know if upgrading sqlalchemy that solved your problem

**Comment by helios4281** [comment]
already reinstalled/upgraded sqlalchemy. still have same issue.  current sqlalchemy version:  sqlalchemy-1.3.15

**Comment by doomedraven** [comment]
hm i can't reproduce it in any of 2 servers that we running with v2,
 i have pushed tht part under try/except can you `git pull` and try again and post output if ti fails?

**Comment by helios4281** [comment]
you can close/ignore this case.  i'll try to start from the scratch. thanks for the help though.

**Comment by doomedraven** [comment]
let us know what solves that for you
