### ISSUE TITLE
Unhandled CAPA exceptions when not on demand cause entire processing of the task to fail

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1565]
When the `on_demand` setting is set to `no` in the `CAPA` section of `processing.conf`, CAPA in ran on every sample, payload and dump as a part of the final processing of the analysis, before the results are displayed to the user. It turns out that if unhandled CAPA exceptions occur during this time, the entire task will fail with the status of `failed_processing`.

The configuration file hints that the `on_demand` setting should be kept set to `yes`, but the English isn't clear.

> still should be enabled to use this feature on demand

For example, this sample triggers this condition. https://capesandbox.com/analysis/393763/ 60711919ef00c7bff67dbeb8dfa743525c23a10becdf14d1214ce6dbf94d2f5b

```python
2023-05-30 20:19:20,349 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
023-05-30 20:20:41,645 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/aca1a538b04254feb5844ddb3ab55aadc39d5959799ba7cdc8ce996ddd76fb21
2023-05-30 20:20:41,661 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:20:41,662 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:21:15,516 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/80d17f8066f5a467a0bb92f64e07eb8a1e779adba5651819da07243e7fa2b45e
2023-05-30 20:21:15,533 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:21:15,534 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:21:16,647 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/2200078132d0e03deb0c48e785b614c1b68e7b8cc21ee0efc71809f7637a83fb
2023-05-30 20:21:16,647 [Task 2] [modules.processing.CAPE] INFO: CAPE: config returned for: QakBot
2023-05-30 20:21:16,647 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:21:17,532 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Duplicate payload skipped: ssdeep grade 99, threshold 95
2023-05-30 20:21:52,360 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/cf6735a437e3970e330b63a645f0f0ba49098b536ef1342bd4ef49fba38b8ac1
2023-05-30 20:21:52,375 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:21:52,375 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:21:53,169 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: 00000000
2023-05-30 20:21:53,170 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:21:54,131 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: 00000000
2023-05-30 20:21:54,132 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:22:28,148 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/09e646ad3a928d4508932c0aec8d7debdc7829cc1cbe29c0637b9691687108c9
2023-05-30 20:22:28,165 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:22:28,165 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:22:28,927 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: 00000000
2023-05-30 20:22:28,927 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:23:06,425 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/171f538bdb25ad588a6fcbc3e98995c02b3371a4e2540fe738326f4d9d73c66e
2023-05-30 20:23:06,443 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:23:06,443 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Duplicate payload skipped: ssdeep grade 99, threshold 95
2023-05-30 20:23:06,444 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:23:07,345 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: 00000000
2023-05-30 20:23:07,346 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:23:08,107 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: 00000000
2023-05-30 20:23:08,107 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:23:08,842 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Duplicate payload skipped: ssdeep grade 99, threshold 95
2023-05-30 20:23:43,834 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/c665558c79e96adae87e50b95ac319e9557266429416fb8c3b12f8052919fdfe
2023-05-30 20:23:43,862 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:23:43,879 [Task 2] [capa] DEBUG: generating vivisect workspace for: /opt/CAPEv2/storage/analyses/2/CAPE/c665558c79e96adae87e50b95ac319e9557266429416fb8c3b12f8052919fdfe
2023-05-30 20:23:47,953 [Task 2] [capa] DEBUG: format: pe, platform: windows, architecture: i386, number of functions: 595
2023-05-30 20:23:47,953 [Task 2] [capa] DEBUG: CAPA_SAVE_WORKSPACE unset, not saving workspace
2023-05-30 20:23:55,204 [Task 2] [capa] DEBUG: analyzed function 0x100194c0 and extracted 41 features
2023-05-30 20:23:55,226 [Task 2] [capa] DEBUG: analyzed file and extracted 1260 features
2023-05-30 20:23:56,363 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: e99f0000
2023-05-30 20:23:56,363 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:24:32,286 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/a356c36ed5d40ccee3a07504d816029342ada0de6e80f1418ae192fdb493316c
2023-05-30 20:24:32,302 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:24:32,302 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Duplicate payload skipped: ssdeep grade 99, threshold 95
2023-05-30 20:24:32,302 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:24:33,096 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Duplicate payload skipped: ssdeep grade 99, threshold 95
2023-05-30 20:25:06,479 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: Running CAPE on /opt/CAPEv2/storage/analyses/2/CAPE/7453b55235dc1ef218da1f3ab459b898f8cb39c6fe634208001ba96c03c1c0bd
2023-05-30 20:25:06,496 [Task 2] [modules.processing.CAPE] WARNING: CAPE: data loss may occur, existing config found for: QakBot
2023-05-30 20:25:06,496 [Task 2] [lib.cuckoo.common.cape_utils] DEBUG: CAPE duplicate output file skipped: matching entrypoint
2023-05-30 20:25:07,393 [Task 2] [capa.features.extractors.common] DEBUG: unsupported file format: 00000000
2023-05-30 20:25:07,393 [Task 2] [lib.cuckoo.common.integrations.capa] ERROR: 
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/capa.py", line 240, in flare_capa_details
    extractor = capa.main.get_extractor(file_path, "auto", capa.main.BACKEND_VIV, [], False, disable_progress=True)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/capa/main.py", line 503, in get_extractor
    raise UnsupportedFormatError()
capa.exceptions.UnsupportedFormatError
2023-05-30 20:25:13,304 [Task 2] [capa] DEBUG: generating vivisect workspace for: /opt/CAPEv2/storage/analyses/2/procdump/986df92535657d5337e356081eb833d8a26e3187e04b12083f0a742543dd1479
2023-05-30 20:25:13,470 [Task 2] [capa] DEBUG: format: pe, platform: windows, architecture: i386, number of functions: 31
2023-05-30 20:25:13,470 [Task 2] [capa] DEBUG: CAPA_SAVE_WORKSPACE unset, not saving workspace

2023-05-30 20:31:24,761 [Task 2] [capa] DEBUG: analyzed file and extracted 464 features
```

**Comment by doomedraven** [comment]
idk how it can break if is under generic try/except, anyway added also UnsupportedFormatError handler here https://github.com/kevoreilly/CAPEv2/commit/38de7de6bb5b90aac703e7bd7d5bad96406b13b6
