### ISSUE TITLE
extra/poetry_libvirt_installer.sh does not work beyond 9.3.0

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#1581]
As I was trying out the existing install scripts with newer versions of dependencies, I noticed that `libvirt` 9.4.0 installs correctly on a system level using `installer/kvm-qemu.sh`, but using `extra/poetry_libvirt_installer.sh` to install `libvirt` in the Poetry environment only works up to `libvirt` 9.3.0 (the script is currently configured to install `libvirt` 9.0.0) not sure if/when `libvirt` >=9.4.0 will be needed though. Just thought I'd call it out.

```python
running build
running build_py
Traceback (most recent call last):
  File "/tmp/libvirt-python-9.4.0/generator.py", line 1794, in <module>
    emit_py_code(sys.argv[1])
  File "/tmp/libvirt-python-9.4.0/generator.py", line 1319, in emit_py_code
    classes = open(classes_file, "w")
PermissionError: [Errno 13] Permission denied: 'build/libvirt.py'
Traceback (most recent call last):
  File "/tmp/libvirt-python-9.4.0/setup.py", line 337, in <module>
    setup(name = 'libvirt-python',
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/libvirt-python-9.4.0/setup.py", line 155, in run
    subprocess.check_call([sys.executable, "generator.py", "libvirt", apis[0], "py"])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python3', 'generator.py', 'libvirt', '/usr/share/libvirt/api/libvirt-api.xml', 'py']' returned non-zero exit status 1.
Processing /tmp/libvirt-python-9.4.0
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: libvirt-python
  Building wheel for libvirt-python (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      running bdist_wheel
      running build
      running build_py
      Traceback (most recent call last):
        File "/tmp/libvirt-python-9.4.0/generator.py", line 1794, in <module>
          emit_py_code(sys.argv[1])
        File "/tmp/libvirt-python-9.4.0/generator.py", line 1319, in emit_py_code
          classes = open(classes_file, "w")
      PermissionError: [Errno 13] Permission denied: 'build/libvirt.py'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/libvirt-python-9.4.0/setup.py", line 337, in <module>
          setup(name = 'libvirt-python',
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/libvirt-python-9.4.0/setup.py", line 155, in run
          subprocess.check_call([sys.executable, "generator.py", "libvirt", apis[0], "py"])
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python', 'generator.py', 'libvirt', '/usr/share/libvirt/api/libvirt-api.xml', 'py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libvirt-python
  Running setup.py clean for libvirt-python
Failed to build libvirt-python
ERROR: Could not build wheels for libvirt-python, which is required to install pyproject.toml-based projects
```

**Comment by seanthegeek** [comment]
D'oh! I'm an idiot. Imade a mistake when running the script the first time, which messsed up the permissions in /tmp

**Comment by veleus** [comment]
how u sloved this problem?
