### ISSUE TITLE
Web Interface Reports : ERROR :-( The specified analysis does not exist or not finished yet

### ISSUE THREAD

**Issue by v1ctorp1vert** [kevoreilly/CAPEv2#1682]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior
When I'm doing an analysis I would expect to have the report on the webservice.

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Submit sample using either submit.py or the web interface. 
2. Wait for the analysis to be ran
3. Process the analysis
4. Get the report

I ran process.py with the debug mode on to see if it would catch any error but couldn't find anything related to the report section.
The last line of the output are :
INFO:root:Reports generation completed
2023-08-01 07:23:32,616 [root] INFO: Reports generation completed

When I go in /opt/CAPEV2/storage/analysis/{id}/reports/ I can see both report.html and report.json
But I still have this error on the webpage :
![image](https://github.com/kevoreilly/CAPEv2/assets/95937827/e5850b7f-6034-451f-bddc-c91d721ced61)

## Context

I'm running Ubuntu 22.04 in a VMWare VM. 
I did a fresh base install
I'm using KVM for the analysis with Windows 10.

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 50e4492ca2dafe795ac9a59cb783fd1797bc4b01
| OS version       | Ubuntu 22.04.2 LTS

## Failure Logs

Those are the only error I have when I run `sudo -u cape poetry run python3 utils/process.py -d auto` :

```
OPTIONAL! Missed dependency: pip3 install https://github.com/CAPESandbox/peepdf/archive/20eda78d7d77fc5b3b652ffc2d8a5b0af796e3dd.zip#egg=peepdf==0.4.2
OPTIONAL! Missed dependency: pip3 install -U git+https://github.com/DissectMalware/batch_deobfuscator
Missed dependency: pip3 install volatility3 -U
name 'JsonRenderer' is not defined
OPTIONAL! Missed dependency: poetry run pip install -U git+https://github.com/CAPESandbox/httpreplay
Unable to import plugin "modules.processing.sysmon": No module named 'xmltodict'
INFO:root:Processing analysis data
2023-08-01 07:19:18,075 [root] INFO: Processing analysis data
```

```
ERROR:lib.cuckoo.core.plugins:Failed to run signature "uses_windows_utilities": 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 465, in process
    data = signature.run()
  File "/opt/CAPEv2/utils/../modules/signatures/windows_utilities.py", line 479, in run
    if init_cmd.lower().startswith(GENERIC_CMD):
AttributeError: 'NoneType' object has no attribute 'lower'
2023-08-01 07:23:32,255 [Task 7] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "uses_windows_utilities": 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 465, in process
    data = signature.run()
  File "/opt/CAPEv2/utils/../modules/signatures/windows_utilities.py", line 479, in run
    if init_cmd.lower().startswith(GENERIC_CMD):
AttributeError: 'NoneType' object has no attribute 'lower'
2023-08-01 07:23:32,255 [Task 7] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "uses_windows_utilities": 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 465, in process
    data = signature.run()
  File "/opt/CAPEv2/utils/../modules/signatures/windows_utilities.py", line 479, in run
    if init_cmd.lower().startswith(GENERIC_CMD):
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by doomedraven** [comment]
hello, did you enable the mongodb in reporting.conf? did you install mongo also and configured it properly?

**Comment by v1ctorp1vert** [comment]
Hello, I did enable mongodb in reporting.conf, I ran the cape2.sh installer in base mode so yes mongodb is installed. I didn't edit the configuration for mongodb, should I modify something?

Also when I'm trying to run sudo -u cape poetry run python web/manage.py runserver_plus 0.0.0.0:8000 --traceback --keep-meta-shutdown
I get this : 

```
Traceback (most recent call last):
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 259, in fetch_command
    app_name = commands[subcommand]
KeyError: 'runserver_plus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/web/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 266, in fetch_command
    settings.INSTALLED_APPS
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/CAPEv2/web/web/settings.py", line 20, in <module>
    from lib.cuckoo.common.config import Config
ModuleNotFoundError: No module named 'lib.cuckoo'
```
Did I messed something up?

**Comment by doomedraven** [comment]
Yes, google this KeyError: 'runserver_plus'
 You have missed dependencies, +try torun from inside of web folder

**Comment by v1ctorp1vert** [comment]
I tried to run from the web dir but wasn't successful. The error seems to be related to the missing module lib.cuckoo.
Is there any way I can install it? I ran the poetry install but didn't find any updates or new dependencies to run.

**Comment by doomedraven** [comment]
That module is part of cape, and is inside of the lib/cuckoo/common/config
so it cant be missed

**Comment by doomedraven** [comment]
cd /opt/CAPEv2
poetry run pip install django-extensions
Then try to start the web

**Comment by v1ctorp1vert** [comment]
All the requirements were already satisfied. but still the same error ModuleNotFoundError: No module named 'lib.cuckoo'

**Comment by doomedraven** [comment]
That not make any sense

**Comment by s-Fl** [comment]
Had the same issue. I also had an error in `cape-web` logs while performing analysis: `WARNING:root:PyMongo auto-reconnecting...127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64c9250c3f2bec1a22e7da16, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>. Waiting 1.0 seconds`

I used [this answer](https://stackoverflow.com/a/68973140) to reinstall MongoDB. Then I:
- Changed `bindIp` value from `127.0.0.1` to `0.0.0.0` in `/etc/mongod.conf`
- Restarted mongod service: `sudo systemctl restart mongod`
- Restarted all cape services: `sudo systemctl restart cape*`
And it solved the problem - can now view data from analysis using web interface.

**Comment by doomedraven** [comment]
here is the problem, mongod is not our systemd file, our one is mongodb, we remove systemd as we use it only in clustered cape

**Comment by doomedraven** [comment]
my main suggestion in case if you have mongo problem, is to investigate mongo log, otherwise on long run you can generate more problem on conflicting services, but thanks for tip

**Comment by doomedraven** [comment]
@v1ctorp1vert what if you run just like this? `cd /opt/CAPEv2/web && sudo -u cape poetry run python manage.py runserver 0.0.0.0:8000`

**Comment by doomedraven** [comment]
np, yes something is messed here
