### ISSUE TITLE
CAPE Agent Failure

### ISSUE THREAD

**Issue by CarsonHrusovsky** [kevoreilly/CAPEv2#1705]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Cape agent executes correctly.

# Current Behavior

Cape agent failure without error status. This can happen on its own but overwhelmingly seems to happen when a lot of activity is seen at the same time by the processor. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit a few analysis at the same time. Usually all the same type. Can also appear if I submit the same URL again after the first analysis.
2. CAPE Agent failure / Connection reset by peer.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       Updated today - 08/15/2023 from master.
| OS version       | Ubuntu 22.04, Windows 10s Virtual Machines, VMWare ESXI

```
2023-08-15 21:06:48,757 [lib.cuckoo.core.guest] INFO: Task #615: Starting analysis on guest (id=REDACTED, ip=X.X.X.X)
2023-08-15 21:06:58,994 [lib.cuckoo.core.guest] INFO: Task #614: Guest is running CAPE Agent 0.11 (id=REDACTED, ip=X.X.X.X)
2023-08-15 21:06:59,699 [lib.cuckoo.core.scheduler] ERROR: CAPE Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.10) and notify us if the issue persists
Traceback (most recent call last):
File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
[2102]:     response = self._make_request(
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
[2102]:     conn.request(
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 402, in request
[2102]:     self.send(chunk)
[2102]:   File "/usr/lib/python3.10/http/client.py", line 999, in send
[2102]:     self.sock.sendall(data)
[2102]: ConnectionResetError: [Errno 104] Connection reset by peer
[2102]: During handling of the above exception, another exception occurred:
[2102]: Traceback (most recent call last):
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
[2102]:     resp = conn.urlopen(
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
[2102]:     retries = retries.increment(
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
[2102]:     raise reraise(type(error), error, _stacktrace)
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
[2102]:     raise value.with_traceback(tb)
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
[2102]:     response = self._make_request(
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
[2102]:     conn.request(
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 402, in request
[2102]:     self.send(chunk)
[2102]:   File "/usr/lib/python3.10/http/client.py", line 999, in send
[2102]:     self.sock.sendall(data)
[2102]: urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2102]: During handling of the above exception, another exception occurred:
[2102]: Traceback (most recent call last):
[2102]:   File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 126, in post
[2102]:     r = session.post(url, *args, **kwargs)
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
[2102]:     return self.request("POST", url, data=data, json=json, **kwargs)
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[2102]:     resp = self.send(prep, **send_kwargs)
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[2102]:     r = adapter.send(request, **kwargs)
[2102]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
[2102]:     raise ConnectionError(err, request=request)
[2102]: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2102]: During handling of the above exception, another exception occurred:
[2102]: Traceback (most recent call last):
[2102]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 355, in launch_analysis
[2102]:     guest.start_analysis(options)
[2102]:   File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 291, in start_analysis
[2102]:     self.upload_analyzer()
[2102]:   File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 196, in upload_analyzer
[2102]:     self.post("/extract", files={"zipfile": zip_data}, data=data)
[2102]:   File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 128, in post
[2102]:     raise CuckooGuestError(
[2102]: lib.cuckoo.common.exceptions.CuckooGuestError: CAPE Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.10) and notify us if the issue persists
```

This is my second post on here addressing this issue - my initial post did not gain much traction. Finally got around to making sure everything is up to date and yet this error still persists. Usually if submitting one or two links every few minutes there is no problem, but a few too many in close succession and we are met with this. Thank you for any help!

**Comment by doomedraven** [comment]
that is the server side problem that for some reason closes connection, but why it closes it i have no idea. as i rarely see this issue. you will have to invistegate on your own

**Comment by CarsonHrusovsky** [comment]
Server side meaning on the side of the virtual host or on the side of the Cape host machine?

**Comment by doomedraven** [comment]
cape host machine, aka result server. reasons for that can be 100, like if you have docker for example, it installs it own network driver and in past it was messing a lot with cape's networking, etc. so it really depends on the extra things that you have on your host

**Comment by doomedraven** [comment]
but as we don't experience this, we won't be able to help

**Comment by CarsonHrusovsky** [comment]
thank you @doomedraven always very helpful and you've given me a good place to start looking

**Comment by CarsonHrusovsky** [comment]
hey doom is the api pretty much deprecated? I know it says that on the readthedocs but it has been giving me quite a bit of trouble with rate limiting and throttling (how I am fixing the above issue is just using API to see if issue arise and replace broken analysis with resubmission of new one). Despite going into api.conf and cranking up the rates and removing throttling seems to have no impact on getting throttled with api if 3 api request are sent in close succession.
