### ISSUE TITLE
More URL analysis issue?

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#181]
I just got this error while analyzing a URL:

```
2020-04-21 05:05:21,726 [lib.api.process] INFO: Successfully executed process from path "C:\Program Files (x86)\Internet Explorer\iexplore.exe" with arguments ""http://xxxxxxx"" with pid 4128
2020-04-21 05:05:22,414 [lib.api.process] INFO: Monitor config for process 4128: C:\tmp0pm2gis2\dll\4128.ini
2020-04-21 05:05:30,564 [root] ERROR: Traceback (most recent call last):
  File "C:/tmp0pm2gis2/analyzer.py", line 517, in run
    pids = pack.start(self.target)
  File "C:\tmp0pm2gis2\modules\packages\ie.py", line 17, in start
    return self.execute(iexplore, "\"%s\"" % url, url)
  File "C:\tmp0pm2gis2\lib\common\abstracts.py", line 134, in execute
    p.inject(INJECT_QUEUEUSERAPC, interest)
  File "C:\tmp0pm2gis2\lib\api\process.py", line 626, in inject
    self.write_monitor_config(interest, nosleepskip)
  File "C:\tmp0pm2gis2\lib\api\process.py", line 563, in write_monitor_config
    config.write("referrer={0}\n".format(get_referrer_url(interest)))
  File "C:\tmp0pm2gis2\lib\api\process.py", line 62, in get_referrer_url
    vedstr = "0CCEQfj" + base64.urlsafe_b64encode(random_string(random.randint(5, 8) * 3))
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38-32\lib\base64.py", line 118, in urlsafe_b64encode
    return b64encode(s).translate(_urlsafe_encode_translation)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38-32\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by doomedraven** [comment]
one more thing when you report issue please provide full details, as just error is ok but i can't reproduce it by myself so i need to know all steps and options that you used

**Comment by xme** [comment]
Sorry for this... It has been submitted via the API...
Here is the code snippet:

```
    def submit_url(self, target_url, options):
        url = urljoin(self.web_endpoint, '/api/tasks/create/url/')
        options['url'] = target_url
        response = requests.post(url, data=options)
        try:
            self.task_id = response.json()['data']['task_ids'][0]
        except:
            raise ModuleExecutionError('{0}'.format(response.json()['error_value']))
```

No other specific options...

**Comment by doomedraven** [comment]
thanks, should be tested now, i have pushed code that fix that bytes vs str, let me know if that is fixed

**Comment by xme** [comment]
Updated to latest push and seems ok, tx!

**Comment by doomedraven** [comment]
Thanks for feedback
