### ISSUE TITLE
Error run command "poetry run python3 manage.py migrate"

### ISSUE THREAD

**Issue by eingel86** [kevoreilly/CAPEv2#1961]
Dear Community,

I wanted to activate the web interface auth on Capev2. When I try to run the command 'poetry run python3 manage.py migrate' I get all the following errors. Can you help me understand why? Thank you very much.

/opt/CAPEv2/web$ poetry run python3 manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, openid, sessions, sites, socialaccount, users
Running migrations:
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 324, in execute
    return super().execute(query)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 451, in create_model
    self.execute(sql, params or None)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 324, in execute
    return super().execute(query)
django.db.utils.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/web/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/migrations/executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "/home/user/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 72, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (attempt to write a readonly database)

**Comment by doomedraven** [comment]
`sqlite3.OperationalError: attempt to write a readonly database` that is permission problem, how did you run everything? you missed that byte of details

**Comment by eingel86** [comment]
Dear @doomedraven doomedraven,

thank you for your reply, I used a user who is inside the sudo group but is not root.

Should I run the command with sudo first?

sudo poetry run python3 manage.py migrate

Regards
Engel

**Comment by doomedraven** [comment]
did you read docs? never as root, it should be executed only as cape user, if you run it with another users you will get into a lot of permission problems as you have now. https://capev2.readthedocs.io/en/latest/

**Comment by eingel86** [comment]
Thank you, I have followed this guide: [https://capev2.readthedocs.io/en/latest/usage/web.html](https://capev2.readthedocs.io/en/latest/usage/web.html) and the command they say to run is not correct, using instead the command: sudo -u cape poetry run python3 manage.py migrate I get no errors. Thanks for the tip.

**Comment by doomedraven** [comment]
what command is wrong?

**Comment by eingel86** [comment]
The web help instructs you to run the command like this:
![image](https://github.com/kevoreilly/CAPEv2/assets/82473625/90220bd7-59f1-4a1d-9a56-57f84fc2c7f1)

but it gave me an error. Instead, running the command by first entering 'sudo -u cape' then like this: 'sudo -u cape poetry run python3 manage.py migrate'

I did not receive the error and was able to complete the procedure.

Engel

**Comment by doomedraven** [comment]
that because you should run everything as `cape` user in `cape`. that your `sudo -u cape` is just change to cape user. so command is correct. read docs carefully please https://capev2.readthedocs.io/en/latest/installation/host/installation.html#attention-cape-user
