### ISSUE TITLE
Can't use the aws machinery due to  KeyError: 'arch' in ./lib/cuckoo/common/abstracts.py

### ISSUE THREAD

**Issue by Y4nush** [kevoreilly/CAPEv2#1978]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ * ] I am running the latest version
- [ * ] I did read the README!
- [ * ] I checked the documentation and found no answer
- [ * ] I checked to make sure that this issue has not already been filed
- [ * ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ * ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Hi, Im trting to run perform analysis with CAPE using aws machinery

# Current Behavior

While looking at the journalctl logs i have seen that i me getting the following KeyError machine.arch = machine_opts["arch"]
Altought i didn't saw any option to specify arch in the aws.conf such as in kvm.conf

# Failure Information (for bugs)

```
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]: Traceback (most recent call last):
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:   File "/opt/CAPEv2/cuckoo.py", line 139, in <module>
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:     cuckoo_main(max_analysis_count=args.max_analysis_count)
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:   File "/opt/CAPEv2/cuckoo.py", line 100, in cuckoo_main
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:     sched.start()
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 967, in start
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:     self.initialize()
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 890, in initialize
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:     machinery.initialize(machinery_name)
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:   File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 132, in initialize
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:     self._initialize(module_name)
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:   File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 155, in _initialize
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]:     machine.arch = machine_opts["arch"]
Feb 22 16:34:25 ip-172-31-37-191 python3[3155]: KeyError: 'arch'
Feb 22 16:34:25 ip-172-31-37-191 systemd[1]: cape.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 16:34:25 ip-172-31-37-191 systemd[1]: cape.service: Failed with result 'exit-code'.
Feb 22 16:34:25 ip-172-31-37-191 systemd[1]: cape.service: Consumed 3.428s CPU time.

```
## Steps to Reproduce

That is the conf file that i have used:
```
[aws]
# Specify the AWS Region (for example, us-west-1)
region_name = censored
# Specify the Availability Zone(for example, us-west-1a) to create a new volume (used at machine's restoration).
availability_zone = censored
# Access keys consist of two parts: an access key ID (for example, AKIAIOSFODNN7EXAMPLE)
# and a secret access key (for example, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY).
# To create access keys for your AWS account root user, you must use the AWS Management Console.
aws_access_key_id = censored
aws_secret_access_key = censored

# Specify a comma-separated list of available machines to be used.
# Each machine will be represented by the instance-id (for example, i-05f07711c635f817f).
# For each specified instance-id you have to define a dedicated section containing the details
# on the respective machine. (E.g. i-05f07711c635f817f,i-04d465547cba1af5e)
# For better performance, it is recommended to leave this empty and set autoscale = yes.
machines = censored

# Default network interface.
interface = eth0

# To improve the performance, running_machines_gap is number of machines that are ready to perform a task (up and running).
# running_machines_gap is the size of a pool which contains machines that were already started in advance.
# Whenever a machine from the pool starts a task, the machinery will start another new machine.
# In a scenario where all the list of machines are occupied, and autoscale mode is on, the machinery will instantly
# scale up by creating new machines.
# Thus, there will always be a constant number of ready machines for the user's requests.
# It is recommended to set this value to 1 and above.
running_machines_gap = 1

# In a scenario where all the configured machines are occupied, the machinery will instantly scale up by creating
# new machines and adding them to the Cuckoo internal database (DB). The new machines will be terminated after use.

# The user can choose to prepare any number of machines, but does not have to (if autoscale in on).

[autoscale]

# Enable auto-scale in cuckoo(by setting autoscale = yes). recommended for better performance.
autoscale =

# Specify the maximum number of online machines that was created as a result of auto-scale operation.
# Once reaching that limit, cuckoo will create a new machine only if another was terminated.
# This limit prevents a situation of creating machine beyond the subnet capacity.
dynamic_machines_limit = 2

# Specify the Amazon Machine Image (AMI). It required to launch a new instance.
# You should create an image from the guest machine.
image_id = censored

# Specify the machine's instance type(for example, t2.small)
instance_type = t2.medium

# Specify the subnet id where the machines will be placed
subnet_id = censored

# Specify a comma-separated list of security groups IDs that will be associated with the machines.
# On the Cuckoo default settings ,the security groups must allow tcp ports 2042,8000 and 8090 on the inbound.
security_groups = censored

# Specify the operating system platform used by the new machine
# [windows/darwin/linux].
platform = windows

# Default network interface.
interface = eth0

# Mostly unused for now. Please don't fill it out.
options =

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags =

# Specify the IP of the Result Server, as your virtual machine sees it.
# It should be the nest ip address.
resultserver_ip = 172.31.37.191

# Specify a port number to bind the result server on.
resultserver_port = 2042



# This section is just a template for one pre-configured machine, if you choose to use it.
# For better performance, it is best to leave it blank and let the auto-scaling to control the machines.

[censored]
# Specify the label name.
# Label would be the instance-id of the current machine as specified in your AWS account.
label = censored

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 172.31.37.191

# Specify the snapshot-id to use. it is used when creating a new volume when restoring a machine.
# You should create a snapshot from the guest machine.
snapshot = censored

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified above.
# Example (eth0 is the interface name):
interface = eth0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip =

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
resultserver_port =

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags =

# Mostly unused for now. Please don't fill it out.
options =
```

1. Use the conf file with your recources, not on auto-scaling mode 
2. 
```
journalctl -u cape.service -f
```

## Context

Im using ubuntu 22.04 server on AWS, installed with the reguler installation script (base) and poetry. 
I managed to spin-up the EC2 by modifying /opt/CAPEv2/lib/cuckoo/common/abstracts.py but it breaked other componnets

Thank you for your support

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
just add `arch=X` where x is x64 or x86, we do not support aws officially as we don't have setup, that is community module

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/commit/7880b18aa014322019d6a10b82477f0e1db2025e

**Comment by doomedraven** [comment]
is this fixed?

**Comment by Y4nush** [comment]
@doomedraven Thank you so much for your quick response!
Unfortunately, after doing that, it broke the web-server component: "./web/submission/views.py"
```
File "/opt/CAPEv2/web/submission/views.py", line 550, in <listcomp>
break
else:
# Get VM names for machinery config elements
vms = [x.strip() for x in str(getattr(Config(machinery), machinery).get("machines")).split(",") if x.strip()]
# Check each VM config element for tags
if any(["tags" in list(getattr(Config(machinery), vmtag).keys()) for vmtag in vms]):
enabledconf["tags"] = True
packages, machines = get_form_data("windows")

socks5s = _load_socks5_operational()
AttributeError: 'Config' object has no attribute 'none'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback, you can also create a paste of it. For code execution, mouse-over the frame you want to debug and click on the console icon on the right side.
```
I managed to overcome this by changing the variable arch under the function acquire from the Class Machinery to None.

After resolving that error, I had another error caused by lib/cuckoo/core/scheduler.py

```
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 618, in run
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]:     success = self.launch_analysis()
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 478, in launch_analysis
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]:     self.acquire_machine()
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]:   File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 355, in acquire_machine
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]:     machine = machinery.acquire(
Feb 22 20:26:26 ip-172-31-37-191 python3[1354]: TypeError: AWS.acquire() got an unexpected keyword argument 'arc

```
I have deleted all of the non-relevant tags (for my use case) and left only

```
            machine = machinery.acquire(
                machine_id=self.task.machine,
                platform=self.task.platform,
                tags=task_tags,
                arch=task_archs,
                os_version=os_version,
                need_scheduled=True,

```
Unfortunately, it didn't work as well, and I decided to go back in time to https://github.com/kevoreilly/CAPEv2/tree/a8298eaa8f7ecbd71163f0677972e60bc1408ca8 the last time JaminB has modified the aws.py component. I installed CAPEv2 using the repository at that point on Ubuntu 20.04 by making modifications to your old installation script and using that repo instead of the original.

After completing the installation of the old version, I added the arch = x64 again, and this evrything worked as expected

**Comment by doomedraven** [comment]
yes nobody maintains the aws machinery, but that should be easy i guess just checking azure module if you want to be on latest

**Comment by doomedraven** [comment]
so is up to you, you can keep trying using latest version and help to fix, or use that old version without updates

**Comment by doomedraven** [comment]
https://github.com/kevoreilly/CAPEv2/pull/1980 Closing thia as issue is solved now, let us know if you find any other

**Comment by loust** [comment]
I had the same issue with this, specifically when not using the `autoscaling = no`. I've placed the snapshot ID, the instance ID.
You can now place the `arch=x64` under the `[machinename]` config section in `aws.conf`. This will read the arch and continue working.
However, now you'll get another issue with it relying on an AMI ID, which is not required, but it mandates it, giving an error like this:
```Failure in AnalysisManager.run: An error occurred (InvalidAMIID.Malformed) when calling the RunInstances operation: Invalid id: "ami-abcdefgh123456789" (expecting "ami-...")```
Even though AMI ID is not required when setting it with a specific machine name and ID, it still relies on it.

**Comment by doomedraven** [comment]
but this doesn't look like cape error, it looks like some configuration problem?
