### ISSUE TITLE
[cuckoo] Cuckoo fails to start: AttributeError: 'Scheduler' object has no attribute 'task'

### ISSUE THREAD

**Issue by dfr-fands** [kevoreilly/CAPEv2#2073]
```
$ sudo -u cape /usr/bin/python3 -m poetry run python cuckoo.py -d
...
2024-04-18 10:54:38,659 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks
Traceback (most recent call last):
  File "/opt/CAPEv2/cuckoo.py", line 139, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "/opt/CAPEv2/cuckoo.py", line 100, in cuckoo_main
    sched.start()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 1123, in start
    if self.task.category in ("file", "pcap", "static"):
AttributeError: 'Scheduler' object has no attribute 'task'
```

Seems related to this commit https://github.com/kevoreilly/CAPEv2/commit/bfce3fdda4803605a8e65bdbbd88cb062e8655d2 . `task` is not a class variable, its a local variable and therefore the line should be:
```
if task.category in ("file", "pcap", "static"):
```

After changing that cuckoo starts normally.

**Comment by doomedraven** [comment]
was working on that right now, pushed that, thanks for headups
