### ISSUE TITLE
Memory processing module crash

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#2075]
## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

I enabled memory processing and many options in memory.conf. When a sample is analysed, the memory dmp file is properly stored on the server but I can't run the Volatility. 
# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

```
2024-04-19 13:10:20,044 [root] INFO: Processing analysis data for Task #12
2024-04-19 13:12:29,587 [Task 12] [root] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 346, in run
    results = vol.run()
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 277, in run
    self.do_strings()
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 312, in do_strings
    _ = Path(f"{self.memfile}.strings").write_bytes(b"\n".join(strings))
MemoryError
2024-04-19 13:12:29,602 [Task 12] [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory": 'NoneType' object has no attribute 'delete_memdump_on_exception'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 346, in run
    results = vol.run()
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 277, in run
    self.do_strings()
  File "/opt/CAPEv2/utils/../modules/processing/memory.py", line 312, in do_strings
    _ = Path(f"{self.memfile}.strings").write_bytes(b"\n".join(strings))
MemoryError
```
## Context

Standard fresh setup... Reinstalled my CAPE instance from scratch!

| Question         | Answer
|------------------|--------------------
| Git commit       |` 4234f86d15077c7b8074fdcc09b08af4fdf9f932`
| OS version       | Ubuntu 22.04, Windows 7 guest

**Comment by doomedraven** [comment]
hey, `delete_memdump_on_exception` is strange i will get a look on botconf, but  about memory error according to google is that you don't have enough ram, how much FREE ram does your server has?

**Comment by xme** [comment]
Oh my god, I missed the "MemoryError"... It should not be a problem from a server memory point of view. Will check deeper. Going to Botconf?

**Comment by doomedraven** [comment]
Yep, all cape team and few core contributes coming, you will be around too
right?

**Comment by xme** [comment]
Flying to Nice today! See you there! Will be happy to have some beers with you!

**Comment by doomedraven** [comment]
Yep, see you soon, have a nice flight
