### ISSUE TITLE
rooter.py error

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#211]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

rooter.py is spawned from supervisor and listen to /tmp/cuckoo-rooter

# Current Behavior

rooter.py is running but can't be used. From cuckoo.log:

`2020-06-10 11:16:28,699 [lib.cuckoo.core.rooter] CRITICAL: Unable to passthrough root command as we're unable to connect to the rooter unix socket: [Errno 111] Connection refused.
`

# Failure Information (for bugs)

When rooter.py is launched:

```
Traceback (most recent call last):
  File "rooter.py", line 384, in <module>
    raise e
  File "rooter.py", line 380, in <module>
    command, addr = server.recvfrom(4096)
OSError: [Errno 9] Bad file descriptor
```

**Comment by doomedraven** [comment]
hey, how do you start rooter? first time see this

**Comment by xme** [comment]
I forgot to add:
```
# ll /tmp/cuckoo-rooter
srw--w---- 1 root cape 0 Jun 10 11:19 /tmp/cuckoo-rooter=
```

rooter.py is started from supervisor:

```
[program:rooter]
command=python3 rooter.py -g cape
directory=/opt/CAPEv2/utils
user=root
startsecs=10
priority = 100
autostart=true
autorestart=true
stopasgroup=true
stderr_logfile=/var/log/supervisor/router.err.log
stdout_logfile=/var/log/supervisor/router.out.log
```

**Comment by doomedraven** [comment]
can you stop that and start manually with adding `-v` and restart cape.service?

**Comment by xme** [comment]
Seems to be ok when started manually:
```
# python3 rooter.py -v -g cape
2020-06-10 11:41:19,032 [cuckoo-rooter] INFO: Processing command: nic_available ens160
2020-06-10 11:41:19,137 [cuckoo-rooter] INFO: Processing command: forward_enable virbr0 ens160 192.168.122.107
2020-06-10 11:41:19,137 [cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i virbr0 -j REJECT -m comment --comment CAPE-rooter
2020-06-10 11:41:19,509 [cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -o virbr0 -j REJECT -m comment --comment CAPE-rooter
2020-06-10 11:41:19,511 [cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I FORWARD -i virbr0 -o ens160 --source 192.168.122.107 -j ACCEPT -m comment --comment CAPE-rooter
2020-06-10 11:41:19,539 [cuckoo-rooter] DEBUG: Running command: /sbin/iptables -I FORWARD -i ens160 -o virbr0 --destination 192.168.122.107 -j ACCEPT -m comment --comment CAPE-rooter
2020-06-10 11:41:19,543 [cuckoo-rooter] INFO: Processing command: srcroute_enable main 192.168.122.107
2020-06-10 11:41:19,543 [cuckoo-rooter] DEBUG: Running command: /sbin/ip rule add from 192.168.122.107 table main
2020-06-10 11:41:19,559 [cuckoo-rooter] DEBUG: Running command: /sbin/ip route flush cache
2020-06-10 11:42:40,711 [cuckoo-rooter] INFO: Processing command: forward_disable virbr0 ens160 192.168.122.107
2020-06-10 11:42:40,712 [cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i virbr0 -o ens160 --source 192.168.122.107 -j ACCEPT -m comment --comment CAPE-rooter
2020-06-10 11:42:40,751 [cuckoo-rooter] DEBUG: Running command: /sbin/iptables -D FORWARD -i ens160 -o virbr0 --destination 192.168.122.107 -j ACCEPT -m comment --comment CAPE-rooter
2020-06-10 11:42:40,754 [cuckoo-rooter] INFO: Processing command: srcroute_disable main 192.168.122.107
2020-06-10 11:42:40,754 [cuckoo-rooter] DEBUG: Running command: /sbin/ip rule del from 192.168.122.107 table main
2020-06-10 11:42:40,811 [cuckoo-rooter] DEBUG: Running command: /sbin/ip route flush cache
```

**Comment by doomedraven** [comment]
then idk what is wrong i never saw this error, try again start from systemd and maybe error is gone?
