### ISSUE TITLE
tasks stuck in processing

### ISSUE THREAD

**Issue by joser12345678** [kevoreilly/CAPEv2#2114]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ x] I did read the README!
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I have read and checked all configs (with all optional parts)

# Expected Behavior

I am trying to setup cape on an ubuntu 22.04 server to submit some linux malware for analysis in my ubuntu 22.04 guest VM. I'm expecting the analysis to finish so I can review the reports.

# Current Behavior

The task is stuck in processing, and the process logs indicate an error. Thank you in advance for any and all help!

# Failure Information (for bugs)

Not sure if it is a bug, but according to the process-1.log file for task 1: 

```
2024-05-09 15:54:08,903 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "modify_desktop_wallpaper": 'summary'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 591, in run
    result = sig.on_complete()
  File "/opt/CAPEv2/utils/../modules/signatures/windows/modifies_wallpaper.py", line 46, in on_complete
    if self.check_write_key(pattern=indicator, regex=True):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/abstracts.py", line 1185, in check_write_key
    subject = self.results["behavior"]["summary"]["write_keys"]
KeyError: 'summary'
2024-05-09 15:54:08,907 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "banker_zeus_p2p": 'summary'
2024-05-09 15:54:08,908 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "bot_athenahttp": 'summary'
2024-05-09 15:54:08,913 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "family_proxyback": 'summary'
2024-05-09 15:54:08,931 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_parallels_keys": 'summary'
2024-05-09 15:54:08,932 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "bypass_firewall": 'summary'
2024-05-09 15:54:08,932 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "disables_winfirewall": 'summary'
2024-05-09 15:54:08,933 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "parallax_mutexes": 'summary'
2024-05-09 15:54:08,933 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "allaple_mutexes": 'summary'
```
## Steps to Reproduce

1. install and run cuckoo.py: `poetry run python3 cuckoo.py -d`
2. submit a linux malware for analysis with the default options in the web UI
3. wait for analysis to finish and it is stuck in processing

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | 9d49d6175d0a9df4fefa3d862755817febd47c33
| OS version       | Ubuntu 22.04

## Failure Logs

For completeness, here is the output of running cuckoo.py in debug mode:

```
2024-05-09 15:45:40,463 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2024-05-09 15:45:40,477 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks
2024-05-09 15:46:18,894 [lib.cuckoo.core.scheduler] DEBUG: Task #1: Processing task
2024-05-09 15:46:18,989 [lib.cuckoo.core.scheduler] INFO: Task #1: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_buj7v__v/f69de7425721056d577b152a'
2024-05-09 15:46:19,096 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine test_joseph (label=test_joseph, arch=x64, platform=linux)
2024-05-09 15:46:19,158 [lib.cuckoo.common.abstracts] DEBUG: Starting machine test_joseph
2024-05-09 15:46:19,160 [lib.cuckoo.common.abstracts] DEBUG: Getting status for test_joseph
2024-05-09 15:46:19,248 [lib.cuckoo.common.abstracts] DEBUG: Using snapshot base_install for virtual machine test_joseph
2024-05-09 15:46:38,612 [lib.cuckoo.common.abstracts] DEBUG: Getting status for test_joseph
2024-05-09 15:46:38,742 [lib.cuckoo.common.integrations.parse_pe] ERROR: PE type not recognised: 'DOS Header magic not found.'
2024-05-09 15:46:38,753 [lib.cuckoo.core.resultserver] DEBUG: Task #1: The associated machine IP is 192.168.122.154
2024-05-09 15:46:38,806 [lib.cuckoo.core.scheduler] INFO: Enabled route 'none'.
2024-05-09 15:46:38,810 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2024-05-09 15:46:38,876 [lib.cuckoo.core.guest] INFO: Task #1: Starting analysis on guest (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:46:38,921 [lib.cuckoo.core.guest] INFO: Task #1: Guest is running CAPE Agent 0.17 (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:46:39,058 [lib.cuckoo.core.guest] DEBUG: Task #1: Uploading analyzer to guest (id=test_joseph, ip=192.168.122.154, size=265422)
2024-05-09 15:46:39,220 [lib.cuckoo.core.guest] INFO: Task #1: Uploading script files to guest (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:46:39,744 [lib.cuckoo.core.resultserver] DEBUG: Task #1: live log analysis.log initialized
2024-05-09 15:46:44,510 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:46:49,634 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:46:54,783 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:46:59,899 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:05,292 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:10,503 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:15,682 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:20,812 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:25,992 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:31,146 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:36,266 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:41,429 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:46,601 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:51,713 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:47:56,835 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:01,952 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:07,065 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:12,179 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:17,322 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:22,465 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:27,607 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:32,751 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:37,889 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:42,997 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:48,111 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:53,222 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:48:58,327 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:03,436 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:08,586 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:13,762 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:18,924 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:24,089 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:29,263 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:34,444 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:39,610 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:44,778 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:49,916 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:49:55,076 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:50:00,248 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:50:02,982 [lib.cuckoo.core.resultserver] DEBUG: Task #1: Trying to upload file logs/strace.log.1080
2024-05-09 15:50:02,992 [lib.cuckoo.core.resultserver] DEBUG: Task #1: Trying to upload file logs/strace.log.1083
2024-05-09 15:50:03,000 [lib.cuckoo.core.resultserver] DEBUG: Task #1: Trying to upload file logs/strace.log.1081
2024-05-09 15:50:03,007 [lib.cuckoo.core.resultserver] DEBUG: Task #1: Trying to upload file logs/strace.log.1082
2024-05-09 15:50:05,430 [lib.cuckoo.core.guest] DEBUG: Task #1: Analysis is still running (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:50:08,525 [lib.cuckoo.core.guest] INFO: Task #completed successfully: Analysis 1 (id=test_joseph, ip=192.168.122.154)
2024-05-09 15:50:08,599 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2024-05-09 15:50:08,602 [lib.cuckoo.common.abstracts] DEBUG: Stopping machine test_joseph
2024-05-09 15:50:08,603 [lib.cuckoo.common.abstracts] DEBUG: Getting status for test_joseph
2024-05-09 15:50:11,034 [lib.cuckoo.common.abstracts] DEBUG: Getting status for test_joseph
2024-05-09 15:50:11,117 [lib.cuckoo.core.resultserver] DEBUG: Task #1: Stopped tracking machine 192.168.122.154
2024-05-09 15:50:11,421 [lib.cuckoo.core.scheduler] DEBUG: Task #1: Released database task with status True
2024-05-09 15:50:11,425 [lib.cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed
```

**Comment by doomedraven** [comment]
you marked that you checked issues, here is it, https://github.com/kevoreilly/CAPEv2/issues/2103 closing as duplicated.

About summary missed you must have some error before or disabled some config options
