### ISSUE TITLE
[Errno 13] Permission denied: 'C:\\tmpnnvioog4\\dll\\536.ini'

### ISSUE THREAD

**Issue by HAB18** [kevoreilly/CAPEv2#2133]
Hi CAPEv2 team, i really need some support here

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

I just finished setup my capev2 sandbox following the document, i tried submit some samples but all return error in analyze with the same Warning above. I'm using virtualbox guest machine with win 10 Pro OS. Bellow is a part of log file i get in the guest machine, from where i think having problem. 

## Failure Logs

```
2024-05-20 01:55:33,747 [root] DEBUG: Initialized auxiliary module "Sysmon"
2024-05-20 01:55:33,747 [root] DEBUG: Trying to start auxiliary module "Sysmon"...
2024-05-20 01:55:33,747 [root] WARNING: Cannot execute auxiliary module Sysmon: In order to use the Sysmon functionality, it is required to have the SMaster(64|32).exe file and sysmonconfig-export.xml file in the bin path. Note that the SMaster(64|32).exe files are just the standard Sysmon binaries renamed to avoid anti-analysis detection techniques.
2024-05-20 01:55:33,747 [root] DEBUG: Initialized auxiliary module "TLSDumpMasterSecrets"
2024-05-20 01:55:33,747 [root] DEBUG: Trying to start auxiliary module "TLSDumpMasterSecrets"...
2024-05-20 01:55:33,747 [modules.auxiliary.tlsdump] INFO: lsass.exe found, pid 536
2024-05-20 01:55:33,747 [lib.api.process] INFO: Monitor config for <Process 536 lsass.exe>: C:\tmpnnvioog4\dll\536.ini
2024-05-20 01:55:33,747 [root] WARNING: Cannot execute auxiliary module TLSDumpMasterSecrets: [Errno 13] Permission denied: 'C:\\tmpnnvioog4\\dll\\536.ini'
2024-05-20 01:55:33,928 [root] DEBUG: Initialized auxiliary module "Usage"
2024-05-20 01:55:33,942 [root] DEBUG: Trying to start auxiliary module "Usage"...
2024-05-20 01:55:33,951 [root] DEBUG: Started auxiliary module Usage
2024-05-20 01:55:33,951 [root] DEBUG: Initialized auxiliary module "During_script"
2024-05-20 01:55:33,951 [root] DEBUG: Trying to start auxiliary module "During_script"...
2024-05-20 01:55:33,996 [root] DEBUG: Started auxiliary module During_script
2024-05-19 18:55:28,831 [root] INFO: Restarting WMI Service
2024-05-19 18:55:28,831 [root] DEBUG: package modules.packages.exe does not support configure, ignoring
2024-05-19 18:55:28,831 [root] WARNING: configuration error for package modules.packages.exe: error importing data.packages.exe: No module named 'data.packages'
2024-05-19 18:55:29,161 [lib.core.compound] INFO: C:\Users\user\AppData\Local\Temp already exists, skipping creation
2024-05-19 18:55:29,161 [lib.api.process] INFO: Successfully executed process from path "C:\Users\user\AppData\Local\Temp\ExplorerSuite.exe" with arguments "" with pid 5188
2024-05-19 18:55:29,161 [lib.api.process] INFO: Monitor config for <Process 5188 ExplorerSuite.exe>: C:\tmpnnvioog4\dll\5188.ini
2024-05-19 18:55:29,161 [root] INFO: You probably submitted the job with wrong package
Traceback (most recent call last):
  File "C:\tmpnnvioog4\analyzer.py", line 583, in run
    pids = self.package.start(self.target)
  File "C:\tmpnnvioog4\modules\packages\exe.py", line 37, in start
    return self.execute(path, args, path)
  File "C:\tmpnnvioog4\lib\common\abstracts.py", line 176, in execute
    p.inject(interest)
  File "C:\tmpnnvioog4\lib\api\process.py", line 652, in inject
    self.write_monitor_config(interest, nosleepskip)
  File "C:\tmpnnvioog4\lib\api\process.py", line 571, in write_monitor_config
    with open(config_path, "w", encoding="utf-8") as config:
PermissionError: [Errno 13] Permission denied: 'C:\\tmpnnvioog4\\dll\\5188.ini'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tmpnnvioog4\analyzer.py", line 1464, in <module>
    success = analyzer.run()
  File "C:\tmpnnvioog4\analyzer.py", line 589, in run
    raise CuckooError(f'The package "{package_name}" start function encountered an unhandled exception: {e}') from e
lib.common.exceptions.CuckooError: The package "modules.packages.exe" start function encountered an unhandled exception: [Errno 13] Permission denied: 'C:\\tmpnnvioog4\\dll\\5188.ini'
2024-05-19 18:55:29,161 [root] WARNING: Folder at path "C:\JAOcmlBTV\debugger" does not exist, skipping
2024-05-19 18:55:29,161 [root] WARNING: Folder at path "C:\JAOcmlBTV\tlsdump" does not exist, skipping
2024-05-19 18:55:29,161 [root] INFO: Analysis completed

```

**Comment by kevoreilly** [comment]
My first guess would be the agent is not running with elevated/admin privs. Try ensuring this is the case.

**Comment by HAB18** [comment]
I thought so, too, i ran again with admin right and replace snapshot but error still happen.

**Comment by HAB18** [comment]
I read the Error 13, it's something related to missmatch file type when using open function. Hope this help

**Comment by doomedraven** [comment]
what version of python?

**Comment by HAB18** [comment]
I'm using 3.8.10 for host and 3.9.5 for guest
![image](https://github.com/kevoreilly/CAPEv2/assets/47893240/e48803b9-edb1-440b-991b-750a04bbc748)

**Comment by kevoreilly** [comment]
32 or 64 bit?

**Comment by HAB18** [comment]
Guest is 64-bit

**Comment by kevoreilly** [comment]
Uh oh there it is. Read the docs

**Comment by HAB18** [comment]
Can you point out where i'm wrong? I read the docs very careful. I don't see anything say about it, it suggest guest windows 10 64-bit as well

**Comment by doomedraven** [comment]
readme in bold
![image](https://github.com/kevoreilly/CAPEv2/assets/1856495/b0547abb-8ad0-4cd3-8a5c-fa00dbc82417)

**Comment by HAB18** [comment]
oh, you mean python, i using 32-bit of course

**Comment by HAB18** [comment]
![image](https://github.com/kevoreilly/CAPEv2/assets/47893240/9c8bc736-f875-44e6-a6f3-460b914ad7b2)

**Comment by doomedraven** [comment]
can you post from that curl command ?
https://capev2.readthedocs.io/en/latest/installation/guest/agent.html#installing-the-agent

**Comment by HAB18** [comment]
![image](https://github.com/kevoreilly/CAPEv2/assets/47893240/a64d9f1f-ba82-4aa9-878e-fa575e16df56)
sure, here

**Comment by doomedraven** [comment]
upgrade your agent to latest 0.17 and post the output of the same command

**Comment by HAB18** [comment]
oh, sure, wait me a sec, sorry to forgot update the agent in guest to newest

**Comment by HAB18** [comment]
![image](https://github.com/kevoreilly/CAPEv2/assets/47893240/d7961c14-a69d-46b0-b39b-8090ba1d3ee1)
here it is

**Comment by HAB18** [comment]
i will try updating everything and run one again, if still error, i will let you guys know

**Comment by doomedraven** [comment]
btw https://github.com/kevoreilly/CAPEv2/issues/1376

**Comment by nbargnesi** [comment]
If you're running the latest version, there's a lot of useful logs that get dumped out before Sysmon gets initialized. That includes a call to log the results of [IsUserAnAdmin](https://github.com/kevoreilly/CAPEv2/blob/477033b4b66d6f3ce978c7d708f87cf956576032/analyzer/windows/analyzer.py#L418). Those logs are real helpful debugging permission problems.

Something else to look for when you updating everything and run again.

**Comment by doomedraven** [comment]
closing as abondoned
