### ISSUE TITLE
Compression method not supported

### ISSUE THREAD

**Issue by bartblaze** [kevoreilly/CAPEv2#216]
# Failure Information (for bugs)
Creating a ZIP with Encryption Method set as AES-256 does not execute/extract (with ZIP package chosen in Submission).

> That compression method is not supported

## Steps to Reproduce

1. ZIP a file with AES-256 as encryption method
2. Upload to CAPE, select ZIP package

## Failure Logs

```
2020-05-13 09:07:47,930 [root] INFO: Date set to: 20200623T09:19:04, timeout set to: 300
2020-06-23 09:19:04,031 [root] DEBUG: Starting analyzer from: C:\tmpnwhtwc92
2020-06-23 09:19:04,031 [root] DEBUG: Storing results at: C:\tGHpaeMoH
2020-06-23 09:19:04,031 [root] DEBUG: Pipe server name: \\.\PIPE\SdeVIcjF
2020-06-23 09:19:04,031 [root] DEBUG: Python path: C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32
2020-06-23 09:19:04,031 [root] INFO: Analysis package "zip" has been specified.
2020-06-23 09:19:04,031 [root] DEBUG: Trying to import analysis package "zip"...
2020-06-23 09:19:04,046 [root] DEBUG: Imported analysis package "zip".
2020-06-23 09:19:04,046 [root] DEBUG: Trying to initialize analysis package "zip"...
2020-06-23 09:19:04,046 [root] DEBUG: Initialized analysis package "zip".
2020-06-23 09:19:04,093 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.browser"...
2020-06-23 09:19:04,109 [root] DEBUG: Imported auxiliary module "modules.auxiliary.browser".
2020-06-23 09:19:04,109 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.curtain"...
2020-06-23 09:19:04,187 [root] DEBUG: Imported auxiliary module "modules.auxiliary.curtain".
2020-06-23 09:19:04,187 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.digisig"...
2020-06-23 09:19:04,203 [root] DEBUG: Imported auxiliary module "modules.auxiliary.digisig".
2020-06-23 09:19:04,203 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.disguise"...
2020-06-23 09:19:04,218 [root] DEBUG: Imported auxiliary module "modules.auxiliary.disguise".
2020-06-23 09:19:04,218 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.human"...
2020-06-23 09:19:04,234 [root] DEBUG: Imported auxiliary module "modules.auxiliary.human".
2020-06-23 09:19:04,234 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.procmon"...
2020-06-23 09:19:04,234 [root] DEBUG: Imported auxiliary module "modules.auxiliary.procmon".
2020-06-23 09:19:04,234 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.screenshots"...
2020-06-23 09:19:04,312 [modules.auxiliary.screenshots] DEBUG: Importing 'time'
2020-06-23 09:19:04,312 [modules.auxiliary.screenshots] DEBUG: Importing 'StringIO'
2020-06-23 09:19:04,312 [modules.auxiliary.screenshots] DEBUG: Importing 'Thread'
2020-06-23 09:19:04,328 [modules.auxiliary.screenshots] DEBUG: Importing 'Auxiliary'
2020-06-23 09:19:04,328 [modules.auxiliary.screenshots] DEBUG: Importing 'NetlogFile'
2020-06-23 09:19:04,328 [modules.auxiliary.screenshots] DEBUG: Importing 'Screenshot'
2020-06-23 09:19:04,328 [lib.api.screenshot] DEBUG: Importing 'math'
2020-06-23 09:19:04,328 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2020-06-23 09:19:05,687 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageGrab'
2020-06-23 09:19:05,734 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2020-06-23 09:19:05,796 [modules.auxiliary.screenshots] DEBUG: Imports OK
2020-06-23 09:19:05,812 [root] DEBUG: Imported auxiliary module "modules.auxiliary.screenshots".
2020-06-23 09:19:05,812 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.sysmon"...
2020-06-23 09:19:05,937 [root] DEBUG: Imported auxiliary module "modules.auxiliary.sysmon".
2020-06-23 09:19:05,937 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.usage"...
2020-06-23 09:19:06,109 [root] DEBUG: Imported auxiliary module "modules.auxiliary.usage".
2020-06-23 09:19:06,125 [root] DEBUG: Trying to initialize auxiliary module "Browser"...
2020-06-23 09:19:06,125 [root] DEBUG: Initialized auxiliary module "Browser".
2020-06-23 09:19:06,125 [root] DEBUG: Trying to start auxiliary module "Browser"...
2020-06-23 09:19:06,140 [root] DEBUG: Started auxiliary module Browser
2020-06-23 09:19:06,140 [root] DEBUG: Trying to initialize auxiliary module "Curtain"...
2020-06-23 09:19:06,171 [root] DEBUG: Initialized auxiliary module "Curtain".
2020-06-23 09:19:06,171 [root] DEBUG: Trying to start auxiliary module "Curtain"...
2020-06-23 09:19:06,187 [root] DEBUG: Started auxiliary module Curtain
2020-06-23 09:19:06,187 [root] DEBUG: Trying to initialize auxiliary module "DigiSig"...
2020-06-23 09:19:06,187 [root] DEBUG: Initialized auxiliary module "DigiSig".
2020-06-23 09:19:06,187 [root] DEBUG: Trying to start auxiliary module "DigiSig"...
2020-06-23 09:19:06,203 [modules.auxiliary.digisig] DEBUG: Checking for a digital signature.
2020-06-23 09:19:11,312 [modules.auxiliary.digisig] DEBUG: File format not recognized.
2020-06-23 09:19:11,312 [modules.auxiliary.digisig] INFO: Uploading signature results to aux/DigiSig.json
2020-06-23 09:19:11,328 [root] DEBUG: Started auxiliary module DigiSig
2020-06-23 09:19:11,328 [root] DEBUG: Trying to initialize auxiliary module "Disguise"...
2020-06-23 09:19:11,328 [root] DEBUG: Initialized auxiliary module "Disguise".
2020-06-23 09:19:11,328 [root] DEBUG: Trying to start auxiliary module "Disguise"...
2020-06-23 09:19:11,343 [root] DEBUG: Started auxiliary module Disguise
2020-06-23 09:19:11,343 [root] DEBUG: Trying to initialize auxiliary module "Human"...
2020-06-23 09:19:11,343 [root] DEBUG: Initialized auxiliary module "Human".
2020-06-23 09:19:11,343 [root] DEBUG: Trying to start auxiliary module "Human"...
2020-06-23 09:19:11,343 [root] DEBUG: Started auxiliary module Human
2020-06-23 09:19:11,343 [root] DEBUG: Trying to initialize auxiliary module "Procmon"...
2020-06-23 09:19:11,359 [root] DEBUG: Initialized auxiliary module "Procmon".
2020-06-23 09:19:11,359 [root] DEBUG: Trying to start auxiliary module "Procmon"...
2020-06-23 09:19:11,359 [root] DEBUG: Started auxiliary module Procmon
2020-06-23 09:19:11,359 [root] DEBUG: Trying to initialize auxiliary module "Screenshots"...
2020-06-23 09:19:11,359 [root] DEBUG: Initialized auxiliary module "Screenshots".
2020-06-23 09:19:11,359 [root] DEBUG: Trying to start auxiliary module "Screenshots"...
2020-06-23 09:19:11,359 [root] DEBUG: Started auxiliary module Screenshots
2020-06-23 09:19:11,359 [root] DEBUG: Trying to initialize auxiliary module "Sysmon"...
2020-06-23 09:19:11,359 [root] DEBUG: Initialized auxiliary module "Sysmon".
2020-06-23 09:19:11,359 [root] DEBUG: Trying to start auxiliary module "Sysmon"...
2020-06-23 09:19:11,359 [root] DEBUG: Started auxiliary module Sysmon
2020-06-23 09:19:11,359 [root] DEBUG: Trying to initialize auxiliary module "Usage"...
2020-06-23 09:19:11,359 [root] DEBUG: Initialized auxiliary module "Usage".
2020-06-23 09:19:11,359 [root] DEBUG: Trying to start auxiliary module "Usage"...
2020-06-23 09:19:11,375 [root] DEBUG: Started auxiliary module Usage
2020-06-23 09:19:11,375 [root] INFO: Analyzer: Package modules.packages.zip does not specify a DLL option
2020-06-23 09:19:11,375 [root] INFO: Analyzer: Package modules.packages.zip does not specify a DLL_64 option
2020-06-23 09:19:11,375 [root] INFO: Analyzer: Package modules.packages.zip does not specify a loader option
2020-06-23 09:19:11,375 [root] INFO: Analyzer: Package modules.packages.zip does not specify a loader_64 option
2020-06-23 09:19:11,406 [root] ERROR: Traceback (most recent call last):
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 64, in extract_zip
    archive.extractall(path=extract_path, pwd=password)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1700, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1571, in open
    return ZipExtFile(zef_file, mode, zinfo, pwd, True)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 819, in __init__
    self._decompressor = _get_decompressor(self._compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 720, in _get_decompressor
    _check_compression(compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 700, in _check_compression
    raise NotImplementedError("That compression method is not supported")
NotImplementedError: That compression method is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 69, in extract_zip
    archive.extractall(path=extract_path, pwd=password)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1700, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1571, in open
    return ZipExtFile(zef_file, mode, zinfo, pwd, True)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 819, in __init__
    self._decompressor = _get_decompressor(self._compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 720, in _get_decompressor
    _check_compression(compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 700, in _check_compression
    raise NotImplementedError("That compression method is not supported")
NotImplementedError: That compression method is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpnwhtwc92/analyzer.py", line 509, in run
    pids = self.package.start(self.target)
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 119, in start
    self.extract_zip(path, root, password, 0)
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 71, in extract_zip
    raise CuckooPackageError("Unable to extract Zip file: "
lib.common.exceptions.CuckooPackageError: Unable to extract Zip file: That compression method is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpnwhtwc92/analyzer.py", line 1469, in <module>
    success = analyzer.run()
  File "C:/tmpnwhtwc92/analyzer.py", line 514, in run
    raise CuckooError("The package \"{0}\" start function raised an "
lib.common.exceptions.CuckooError: The package "modules.packages.zip" start function raised an error: Unable to extract Zip file: That compression method is not supported
Traceback (most recent call last):
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 64, in extract_zip
    archive.extractall(path=extract_path, pwd=password)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1700, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1571, in open
    return ZipExtFile(zef_file, mode, zinfo, pwd, True)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 819, in __init__
    self._decompressor = _get_decompressor(self._compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 720, in _get_decompressor
    _check_compression(compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 700, in _check_compression
    raise NotImplementedError("That compression method is not supported")
NotImplementedError: That compression method is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 69, in extract_zip
    archive.extractall(path=extract_path, pwd=password)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1700, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1571, in open
    return ZipExtFile(zef_file, mode, zinfo, pwd, True)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 819, in __init__
    self._decompressor = _get_decompressor(self._compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 720, in _get_decompressor
    _check_compression(compress_type)
  File "C:\Users\Rebecca\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 700, in _check_compression
    raise NotImplementedError("That compression method is not supported")
NotImplementedError: That compression method is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpnwhtwc92/analyzer.py", line 509, in run
    pids = self.package.start(self.target)
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 119, in start
    self.extract_zip(path, root, password, 0)
  File "C:\tmpnwhtwc92\modules\packages\zip.py", line 71, in extract_zip
    raise CuckooPackageError("Unable to extract Zip file: "
lib.common.exceptions.CuckooPackageError: Unable to extract Zip file: That compression method is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpnwhtwc92/analyzer.py", line 1469, in <module>
    success = analyzer.run()
  File "C:/tmpnwhtwc92/analyzer.py", line 514, in run
    raise CuckooError("The package \"{0}\" start function raised an "
lib.common.exceptions.CuckooError: The package "modules.packages.zip" start function raised an error: Unable to extract Zip file: That compression method is not supported
2020-06-23 09:19:11,406 [root] WARNING: Folder at path "C:\tGHpaeMoH\debugger" does not exist, skip.
2020-06-23 09:19:11,406 [root] INFO: Analysis completed.
```

Failing analysis result (AES-256): https://capesandbox.com/analysis/12936/
Succesful analysis result (ZipCrypto): https://capesandbox.com/analysis/12937/

**Comment by doomedraven** [comment]
that is your vm problem, zipfile doesn't support that by default, so that should be handled before, or installed extended version of zipfile and rewrite zip package handling, but that would be better on sflock than send it to vm

**Comment by doomedraven** [comment]
sflock update to handle this

**Comment by bartblaze** [comment]
For my own reference: 
`pip3 install -U git+https://github.com/doomedraven/sflock`
