### ISSUE TITLE
Error: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by bartblaze** [kevoreilly/CAPEv2#217]
# Failure Information (for bugs)

Uploading a ZIP with an Office file inside, does not run the Office file. You get:

> 2020-06-23 19:57:42,625 [lib.api.process] ERROR: Failed to execute process from path "C:\Users\Louise\AppData\Local\Temp\Financial Sample.xlsx" with arguments "None" (Error: %1 is not a valid Win32 application (ERROR_BAD_EXE_FORMAT))

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create ZIP with Office file (xlsx, docx, ..) inside
2. Upload (choose ZIP package or generic)

## Failure Logs

```
2020-05-13 09:29:27,121 [root] INFO: Date set to: 20200623T19:57:38, timeout set to: 300
2020-06-23 19:57:38,078 [root] DEBUG: Starting analyzer from: C:\tmp558c2t_g
2020-06-23 19:57:38,078 [root] DEBUG: Storing results at: C:\qJYKXSaSG
2020-06-23 19:57:38,078 [root] DEBUG: Pipe server name: \\.\PIPE\PbFahOUA
2020-06-23 19:57:38,078 [root] DEBUG: Python path: C:\Users\Louise\AppData\Local\Programs\Python\Python38-32
2020-06-23 19:57:38,078 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2020-06-23 19:57:38,093 [root] INFO: Automatically selected analysis package "zip"
2020-06-23 19:57:38,093 [root] DEBUG: Trying to import analysis package "zip"...
2020-06-23 19:57:38,156 [root] DEBUG: Imported analysis package "zip".
2020-06-23 19:57:38,156 [root] DEBUG: Trying to initialize analysis package "zip"...
2020-06-23 19:57:38,156 [root] DEBUG: Initialized analysis package "zip".
2020-06-23 19:57:38,281 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.browser"...
2020-06-23 19:57:38,296 [root] DEBUG: Imported auxiliary module "modules.auxiliary.browser".
2020-06-23 19:57:38,296 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.curtain"...
2020-06-23 19:57:38,312 [root] DEBUG: Imported auxiliary module "modules.auxiliary.curtain".
2020-06-23 19:57:38,312 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.digisig"...
2020-06-23 19:57:38,343 [root] DEBUG: Imported auxiliary module "modules.auxiliary.digisig".
2020-06-23 19:57:38,343 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.disguise"...
2020-06-23 19:57:38,390 [root] DEBUG: Imported auxiliary module "modules.auxiliary.disguise".
2020-06-23 19:57:38,390 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.human"...
2020-06-23 19:57:38,437 [root] DEBUG: Imported auxiliary module "modules.auxiliary.human".
2020-06-23 19:57:38,437 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.procmon"...
2020-06-23 19:57:38,453 [root] DEBUG: Imported auxiliary module "modules.auxiliary.procmon".
2020-06-23 19:57:38,453 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.screenshots"...
2020-06-23 19:57:38,453 [modules.auxiliary.screenshots] DEBUG: Importing 'time'
2020-06-23 19:57:38,453 [modules.auxiliary.screenshots] DEBUG: Importing 'StringIO'
2020-06-23 19:57:38,453 [modules.auxiliary.screenshots] DEBUG: Importing 'Thread'
2020-06-23 19:57:38,453 [modules.auxiliary.screenshots] DEBUG: Importing 'Auxiliary'
2020-06-23 19:57:38,453 [modules.auxiliary.screenshots] DEBUG: Importing 'NetlogFile'
2020-06-23 19:57:38,453 [modules.auxiliary.screenshots] DEBUG: Importing 'Screenshot'
2020-06-23 19:57:38,468 [lib.api.screenshot] DEBUG: Importing 'math'
2020-06-23 19:57:38,468 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2020-06-23 19:57:41,171 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageGrab'
2020-06-23 19:57:41,203 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2020-06-23 19:57:41,218 [modules.auxiliary.screenshots] DEBUG: Imports OK
2020-06-23 19:57:41,218 [root] DEBUG: Imported auxiliary module "modules.auxiliary.screenshots".
2020-06-23 19:57:41,218 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.sysmon"...
2020-06-23 19:57:41,265 [root] DEBUG: Imported auxiliary module "modules.auxiliary.sysmon".
2020-06-23 19:57:41,265 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.usage"...
2020-06-23 19:57:41,281 [root] DEBUG: Imported auxiliary module "modules.auxiliary.usage".
2020-06-23 19:57:41,281 [root] DEBUG: Trying to initialize auxiliary module "Browser"...
2020-06-23 19:57:41,296 [root] DEBUG: Initialized auxiliary module "Browser".
2020-06-23 19:57:41,296 [root] DEBUG: Trying to start auxiliary module "Browser"...
2020-06-23 19:57:41,312 [root] DEBUG: Started auxiliary module Browser
2020-06-23 19:57:41,312 [root] DEBUG: Trying to initialize auxiliary module "Curtain"...
2020-06-23 19:57:41,312 [root] DEBUG: Initialized auxiliary module "Curtain".
2020-06-23 19:57:41,328 [root] DEBUG: Trying to start auxiliary module "Curtain"...
2020-06-23 19:57:41,328 [root] DEBUG: Started auxiliary module Curtain
2020-06-23 19:57:41,328 [root] DEBUG: Trying to initialize auxiliary module "DigiSig"...
2020-06-23 19:57:41,328 [root] DEBUG: Initialized auxiliary module "DigiSig".
2020-06-23 19:57:41,328 [root] DEBUG: Trying to start auxiliary module "DigiSig"...
2020-06-23 19:57:41,328 [modules.auxiliary.digisig] DEBUG: Checking for a digital signature.
2020-06-23 19:57:42,453 [modules.auxiliary.digisig] DEBUG: File format not recognized.
2020-06-23 19:57:42,453 [modules.auxiliary.digisig] INFO: Uploading signature results to aux/DigiSig.json
2020-06-23 19:57:42,468 [root] DEBUG: Started auxiliary module DigiSig
2020-06-23 19:57:42,468 [root] DEBUG: Trying to initialize auxiliary module "Disguise"...
2020-06-23 19:57:42,468 [root] DEBUG: Initialized auxiliary module "Disguise".
2020-06-23 19:57:42,468 [root] DEBUG: Trying to start auxiliary module "Disguise"...
2020-06-23 19:57:42,484 [root] DEBUG: Started auxiliary module Disguise
2020-06-23 19:57:42,484 [root] DEBUG: Trying to initialize auxiliary module "Human"...
2020-06-23 19:57:42,484 [root] DEBUG: Initialized auxiliary module "Human".
2020-06-23 19:57:42,484 [root] DEBUG: Trying to start auxiliary module "Human"...
2020-06-23 19:57:42,500 [root] DEBUG: Started auxiliary module Human
2020-06-23 19:57:42,500 [root] DEBUG: Trying to initialize auxiliary module "Procmon"...
2020-06-23 19:57:42,500 [root] DEBUG: Initialized auxiliary module "Procmon".
2020-06-23 19:57:42,500 [root] DEBUG: Trying to start auxiliary module "Procmon"...
2020-06-23 19:57:42,500 [root] DEBUG: Started auxiliary module Procmon
2020-06-23 19:57:42,515 [root] DEBUG: Trying to initialize auxiliary module "Screenshots"...
2020-06-23 19:57:42,515 [root] DEBUG: Initialized auxiliary module "Screenshots".
2020-06-23 19:57:42,515 [root] DEBUG: Trying to start auxiliary module "Screenshots"...
2020-06-23 19:57:42,515 [root] DEBUG: Started auxiliary module Screenshots
2020-06-23 19:57:42,515 [root] DEBUG: Trying to initialize auxiliary module "Sysmon"...
2020-06-23 19:57:42,515 [root] DEBUG: Initialized auxiliary module "Sysmon".
2020-06-23 19:57:42,515 [root] DEBUG: Trying to start auxiliary module "Sysmon"...
2020-06-23 19:57:42,515 [root] DEBUG: Started auxiliary module Sysmon
2020-06-23 19:57:42,515 [root] DEBUG: Trying to initialize auxiliary module "Usage"...
2020-06-23 19:57:42,515 [root] DEBUG: Initialized auxiliary module "Usage".
2020-06-23 19:57:42,515 [root] DEBUG: Trying to start auxiliary module "Usage"...
2020-06-23 19:57:42,515 [root] DEBUG: Started auxiliary module Usage
2020-06-23 19:57:42,515 [root] INFO: Analyzer: Package modules.packages.zip does not specify a DLL option
2020-06-23 19:57:42,531 [root] INFO: Analyzer: Package modules.packages.zip does not specify a DLL_64 option
2020-06-23 19:57:42,531 [root] INFO: Analyzer: Package modules.packages.zip does not specify a loader option
2020-06-23 19:57:42,531 [root] INFO: Analyzer: Package modules.packages.zip does not specify a loader_64 option
2020-06-23 19:57:42,562 [modules.packages.zip] DEBUG: Missing file option, auto executing: Financial Sample.xlsx
2020-06-23 19:57:42,562 [modules.packages.zip] DEBUG: file_name: "Financial Sample.xlsx"
2020-06-23 19:57:42,625 [lib.api.process] ERROR: Failed to execute process from path "C:\Users\Louise\AppData\Local\Temp\Financial Sample.xlsx" with arguments "None" (Error: %1 is not a valid Win32 application (ERROR_BAD_EXE_FORMAT))
2020-06-23 19:57:42,625 [root] ERROR: Traceback (most recent call last):
  File "C:/tmp558c2t_g/analyzer.py", line 509, in run
    pids = self.package.start(self.target)
  File "C:\tmp558c2t_g\modules\packages\zip.py", line 169, in start
    return self.execute(file_path, self.options.get("arguments"), file_path)
  File "C:\tmp558c2t_g\lib\common\abstracts.py", line 127, in execute
    raise CuckooPackageError("Unable to execute the initial process, "
lib.common.exceptions.CuckooPackageError: Unable to execute the initial process, analysis aborted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmp558c2t_g/analyzer.py", line 1469, in <module>
    success = analyzer.run()
  File "C:/tmp558c2t_g/analyzer.py", line 514, in run
    raise CuckooError("The package \"{0}\" start function raised an "
lib.common.exceptions.CuckooError: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:/tmp558c2t_g/analyzer.py", line 509, in run
    pids = self.package.start(self.target)
  File "C:\tmp558c2t_g\modules\packages\zip.py", line 169, in start
    return self.execute(file_path, self.options.get("arguments"), file_path)
  File "C:\tmp558c2t_g\lib\common\abstracts.py", line 127, in execute
    raise CuckooPackageError("Unable to execute the initial process, "
lib.common.exceptions.CuckooPackageError: Unable to execute the initial process, analysis aborted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmp558c2t_g/analyzer.py", line 1469, in <module>
    success = analyzer.run()
  File "C:/tmp558c2t_g/analyzer.py", line 514, in run
    raise CuckooError("The package \"{0}\" start function raised an "
lib.common.exceptions.CuckooError: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted.
2020-06-23 19:57:42,625 [root] WARNING: Folder at path "C:\qJYKXSaSG\debugger" does not exist, skip.
2020-06-23 19:57:42,625 [root] INFO: Analysis completed.
```

Example analysis (XLSX): https://capesandbox.com/analysis/13267/

DOC and DOCX: https://capesandbox.com/submit/status/13271/ & https://capesandbox.com/submit/status/13272/

**Comment by doomedraven** [comment]
again that is "fake" issue :P , zip file doesn't know how to run other files that are not exe, so zip package problem, dont use it and be happy :)
