### ISSUE TITLE
FLOSS integration fails: ERROR: 'PosixPath' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2172]
```
2024-06-17 10:49:55,971 [Task 81] [lib.cuckoo.common.integrations.floss] ERROR: 'PosixPath' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/common/integrations/floss.py", line 71, in run
    vw = fm.load_vw(Path(self.file_path), fileformat, sigspath, False)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/floss/main.py", line 372, in load_vw
    vw = viv_utils.getWorkspace(sample_path, analyze=False, should_save=False)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/viv_utils/__init__.py", line 102, in getWorkspace
    if fp.endswith(".viv"):
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

**Comment by doomedraven** [comment]
i think you have to open issue to them floss repo instead of cape

https://github.com/mandiant/flare-floss/blob/master/floss/main.py#L394-L399

**Comment by doomedraven** [comment]
btw your error code lines doest match floss code lines, i guess you must upgrade to latest versioj
