### ISSUE TITLE
ERROR: Failed to run the reporting module "MongoDB"

### ISSUE THREAD

**Issue by albertososa-es** [kevoreilly/CAPEv2#2188]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [X] I did read the README!
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I have read and checked all configs (with all optional parts)

# Expected Behavior

Finished analysis with reports.

# Current Behavior

When I submit a sample to analize, an unhandled exception is throwed. See Failure Logs section. I've installed Volatility3 to full memory dump analysis.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit a sample via web interface.
2. Boom!

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 8727513a8c0494bd567ebddb9a5ca2874812ba0d
| OS version       | Ubuntu 22.04.4 LTS, Windows 10 (VM guest)

Config files:

**cuckoo.conf**
```
[cuckoo]
machinery_screenshots = on
memory_dump = on
freespace = 0
    
[resultserver]
ip = 192.168.2.1
```
**auxiliary.conf**
```
[auxiliary_modules]
procmon = yes
sysmon_windows = yes

[sniffer]
interface = virbr1
```
**kvm.conf**
```
[kvm]
machines = vm01

[vm01]
label = win10_msoffice
ip = 192.168.2.10
platform = windows
tags = win10,msoffice
snapshot = snapshot1
arch = x64
```
**memory.conf**
```
[basic]
guest_profile = Win10x64
delete_memdump = no

[malfind]
enabled = yes

[pslist]
enabled = yes

[psscan]
enabled = yes

[callbacks]
enabled = yes

[svcscan]
enabled = yes
```
**processing.conf**
```
[flare_capa]
enabled = yes
static = yes
cape = yes
procdump = yes

[detections]
virustotal = yes

[procmon]
enabled = yes

[memory]
enabled = yes

[virustotal]
enabled = yes
# API Key omitida por confidencialidad en este documento.
key = 697P45....a59

[deduplication]
enabled = yes

[xlsdeobf]
enabled = yes
```
**reporting.conf**
```
[mitre]
enabled = yes

[reporthtml]
enabled = yes
screenshots = yes
apicalls = yes

[reporthtmlsummary]
enabled = yes
screenshots = yes

[reportpdf]
enabled = yes
```
**web.conf**
```
[malscore]
enabled = yes
```

## Failure Logs

![cape](https://github.com/kevoreilly/CAPEv2/assets/14922220/227a5c06-3222-4d3e-9597-94c80b9a2b30)

**Comment by doomedraven** [comment]
Try to disable capa in processing and reprocess a job just as test

**Comment by albertososa95** [comment]
CAPA disabled in processing and submited new sample with default options. Now it has a timeout:

![cape3](https://github.com/kevoreilly/CAPEv2/assets/14922220/79a252b2-ad9f-4d6b-be3a-64e729660c50)

I think that CAPA is not the problem, since my sample is a .doc, so this error message is correct from CAPA. Anyway, I'm working with snapshots (CAPE-host is a VM) and I notice that this error starts since I installed Volatility3 and flare-floss via poetry:
```
$ sudo -u cape poetry run pip install -U volatility3 flare-floss
```
Will be it related?

**Comment by doomedraven** [comment]
could be, i don't use capa, floss neither volatility integrations so idk in which state those plugins are

**Comment by albertososa95** [comment]
So, if I understand the memory analysis with Volatility should be done outside CAPE-host, right?

**Comment by doomedraven** [comment]
well you can use that in cape, but the thing here is that i don't maintain things that i don't use, is just unreal, so sometime community or other people must help support updated version of those libraries, it should works with the versions that is in pyproject, but if you install newer, then that's not ensured by us.

**Comment by albertososa95** [comment]
Ok perfect. I confirm that if I install Volatility, the cape-processor crashes.

**Comment by albertososa95** [comment]
Hi again! I setup tmpfs for memory dump analysis with Volatility and it doesn't crash due to timeout now.

**Comment by albertososa95** [comment]
News... I check that some Volatility modules configured in memory.conf are crashing MongoDB reports (first log error in this issue).

**Comment by doomedraven** [comment]
what modules crashing it? yes tmpfs speedup a lot processing of memdumps, but bear in mind as much plugins you enable, you might need to consider increase timeout from 900 to higher value

**Comment by albertososa95** [comment]
_malfind_ is the first module that causes the crash. If you see the first screenshot in the issue, the exception is throwed at `deepcopy` function. Maybe there is a mismatch between libraries versions and expected data structures (?)

**Comment by doomedraven** [comment]
Probably it returns something that wasn't converted to json

**Comment by albertososa95** [comment]
Mm, not sure about that. I tried to replace the `deepcopy` with a JSON dump and load (only for test purposes) and it doesn't throw exceptions - errors. I've all modules enabled in `memory.conf` and it shows all information in web interface.

**Comment by doomedraven** [comment]
That's interesting, hm would need to investigate once I have some spare time

**Comment by mhdo298** [comment]
Hi, sorry for digging this back up but I'm pretty sure I'm facing exactly the same issue, here's the log (I changed volatility's logging to debug, so it's more verbose):
```
poetry run python utils/process.py 1 -r
pip3 install certvalidator asn1crypto mscerts
OPTIONAL! Missed dependency: poetry run pip install -U git+https://github.com/DissectMalware/batch_deobfuscator
OPTIONAL! Missed dependency: poetry run pip install -U git+https://github.com/CAPESandbox/httpreplay
2025-08-07 20:11:17,242 [Task 1] [volatility3.plugins.yarascan] DEBUG: Using yara-python module
2025-08-07 20:11:17,425 [Task 1] [volatility3.framework.automagic] INFO: Detected a windows category plugin
2025-08-07 20:11:17,429 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: ConstructionMagic
2025-08-07 20:11:17,456 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: SymbolCacheMagic
2025-08-07 20:11:17,549 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: LayerStacker
2025-08-07 20:11:17,669 [Task 1] [volatility3.schemas] INFO: Dependency for validation unavailable: jsonschema
2025-08-07 20:11:17,669 [Task 1] [volatility3.schemas] DEBUG: All validations will report success, even with malformed input
2025-08-07 20:11:17,684 [Task 1] [volatility3.framework.automagic.linux] INFO: No Linux banners found - if this is a linux plugin, please check your symbol files location
2025-08-07 20:11:17,693 [Task 1] [volatility3.framework.automagic.mac] INFO: No Mac banners found - if this is a mac plugin, please check your symbol files location
2025-08-07 20:11:17,699 [Task 1] [volatility3.framework.automagic.linux] INFO: No Linux banners found - if this is a linux plugin, please check your symbol files location
2025-08-07 20:11:17,705 [Task 1] [volatility3.framework.automagic.windows] DEBUG: Detecting Self-referential pointer for recent windows
2025-08-07 20:11:17,749 [Task 1] [volatility3.framework.automagic.windows] DEBUG: DtbSelfRef64bit test succeeded at 0x1aa000
2025-08-07 20:11:17,753 [Task 1] [volatility3.framework.automagic.windows] DEBUG: DTB was found at: 0x1aa000
2025-08-07 20:11:17,878 [Task 1] [volatility3.schemas] INFO: Dependency for validation unavailable: jsonschema
2025-08-07 20:11:17,879 [Task 1] [volatility3.schemas] DEBUG: All validations will report success, even with malformed input
2025-08-07 20:11:17,905 [Task 1] [volatility3.framework.automagic.stacker] DEBUG: physical_layer maximum_address: 2164461554
2025-08-07 20:11:17,905 [Task 1] [volatility3.framework.automagic.stacker] DEBUG: Stacked layers: ['IntelLayer', 'Elf64Layer', 'FileLayer']
2025-08-07 20:11:17,914 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: WinSwapLayers
2025-08-07 20:11:17,919 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: KernelPDBScanner
2025-08-07 20:11:18,046 [Task 1] [volatility3.framework.automagic.pdbscan] DEBUG: Kernel base determination - searching layer module list structure
2025-08-07 20:11:28,001 [Task 1] [volatility3.framework.automagic.pdbscan] DEBUG: Kernel base determination - searching layer module list structure
2025-08-07 20:11:28,181 [Task 1] [volatility3.framework.automagic.pdbscan] DEBUG: Setting kernel_virtual_offset to 0xf8055bc1c000
2025-08-07 20:11:28,186 [Task 1] [volatility3.framework.symbols.windows.pdbutil] DEBUG: Using symbol library: ntkrnlmp.pdb/D9424FC4861E47C10FAD1B35DEC6DCC8-1
2025-08-07 20:11:28,484 [Task 1] [volatility3.schemas] INFO: Dependency for validation unavailable: jsonschema
2025-08-07 20:11:28,484 [Task 1] [volatility3.schemas] DEBUG: All validations will report success, even with malformed input
2025-08-07 20:11:28,494 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: SymbolFinder
2025-08-07 20:11:28,494 [Task 1] [volatility3.framework.automagic] INFO: Running automagic: KernelModule
2025-08-07 20:11:28,536 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_PO_PROCESS_ENERGY_CONTEXT
2025-08-07 20:11:28,549 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_EPROCESS_QUOTA_BLOCK
2025-08-07 20:11:28,554 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_PAGEFAULT_HISTORY
2025-08-07 20:11:28,567 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_JOB_ACCESS_STATE
2025-08-07 20:11:28,571 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_JOB_CPU_RATE_CONTROL
2025-08-07 20:11:28,575 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_JOB_NET_RATE_CONTROL
2025-08-07 20:11:28,579 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_JOB_NOTIFICATION_INFORMATION
2025-08-07 20:11:28,583 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_PSP_STORAGE
2025-08-07 20:11:28,599 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_ACTIVATION_CONTEXT_DATA
2025-08-07 20:11:28,603 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_ASSEMBLY_STORAGE_MAP
2025-08-07 20:11:28,616 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_EXP_LICENSE_STATE
2025-08-07 20:11:28,646 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_DBGKP_ERROR_PORT
2025-08-07 20:11:28,651 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_CI_NGEN_PATHS
2025-08-07 20:11:28,656 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_EX_WNF_SUBSCRIPTION
2025-08-07 20:11:28,692 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_ETW_EVENT_CALLBACK_CONTEXT
2025-08-07 20:11:28,698 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_ETW_SOFT_RESTART_CONTEXT
2025-08-07 20:11:28,701 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_ETW_STACK_CACHE
2025-08-07 20:11:28,719 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_ETW_PERFECT_HASH_FUNCTION
2025-08-07 20:11:28,725 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_EX_TIMER
2025-08-07 20:11:28,729 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_HAL_PMC_COUNTERS
2025-08-07 20:11:29,000 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_DEVICE_NODE_IOMMU_EXTENSION
2025-08-07 20:11:29,024 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_SCSI_REQUEST_BLOCK
2025-08-07 20:11:29,062 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_AWEINFO
2025-08-07 20:11:29,089 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_MI_ZERO_THREAD_CONTEXT
2025-08-07 20:11:29,097 [Task 1] [volatility3.framework.symbols] DEBUG: Unresolved reference: symbol_table_name1!_MI_SLAB_ALLOCATOR_ENTRY
2025-08-07 20:12:22,909 [Task 1] [volatility3.plugins.windows.malware.malfind] DEBUG: [proc_id 3948] Found suspicious DIRTY + PAGE_EXECUTE_READ page at 0x2179a630000
2025-08-07 20:13:49,515 [Task 1] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB": BitField.__new__() missing 3 required positional arguments: 'type_name', 'object_info', and 'base_type'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 869, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/mongodb.py", line 110, in run
    report = get_json_document(results, self.analysis_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/CAPEv2/utils/../modules/reporting/report_doc.py", line 61, in get_json_document
    report = copy.deepcopy(results)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 196, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 253, in _reconstruct
    y = func(*args)
        ^^^^^^^^^^^
  File "/usr/lib/python3.12/copyreg.py", line 99, in __newobj__
    return cls.__new__(cls, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BitField.__new__() missing 3 required positional arguments: 'type_name', 'object_info', and 'base_type'
```
I could probably try to provide the entire analysis folder if that helps, the mem dump itself is actually only 2GB. I'm also pretty sure this isn't *really* a CAPE issue and more likely a volatility issue, but since it's only a problem with the reporting module and not the processing module, I still think it's worth posting here.

I tried to do this in the `get_json_document` function, and it did allow the processing to finish, with a valid-looking report, but I'm sure this might lose some information that could be importnant? Then again, since this seems to need to produce JSON-valid data, this approach would make sense?
```python
report = json.loads(json.dumps(results))
```

**Comment by doomedraven** [comment]
the issue is in malfind code as far as i remember, can you disable it and reprocess that job just to reduce the area of search?

**Comment by mhdo298** [comment]
It is very likely just malfind, I tried some of the other plugins separately and they work fine.

**Comment by mhdo298** [comment]
I checked the volaitility repository because I saw that the [renderer used in CAPE](https://github.com/kevoreilly/CAPEv2/blob/master/modules/processing/memory.py#L61) is basically just the [renderer from volatility](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/cli/text_renderer.py#L569) but returned the output instead of printing it. This means that the output returned is originally meant to just be JSON, and so perhaps it should return `json.loads(json.dumps(final_output[1]))` (json.dumps is what the original renderer does, we're just loading it back as an object) instead of just `final_output[1]`.

Edit: I did run the processor with this change and it does work with malfind.

**Comment by doomedraven** [comment]
like this right? https://github.com/kevoreilly/CAPEv2/pull/2663

**Comment by mhdo298** [comment]
Yep. It seems like one of the test failed, but I’m guessing that’s due to a Yara rule and not the actual change made here?

**Comment by doomedraven** [comment]
yes, thank you for help on this
