### ISSUE TITLE
Task #1: Failure in AnalysisManager.run: start() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by vineethsai** [kevoreilly/CAPEv2#219]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The expected behavior is to start the analysis and complete it.

# Current Behavior

There is a TypeError and the analysis fails. 

# Failure Information (for bugs)

```
2020-06-30 00:55:29,238 [modules.machinery.aws] DEBUG: Old volume vol-0f412abcd68db509f in state available
2020-06-30 00:55:29,239 [modules.machinery.aws] DEBUG: Deleting old volume
2020-06-30 00:55:29,322 [modules.machinery.aws] DEBUG: Creating new volume
2020-06-30 00:55:29,678 [modules.machinery.aws] DEBUG: Created new volume vol-0f412abcd68db509f
2020-06-30 00:55:32,954 [modules.machinery.aws] DEBUG: new volume vol-0f412abcd68db509f in state available
2020-06-30 00:55:32,954 [modules.machinery.aws] DEBUG: Attaching new volume
2020-06-30 00:55:33,202 [modules.machinery.aws] DEBUG: response {'AttachTime': datetime.datetime(2020, 6, 30, 0, 55, 33, 187000, tzinfo=tzlocal()), 'Device': '/dev/sda1', 'InstanceId': 'i-0ae7f9bc0f05e97c3', 'State': 'attaching', 'VolumeId': 'vol-0f412abcd68db509f', 'ResponseMetadata': {'RequestId': '3cb12346-e26a-4168-889b-6472f69f80e4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '3cb12346-e26a-4178-889b-6472f69f80e4', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '411', 'date': 'Tue, 30 Jun 2020 00:55:32 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}
2020-06-30 00:55:33,320 [modules.machinery.aws] DEBUG: new volume vol-0f412abcd68db509f in state in-use
2020-06-30 00:55:33,329 [root] DEBUG: Stopped tracking machine 172.16.134.211 for task #2
2020-06-30 00:55:33,388 [modules.machinery.aws] INFO: instance state: poweroff
2020-06-30 00:55:33,737 [lib.cuckoo.core.scheduler] ERROR: Task #2: Failure in AnalysisManager.run: start() missing 1 required positional argument: 'task'
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 413, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 304, in launch_analysis
    machinery.start(self.machine.label)
TypeError: start() missing 1 required positional argument: 'task'
ERROR    lib.cuckoo.core.scheduler: Task #2: Failure in AnalysisManager.run: start() missing 1 required positional argument: 'task'
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 413, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 304, in launch_analysis
    machinery.start(self.machine.label)
TypeError: start() missing 1 required positional argument: 'task'
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start the web UI
2. Upload any file. (I uploaded a .pdf file)

## Context
I'm trying the instance on Ec2 AWS. I adapted the code from https://github.com/CheckPointSW/Cuckoo-AWS

## Failure Logs

Home screen: 

![Screen Shot 2020-06-29 at 6 10 51 PM](https://user-images.githubusercontent.com/23186197/86071340-e1a4e500-ba33-11ea-8195-67bea9941882.png)

Recent screen: 
![Screen Shot 2020-06-29 at 6 11 15 PM](https://user-images.githubusercontent.com/23186197/86071365-ee293d80-ba33-11ea-9ad7-6bdd5a59d9c4.png)

Upload selections:
![Screen Shot 2020-06-29 at 6 12 08 PM](https://user-images.githubusercontent.com/23186197/86071428-0dc06600-ba34-11ea-87cb-b0806cf4bc21.png)

**Comment by doomedraven** [comment]
Without see aws machinery module this is impossible to solve

**Comment by vineethsai** [comment]
Here are the AWS machinery modules:

1. aws.py: https://github.com/CheckPointSW/Cuckoo-AWS/blob/master/cuckoo/machinery/aws.py 
2. aws.conf: https://github.com/CheckPointSW/Cuckoo-AWS/blob/master/cuckoo/private/cwd/conf/aws.conf

my config file looks the same without any changes. The only other changes I made are changing some py2.7 code to py3 code and file locations. Do you want me to directly paste the code or will this be good?

**Comment by doomedraven** [comment]
copy & paste from cuckoo doesn't work, you need to adjust function args, as in CAPE there no task args and is why it was failing, i pushed fix to your pr for this issue but there could be more issues you need to test it, and i strongly suggest to follow checking others machinery modules in CAPE to compare func args
