### ISSUE TITLE
The view dashboard.views.index didn't return an HttpResponse object. It returned None instead.

### ISSUE THREAD

**Issue by YungBinary** [kevoreilly/CAPEv2#2348]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

# Expected Behavior

Expected to be able to load the index at 127.0.0.1:8000

# Current Behavior

I am unable to load the dashboard page for CAPEv2 on a fresh install. I've tried reinstalling with "All" and "base". Not sure what the issue is as nothing suspect is printed to journalctl as seen below. I've confirmed all other pages are loading fine, e.g. recent, submit, etc. To resolve this I submitted a file and let it finish and now the dashboard loads. I suspect anyone installing CAPEv2 from scratch may run into this. 

# Failure Information (for bugs)

```
cape-web.service - CAPE WSGI app
     Loaded: loaded (/lib/systemd/system/cape-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-10-11 23:41:17 UTC; 5min ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 1547 (python)
      Tasks: 3 (limit: 37537)
     Memory: 516.9M
        CPU: 19.753s
     CGroup: /system.slice/cape-web.service
             ├─1547 /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python manage.py runserver_plus 0.0.0.0:8000 --traceback --keep-meta-shutdown
             └─1713 /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python manage.py runserver_plus 0.0.0.0:8000 --traceback --keep-meta-shutdown

python3[1713]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers>
python3[1713]:     response = get_response(request)
python3[1713]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers>
python3[1713]:     self.check_response(response, callback)
python3[1713]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers>
python3[1713]:     raise ValueError(
python3[1713]: ValueError: The view dashboard.views.index didn't return an HttpResponse object. It returned None instead.
python3[1713]: 127.0.0.1 - - [11/Oct/2024 23:45:04] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Ubuntu 22.04
2. Install KVM/QEMU via kvm-qemu.sh All
3. Install CAPEv2 via cape2.sh All

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| Git commit       | Latest
| OS version       | Ubuntu 22.04

## Failure Logs

```
cape-web.service - CAPE WSGI app
     Loaded: loaded (/lib/systemd/system/cape-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-10-11 23:41:17 UTC; 5min ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 1547 (python)
      Tasks: 3 (limit: 37537)
     Memory: 516.9M
        CPU: 19.753s
     CGroup: /system.slice/cape-web.service
             ├─1547 /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python manage.py runserver_plus 0.0.0.0:8000 --traceback --keep-meta-shutdown
             └─1713 /home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/bin/python manage.py runserver_plus 0.0.0.0:8000 --traceback --keep-meta-shutdown

python3[1713]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers>
python3[1713]:     response = get_response(request)
python3[1713]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers>
python3[1713]:     self.check_response(response, callback)
python3[1713]:   File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers>
python3[1713]:     raise ValueError(
python3[1713]: ValueError: The view dashboard.views.index didn't return an HttpResponse object. It returned None instead.
python3[1713]: 127.0.0.1 - - [11/Oct/2024 23:45:04] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
```

**Comment by doomedraven** [comment]
hello, that is not enough info to reproduce, i need the html error image that you see when you open browser

**Comment by aaron-boyd** [comment]
When I first installed cape my machine pulled down commit fdb291ae110faab1c52f076c83cd6da78e20079e. This worked fine until I pulled from master on 10/11/2024. After a generic install I receive the same error when accessing the cape web-ui.

```
sudo ./kvm-qemu.sh all $USER 2>&1 | sudo tee kvm-qemu.log
sudo ./cape2.sh all cape 2>&1 | sudo tee cape.log
```

```
Traceback (most recent call last):
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/cape/.cache/pypoetry/virtualenvs/capev2-t2x27zRb-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view dashboard.views.index didn't return an HttpResponse object. It returned None instead.
```

**Comment by doomedraven** [comment]
ok, do git pull and restart web server, this should be fixed here, thanks for reporting 

https://github.com/kevoreilly/CAPEv2/commit/432ca07268290ce8b7fcff43eba02c5d0da66b26

**Comment by doomedraven** [comment]
let me know if that doesn't fix, closing
