### ISSUE TITLE
Reporting on URLs using Microsoft Edge fails due to a resubmitexe error

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2441]
``python
2024-12-23 13:26:16,210 [modules.processing.network] INFO: Loading maxmind database from /opt/CAPEv2/modules/processing/../../data/GeoLite2-Country.mmdb
2024-12-23 13:26:29,185 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "binary_yara": 'target'
2024-12-23 13:26:29,187 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "phishing_kit_detected": 'target'
2024-12-23 13:26:29,187 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "phishing_kit_detected": 'target'
2024-12-23 13:26:29,187 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "phishing_kit_detected": 'target'
2024-12-23 13:26:29,193 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "suspicious_html_body": 'target'
2024-12-23 13:26:29,194 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "suspicious_html_name": 'target'
2024-12-23 13:26:29,194 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "suspicious_html_title": 'target'
2024-12-23 13:26:29,301 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run signature "registry_credential_store_access": 'target'
2024-12-23 13:26:39,189 [Task 162] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ReSubmitExtractedEXE": 'target'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 756, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/resubmitexe.py", line 213, in run
    if results["target"]["category"] == "file" and self.results["target"]["file"]["sha256"] == dropped["sha256"]:
KeyError: 'target'
```

I'm not sure what the missing `target` key is in this case, or why it is missing.

**Comment by doomedraven** [comment]
target is target file/url, details, so is very strange that it missing, you maybe have another error there, try to reprocess the same analysis `poetry run python process.py -r X -d`

**Comment by seanthegeek** [comment]
This just got stranger. resubmitexe is the only thing that failed, I can see results if I go to the  report URL. but the results list says `failed_analysis`

```text
2024-12-23 13:45:04,122 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "CAPASummary"
2024-12-23 13:45:04,122 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "MITRE_TTPS"
2024-12-23 13:45:04,618 [Task 140] [Base.Attck] DEBUG: Calling MITRE Enterprise ATT&CK Framework
2024-12-23 13:45:12,720 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "PCAP2CERT"
2024-12-23 13:46:32,067 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "ReportHTMLSummary"
2024-12-23 13:46:32,150 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "ReSubmitExtractedEXE"
2024-12-23 13:46:32,150 [Task 140] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ReSubmitExtractedEXE": 'target'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 756, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/resubmitexe.py", line 213, in run
    if results["target"]["category"] == "file" and self.results["target"]["file"]["sha256"] == dropped["sha256"]:
KeyError: 'target'
2024-12-23 13:46:32,151 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "JsonDump"
2024-12-23 13:46:32,291 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "ReportPDF"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-cape'
2024-12-23 13:46:37,267 [Task 140] [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "MongoDB"
2024-12-23 13:46:39,324 [Task 140] [modules.reporting.mongodb] DEBUG: Deleted previous MongoDB data for Task 140
2024-12-23 13:46:39,668 [Task 140] [root] DEBUG: Finished processing task
```

**Comment by doomedraven** [comment]
that strange, without target you shouldn't be able to see anything related to that url on the web

**Comment by seanthegeek** [comment]
All I'm doing in analyzing example.com in microsoft edge and google chrome

**Comment by doomedraven** [comment]
fixed now too ,thanks for headups, i personally don't use url analysis at all
