### ISSUE TITLE
proxmox machinery broken post 2020-08-29

### ISSUE THREAD

**Issue by vlashef** [kevoreilly/CAPEv2#258]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

analysis is performed using proxmox machinery.

# Current Behavior

after recent pull of master issue began being observed on 2020-08-29

Upon submission of a sample the controller fails to initiate analysis through proxmox machinery.

# Failure Information (for bugs)

==> cuckoo.log <==
2020-09-01 09:23:18,710 [lib.cuckoo.core.scheduler] INFO: Task #2482: Starting analysis of FILE '/opt/tmp/cuckoo-tmp/upload_6f3nnud9/9xasamvTkUFwRx'
2020-09-01 09:23:18,806 [lib.cuckoo.core.scheduler] INFO: Task #2482: File already exists at '/opt/CAPEv2/storage/binaries/59e4659462484cb2521326bf335bef31a68d99748cfc082165562c5da42336c6'
2020-09-01 09:23:18,835 [lib.cuckoo.core.scheduler] INFO: Task #2482: acquired machine c1 (label=c1, platform=windows)
2020-09-01 09:23:21,494 [lib.cuckoo.core.scheduler] ERROR: Task #2482: Failure in AnalysisManager.run: 'name'
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 308, in launch_analysis
    machinery.start(self.machine.label)
  File "/opt/CAPEv2/modules/machinery/proxmox.py", line 191, in start
    vm, node = self.find_vm(label)
  File "/opt/CAPEv2/modules/machinery/proxmox.py", line 65, in find_vm
    if vm["name"] == label:
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 415, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 363, in launch_analysis
    machinery.stop(self.machine.label)
  File "/opt/CAPEv2/modules/machinery/proxmox.py", line 222, in stop
    vm, node = self.find_vm(label)
  File "/opt/CAPEv2/modules/machinery/proxmox.py", line 65, in find_vm
    if vm["name"] == label:
KeyError: 'name'

**Comment by doomedraven** [comment]
hello, that is community machinery, we don't really support it so you need to fix it by yourself or wait till someone fixes it, we only recommends to use kvm
