### ISSUE TITLE
python script does not Behavioral Analysis

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#265]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Submit python script and try Behavioral Analysis

# Current Behavior

 python script does not work while Behavioral Analysis

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit test python script via API to CAPE instance.
2. finish report and look but  Behavioral Analysis report empty.
3. look /opt/CAPEv2/storage/analyses/ID/analysis.log.
 "lib.common.exceptions.CuckooError: The package "modules.packages.python" start function raised an error: Unable to find any Python executable." error exsist.

## Context

Using machinery VirtualBox
Host machine: ubuntu 20.04.1 LTS
Guest machine: Windows 10  (python3.8 installed and set Environment variable)

## Failure Logs

Analyzer log:
```
(venv-cape) root@cape:/opt/CAPEv2/storage/analyses/154# cat analysis.log 
2020-09-08 17:56:12,347 [root] INFO: Date set to: 20200909T00:54:36, timeout set to: 200
2020-09-09 00:54:36,026 [root] DEBUG: Starting analyzer from: C:\tmpwlzn1b50
2020-09-09 00:54:36,026 [root] DEBUG: Storing results at: C:\iunkQHR
2020-09-09 00:54:36,026 [root] DEBUG: Pipe server name: \\.\PIPE\LcpgxE
2020-09-09 00:54:36,026 [root] DEBUG: Python path: C:\Users\IEUser\AppData\Local\Programs\Python\Python38-32
2020-09-09 00:54:36,026 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2020-09-09 00:54:36,026 [root] INFO: Automatically selected analysis package "python"
2020-09-09 00:54:36,026 [root] DEBUG: Trying to import analysis package "python"...
2020-09-09 00:54:36,069 [root] DEBUG: Imported analysis package "python".
2020-09-09 00:54:36,069 [root] DEBUG: Trying to initialize analysis package "python"...
2020-09-09 00:54:36,069 [root] DEBUG: Initialized analysis package "python".
2020-09-09 00:54:36,243 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.browser"...
2020-09-09 00:54:36,297 [root] DEBUG: Imported auxiliary module "modules.auxiliary.browser".
2020-09-09 00:54:36,297 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.curtain"...
2020-09-09 00:54:36,327 [root] DEBUG: Imported auxiliary module "modules.auxiliary.curtain".
2020-09-09 00:54:36,327 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.digisig"...
2020-09-09 00:54:36,509 [root] DEBUG: Imported auxiliary module "modules.auxiliary.digisig".
2020-09-09 00:54:36,509 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.disguise"...
2020-09-09 00:54:36,544 [root] DEBUG: Imported auxiliary module "modules.auxiliary.disguise".
2020-09-09 00:54:36,544 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.human"...
2020-09-09 00:54:36,648 [root] DEBUG: Imported auxiliary module "modules.auxiliary.human".
2020-09-09 00:54:36,648 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.procmon"...
2020-09-09 00:54:36,713 [root] DEBUG: Imported auxiliary module "modules.auxiliary.procmon".
2020-09-09 00:54:36,713 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.screenshots"...
2020-09-09 00:54:36,745 [modules.auxiliary.screenshots] DEBUG: Importing 'time'
2020-09-09 00:54:36,745 [modules.auxiliary.screenshots] DEBUG: Importing 'StringIO'
2020-09-09 00:54:36,745 [modules.auxiliary.screenshots] DEBUG: Importing 'Thread'
2020-09-09 00:54:36,745 [modules.auxiliary.screenshots] DEBUG: Importing 'Auxiliary'
2020-09-09 00:54:36,745 [modules.auxiliary.screenshots] DEBUG: Importing 'NetlogFile'
2020-09-09 00:54:36,745 [modules.auxiliary.screenshots] DEBUG: Importing 'Screenshot'
2020-09-09 00:54:36,787 [lib.api.screenshot] DEBUG: Importing 'math'
2020-09-09 00:54:36,787 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2020-09-09 00:54:37,203 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageGrab'
2020-09-09 00:54:37,230 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2020-09-09 00:54:37,230 [modules.auxiliary.screenshots] DEBUG: Imports OK
2020-09-09 00:54:37,230 [root] DEBUG: Imported auxiliary module "modules.auxiliary.screenshots".
2020-09-09 00:54:37,230 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.sysmon"...
2020-09-09 00:54:37,230 [root] DEBUG: Imported auxiliary module "modules.auxiliary.sysmon".
2020-09-09 00:54:37,230 [root] DEBUG: Trying to import auxiliary module "modules.auxiliary.usage"...
2020-09-09 00:54:37,289 [root] DEBUG: Imported auxiliary module "modules.auxiliary.usage".
2020-09-09 00:54:37,289 [root] DEBUG: Trying to initialize auxiliary module "Browser"...
2020-09-09 00:54:37,289 [root] DEBUG: Initialized auxiliary module "Browser".
2020-09-09 00:54:37,289 [root] DEBUG: Trying to start auxiliary module "Browser"...
2020-09-09 00:54:37,289 [root] DEBUG: Started auxiliary module Browser
2020-09-09 00:54:37,289 [root] DEBUG: Trying to initialize auxiliary module "Curtain"...
2020-09-09 00:54:37,289 [root] DEBUG: Initialized auxiliary module "Curtain".
2020-09-09 00:54:37,289 [root] DEBUG: Trying to start auxiliary module "Curtain"...
2020-09-09 00:54:37,289 [root] DEBUG: Started auxiliary module Curtain
2020-09-09 00:54:37,289 [root] DEBUG: Trying to initialize auxiliary module "DigiSig"...
2020-09-09 00:54:37,289 [root] DEBUG: Initialized auxiliary module "DigiSig".
2020-09-09 00:54:37,289 [root] DEBUG: Trying to start auxiliary module "DigiSig"...
2020-09-09 00:54:37,289 [modules.auxiliary.digisig] DEBUG: Checking for a digital signature.
2020-09-09 00:54:37,825 [modules.auxiliary.digisig] DEBUG: File format not recognized.
2020-09-09 00:54:37,825 [modules.auxiliary.digisig] INFO: Uploading signature results to aux/DigiSig.json
2020-09-09 00:54:37,825 [root] DEBUG: Started auxiliary module DigiSig
2020-09-09 00:54:37,825 [root] DEBUG: Trying to initialize auxiliary module "Disguise"...
2020-09-09 00:54:37,825 [root] DEBUG: Initialized auxiliary module "Disguise".
2020-09-09 00:54:37,825 [root] DEBUG: Trying to start auxiliary module "Disguise"...
2020-09-09 00:54:37,825 [modules.auxiliary.disguise] INFO: Disguising GUID to 6e74ed60-6046-4dd9-838d-99c679e24ed3
2020-09-09 00:54:37,825 [root] DEBUG: Started auxiliary module Disguise
2020-09-09 00:54:37,825 [root] DEBUG: Trying to initialize auxiliary module "Human"...
2020-09-09 00:54:37,825 [root] DEBUG: Initialized auxiliary module "Human".
2020-09-09 00:54:37,825 [root] DEBUG: Trying to start auxiliary module "Human"...
2020-09-09 00:54:37,825 [root] DEBUG: Started auxiliary module Human
2020-09-09 00:54:37,825 [root] DEBUG: Trying to initialize auxiliary module "Procmon"...
2020-09-09 00:54:37,879 [root] DEBUG: Initialized auxiliary module "Procmon".
2020-09-09 00:54:37,879 [root] DEBUG: Trying to start auxiliary module "Procmon"...
2020-09-09 00:54:37,884 [root] DEBUG: Started auxiliary module Procmon
2020-09-09 00:54:37,884 [root] DEBUG: Trying to initialize auxiliary module "Screenshots"...
2020-09-09 00:54:37,884 [root] DEBUG: Initialized auxiliary module "Screenshots".
2020-09-09 00:54:37,884 [root] DEBUG: Trying to start auxiliary module "Screenshots"...
2020-09-09 00:54:37,884 [root] DEBUG: Started auxiliary module Screenshots
2020-09-09 00:54:37,884 [root] DEBUG: Trying to initialize auxiliary module "Sysmon"...
2020-09-09 00:54:37,884 [root] DEBUG: Initialized auxiliary module "Sysmon".
2020-09-09 00:54:37,884 [root] DEBUG: Trying to start auxiliary module "Sysmon"...
2020-09-09 00:54:37,884 [root] DEBUG: Started auxiliary module Sysmon
2020-09-09 00:54:37,884 [root] DEBUG: Trying to initialize auxiliary module "Usage"...
2020-09-09 00:54:37,884 [root] DEBUG: Initialized auxiliary module "Usage".
2020-09-09 00:54:37,884 [root] DEBUG: Trying to start auxiliary module "Usage"...
2020-09-09 00:54:37,884 [root] DEBUG: Started auxiliary module Usage
2020-09-09 00:54:37,884 [root] INFO: Analyzer: Package modules.packages.python does not specify a DLL option
2020-09-09 00:54:37,884 [root] INFO: Analyzer: Package modules.packages.python does not specify a DLL_64 option
2020-09-09 00:54:37,884 [root] INFO: Analyzer: Package modules.packages.python does not specify a loader option
2020-09-09 00:54:37,884 [root] INFO: Analyzer: Package modules.packages.python does not specify a loader_64 option
2020-09-09 00:54:38,282 [root] ERROR: Traceback (most recent call last):
  File "C:/tmpwlzn1b50/analyzer.py", line 502, in run
    pids = self.package.start(self.target)
  File "C:\tmpwlzn1b50\modules\packages\python.py", line 17, in start
    python = self.get_path_glob("Python")
  File "C:\tmpwlzn1b50\lib\common\abstracts.py", line 96, in get_path_glob
    raise CuckooPackageError("Unable to find any %s executable." % application)
lib.common.exceptions.CuckooPackageError: Unable to find any Python executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpwlzn1b50/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmpwlzn1b50/analyzer.py", line 506, in run
    raise CuckooError('The package "{0}" start function raised an ' "error: {1}".format(package_name, e))
lib.common.exceptions.CuckooError: The package "modules.packages.python" start function raised an error: Unable to find any Python executable.
Traceback (most recent call last):
  File "C:/tmpwlzn1b50/analyzer.py", line 502, in run
    pids = self.package.start(self.target)
  File "C:\tmpwlzn1b50\modules\packages\python.py", line 17, in start
    python = self.get_path_glob("Python")
  File "C:\tmpwlzn1b50\lib\common\abstracts.py", line 96, in get_path_glob
    raise CuckooPackageError("Unable to find any %s executable." % application)
lib.common.exceptions.CuckooPackageError: Unable to find any Python executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmpwlzn1b50/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmpwlzn1b50/analyzer.py", line 506, in run
    raise CuckooError('The package "{0}" start function raised an ' "error: {1}".format(package_name, e))
lib.common.exceptions.CuckooError: The package "modules.packages.python" start function raised an error: Unable to find any Python executable.
2020-09-09 00:54:38,282 [root] WARNING: Folder at path "C:\iunkQHR\debugger" does not exist, skip.
2020-09-09 00:54:38,282 [root] INFO: Analysis completed.


```

**Comment by doomedraven** [comment]
hello, can you check where is your python installed? the whole path to python.exe? as package looks just fine i just checked it should be `C:\\Python*\\python.exe`

**Comment by ai-suzuki** [comment]
Thank you for your support.
The path to python.exe is ` c:\Users\<username>\AppData\Local\Programs\Python\Python38-32\python.exe`

**Comment by doomedraven** [comment]
you are welcome, that is the problem, that isn't a default python path, did you install it with custom path? any fork of default python like activepython? any other?

**Comment by ai-suzuki** [comment]
ohh,
but i did not set custom path. i just checked `add python environment variable`
i installed this one
https://www.python.org/getit/
Should I reinstall it so that` C:\\Python*\\python.exe`?

**Comment by doomedraven** [comment]
try to reinstall and pay atenttion to the path for me it installed it to c:\ directly, can you check one thing, if you have `c:\windows\py.exe`?

**Comment by ai-suzuki** [comment]
i have c:\windows\py.exe !

**Comment by doomedraven** [comment]
ok then you don't need to do nothing, i will push check for that one and it will do the trick for you, do `git pull` in 1 min

**Comment by doomedraven** [comment]
done, `git pull` and now you should go fine, can you test it?

**Comment by ai-suzuki** [comment]
OK, Wait a moment

**Comment by ai-suzuki** [comment]
git pull  log
```
(venv-cape) root@cape:/opt/CAPEv2# git pull
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 104 (delta 62), reused 75 (delta 59), pack-reused 18
Receiving objects: 100% (104/104), 307.09 KiB | 567.00 KiB/s, done.
Resolving deltas: 100% (63/63), completed with 21 local objects.
From https://github.com/kevoreilly/CAPEv2
   f6f1547..b3f78de  master     -> origin/master
Updating f6f1547..b3f78de
Fast-forward
 analyzer/windows/dll/capemon.dll            | Bin 632832 -> 632832 bytes
 analyzer/windows/dll/capemon_x64.dll        | Bin 764416 -> 763392 bytes
 analyzer/windows/lib/core/packages.py       |   6 ++-
 analyzer/windows/modules/packages/inp.py    |  32 ++++++++++++
 analyzer/windows/modules/packages/python.py |   1 +
 lib/cuckoo/core/plugins.py                  |   2 +-
 modules/machinery/kvm.py                    |   3 +-
 modules/processing/network.py               |   1 +
 modules/processing/static.py                |   4 +-
 utils/api.py                                |   4 +-
 utils/dist.py                               |  75 ++++++++++++++++------------
 utils/vpn2cape.py                           |   2 +-
 web/api/views.py                            |  14 +++---
 web/submission/views.py                     |   4 +-
 14 files changed, 97 insertions(+), 51 deletions(-)
 create mode 100644 analyzer/windows/modules/packages/inp.py
```

but this error ...  i restart cape and cape-web, so why?
```
oes not specify a loader option
2020-09-09 06:12:01,689 [root] INFO: Analyzer: Package modules.packages.python does not specify a loader_64 option
2020-09-09 06:12:02,350 [root] ERROR: Traceback (most recent call last):
  File "C:/tmp7ksh1spy/analyzer.py", line 502, in run
    pids = self.package.start(self.target)
  File "C:\tmp7ksh1spy\modules\packages\python.py", line 18, in start
    python = self.get_path_glob("Python")
  File "C:\tmp7ksh1spy\lib\common\abstracts.py", line 96, in get_path_glob
    raise CuckooPackageError("Unable to find any %s executable." % application)
lib.common.exceptions.CuckooPackageError: Unable to find any Python executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmp7ksh1spy/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmp7ksh1spy/analyzer.py", line 506, in run
    raise CuckooError('The package "{0}" start function raised an ' "error: {1}".format(package_name, e))
lib.common.exceptions.CuckooError: The package "modules.packages.python" start function raised an error: Unable to find any Python executable.
Traceback (most recent call last):
  File "C:/tmp7ksh1spy/analyzer.py", line 502, in run
    pids = self.package.start(self.target)
  File "C:\tmp7ksh1spy\modules\packages\python.py", line 18, in start
    python = self.get_path_glob("Python")
  File "C:\tmp7ksh1spy\lib\common\abstracts.py", line 96, in get_path_glob
    raise CuckooPackageError("Unable to find any %s executable." % application)
lib.common.exceptions.CuckooPackageError: Unable to find any Python executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/tmp7ksh1spy/analyzer.py", line 1373, in <module>
    success = analyzer.run()
  File "C:/tmp7ksh1spy/analyzer.py", line 506, in run
    raise CuckooError('The package "{0}" start function raised an ' "error: {1}".format(package_name, e))
lib.common.exceptions.CuckooError: The package "modules.packages.python" start function raised an error: Unable to find any Python executable.
2020-09-09 06:12:02,350 [root] WARNING: Folder at path "C:\hMnAJYte\debugger" does not exist, skip.
2020-09-09 06:12:02,350 [root] INFO: Analysis completed.
(venv-cape) root@cape:/opt/CAPEv2/storage/analyses/162# 
```

**Comment by doomedraven** [comment]
well the uniq thing that i can suggest is to install python to that path c:\ as it should be installed, i never say python being installed in another path, so that is the problem

**Comment by ai-suzuki** [comment]
I don't understand why, but I think so too.

**Comment by doomedraven** [comment]
closing as answered, that python installed in wrong path, did you solve it?

**Comment by ai-suzuki** [comment]
I haven't solved it yet.
Parsing the python script was postponed ...
I will contact you if it goes well.
