### ISSUE TITLE
issue when installing pillow 3.2.0 on Python 3.6

### ISSUE THREAD

**Issue by likescam** [kevoreilly/CAPEv2#364]
Hello, 

The last time before running cuckoo, I have to Install sflock by command:
`sudo pip3 install -U sflock`
But it cannot install sflock because the pillow==3.2.0 have problem with python3.5. So I try to install pillow3.2.0 by running:
`sudo pip3 install pillow==3.2.0
`
But both command can not help me install pillow3.2.0 and sflock.
I'm current running Python 3.6.9, Ubuntu 18.04 Full update.
Bellow is the log when try to install sflock/pillow3.2.0:
```
Collecting Pillow==3.2.0 (from peepdf>=0.4.1->sflock)
  Downloading https://files.pythonhosted.org/packages/e2/af/0a3981fffc5cd43078eb8b1057702e0dd2d5771e5aaa36cbd140e32f8473/Pillow-3.2.0.tar.gz (10.3MB)
    100% |████████████████████████████████| 10.3MB 78kB/s 
Requirement already up-to-date: pythonaes==1.0 in /usr/local/lib/python3.6/dist-packages (from peepdf>=0.4.1->sflock)
Requirement already up-to-date: pycparser in /home/cape/.local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1->sflock)
Installing collected packages: Pillow, peepdf, sflock
  Found existing installation: Pillow 8.0.1
    Uninstalling Pillow-8.0.1:
      Successfully uninstalled Pillow-8.0.1
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-78brn3_q/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e2fsrh2j-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    writing top-level names to Pillow.egg-info/top_level.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-3.6/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-78brn3_q/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(), )
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-78brn3_q/Pillow/setup.py", line 512, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
    
    ----------------------------------------
  Rolling back uninstall of Pillow
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-78brn3_q/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e2fsrh2j-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-78brn3_q/Pillow/
```

**Comment by doomedraven** [comment]
google that, that is pillow problem, https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux

**Comment by doomedraven** [comment]
+ we don't use that sflock, use my fork, see readme for instalation script, you have the rest there

**Comment by likescam** [comment]
Thank you @doomedraven 
But when running cape2.sh with: 
sudo ./cape2.sh All
It can not install sflock.
Trying to run your command on cape2.sh script, the log is:
`pip3 install git+https://github.com/doomedraven/sflock.git git+https://github.com/doomedraven/socks5man.git "pyattck>=2.0.2" distorm3 openpyxl git+https://github.com/volatilityfoundation/volatility3 git+https://github.com/DissectMalware/XLMMacroDeobfuscator passlib pyzipper`

```
Collecting git+https://github.com/doomedraven/sflock.git
  Cloning https://github.com/doomedraven/sflock.git to /tmp/pip-ndwa5b04-build
Collecting git+https://github.com/doomedraven/socks5man.git
  Cloning https://github.com/doomedraven/socks5man.git to /tmp/pip-kkm8g8rv-build
Collecting git+https://github.com/volatilityfoundation/volatility3
  Cloning https://github.com/volatilityfoundation/volatility3 to /tmp/pip-dd6samu1-build
Collecting git+https://github.com/DissectMalware/XLMMacroDeobfuscator
  Cloning https://github.com/DissectMalware/XLMMacroDeobfuscator to /tmp/pip-bjia4u8w-build
Requirement already satisfied: pyattck>=2.0.2 in /usr/local/lib/python3.6/dist-packages
Collecting distorm3
  Downloading https://files.pythonhosted.org/packages/36/0e/d11cf7fb81f00237c66c387acf91898822e9974ad5b7d8349867bc67567e/distorm3-3.5.0.tar.gz (137kB)
    100% |████████████████████████████████| 143kB 2.0MB/s 
Collecting openpyxl
  Downloading https://files.pythonhosted.org/packages/5c/90/61f83be1c335a9b69fa773784a785d9de95c7561d1661918796fd1cba3d2/openpyxl-3.0.5-py2.py3-none-any.whl (242kB)
    100% |████████████████████████████████| 245kB 3.9MB/s 
Collecting passlib
  Downloading https://files.pythonhosted.org/packages/3b/a4/ab6b7589382ca3df236e03faa71deac88cae040af60c071a78d254a62172/passlib-1.7.4-py2.py3-none-any.whl (525kB)
    100% |████████████████████████████████| 532kB 1.3MB/s 
Collecting pyzipper
  Downloading https://files.pythonhosted.org/packages/b4/64/2572e23af47c0c6f2abd4e0d4f25d6dd3647c6ada9841c2d6f634bffe55a/pyzipper-0.3.3-py2.py3-none-any.whl (162kB)
    100% |████████████████████████████████| 163kB 2.7MB/s 
Requirement already satisfied: click==6.6 in /home/cape/.local/lib/python3.6/site-packages (from SFlock==0.3.10)
Requirement already satisfied: cryptography>=2.1 in /home/cape/.local/lib/python3.6/site-packages (from SFlock==0.3.10)
Requirement already satisfied: olefile>=0.43 in /home/cape/.local/lib/python3.6/site-packages (from SFlock==0.3.10)
Collecting peepdf>=0.4.1 (from SFlock==0.3.10)
  Downloading https://files.pythonhosted.org/packages/01/0f/12a50ada4a3ff2a2c0c4c74e6fababf374eff037c9786745c51fdf246c8b/peepdf-0.4.2.tar.gz (108kB)
    100% |████████████████████████████████| 112kB 4.5MB/s 
Collecting python-magic>=0.4.13 (from SFlock==0.3.10)
  Downloading https://files.pythonhosted.org/packages/59/77/c76dc35249df428ce2c38a3196e2b2e8f9d2f847a8ca1d4d7a3973c28601/python_magic-0.4.18-py2.py3-none-any.whl
Collecting PySocks>=1.7 (from Socks5man==0.3.0)
  Downloading https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl
Collecting geoip2==2.9.0 (from Socks5man==0.3.0)
  Downloading https://files.pythonhosted.org/packages/ed/17/bcbb7c0849492e218767e658c66fbf9e3420b6301072371547c4f7192d48/geoip2-2.9.0-py2.py3-none-any.whl
Requirement already satisfied: SQLAlchemy<1.4,>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from Socks5man==0.3.0)
Collecting alembic<1.1,>=1.0.7 (from Socks5man==0.3.0)
  Downloading https://files.pythonhosted.org/packages/7b/8b/0c98c378d93165d9809193f274c3c6e2151120d955b752419c7d43e4d857/alembic-1.0.11.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 596kB/s 
Requirement already satisfied: pefile in /usr/local/lib/python3.6/dist-packages (from volatility==2.0.0b1)
Collecting pyxlsb2 (from XLMMacroDeobfuscator==0.1.5)
  Downloading https://files.pythonhosted.org/packages/15/ca/98eb1e630cc1d5c1f4a88ea402d91eec7844ace611fa55549ec6890509f8/pyxlsb2-0.0.2-py3-none-any.whl
Collecting lark-parser (from XLMMacroDeobfuscator==0.1.5)
  Downloading https://files.pythonhosted.org/packages/0a/f3/f8cac236af0e3a6003c015552ee12e9c4b0e67a7add675554baff8a75816/lark_parser-0.11.1-py2.py3-none-any.whl (93kB)
    100% |████████████████████████████████| 102kB 4.7MB/s 
Collecting xlrd2 (from XLMMacroDeobfuscator==0.1.5)
  Downloading https://files.pythonhosted.org/packages/c1/2f/69402836a43926868594d8c96d91092a9a3d61d524723a968e2277c60501/xlrd2-1.2.6-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 122kB 4.6MB/s 
Collecting untangle==1.1.1 (from XLMMacroDeobfuscator==0.1.5)
  Downloading https://files.pythonhosted.org/packages/f4/eb/a19a34858cd702b09524bd2ddb01c0d75a71f993a96aec8755a76e867911/untangle-1.1.1.tar.gz
Requirement already satisfied: msoffcrypto-tool in /usr/local/lib/python3.6/dist-packages (from XLMMacroDeobfuscator==0.1.5)
Requirement already satisfied: Pillow>=6.2.2 in /usr/local/lib/python3.6/dist-packages (from pyattck>=2.0.2)
Requirement already satisfied: PyYaml>=5.0 in /usr/local/lib/python3.6/dist-packages (from pyattck>=2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from pyattck>=2.0.2)
Requirement already satisfied: fire==0.3.1 in /usr/local/lib/python3.6/dist-packages (from pyattck>=2.0.2)
Requirement already satisfied: pendulum<1.3,>=1.2.3 in /usr/local/lib/python3.6/dist-packages (from pyattck>=2.0.2)
Requirement already satisfied: pyfiglet==0.8.post1 in /usr/local/lib/python3.6/dist-packages (from pyattck>=2.0.2)
Collecting et-xmlfile (from openpyxl)
  Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Collecting jdcal (from openpyxl)
  Downloading https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Collecting pycryptodomex (from pyzipper)
  Downloading https://files.pythonhosted.org/packages/ff/29/1541b26a2b679bafb124138c5f009ed7821d9d329536b79a313a9a1aa684/pycryptodomex-3.9.9-cp36-cp36m-manylinux1_x86_64.whl (13.7MB)
    100% |████████████████████████████████| 13.7MB 52kB/s 
Requirement already satisfied: six>=1.4.1 in /home/cape/.local/lib/python3.6/site-packages (from cryptography>=2.1->SFlock==0.3.10)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/cape/.local/lib/python3.6/site-packages (from cryptography>=2.1->SFlock==0.3.10)
Requirement already satisfied: jsbeautifier==1.6.2 in /home/cape/.local/lib/python3.6/site-packages (from peepdf>=0.4.1->SFlock==0.3.10)
Requirement already satisfied: colorama==0.3.7 in /home/cape/.local/lib/python3.6/site-packages (from peepdf>=0.4.1->SFlock==0.3.10)
Requirement already satisfied: future>=0.16.0 in /home/cape/.local/lib/python3.6/site-packages (from peepdf>=0.4.1->SFlock==0.3.10)
Requirement already satisfied: pythonaes==1.0 in /usr/local/lib/python3.6/dist-packages (from peepdf>=0.4.1->SFlock==0.3.10)
Collecting maxminddb>=1.4.0 (from geoip2==2.9.0->Socks5man==0.3.0)
  Downloading https://files.pythonhosted.org/packages/51/90/e1718dc14b9ecc7e1ef627f577d92d644a4acebcb4d97f6a6918e12591ba/maxminddb-2.0.3.tar.gz (286kB)
    100% |████████████████████████████████| 286kB 2.3MB/s 
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic<1.1,>=1.0.7->Socks5man==0.3.0)
Collecting python-editor>=0.3 (from alembic<1.1,>=1.0.7->Socks5man==0.3.0)
  Downloading https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from alembic<1.1,>=1.0.7->Socks5man==0.3.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->pyattck>=2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->pyattck>=2.0.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->pyattck>=2.0.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->pyattck>=2.0.2)
Requirement already satisfied: termcolor in /usr/local/lib/python3.6/dist-packages (from fire==0.3.1->pyattck>=2.0.2)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.6/dist-packages (from pendulum<1.3,>=1.2.3->pyattck>=2.0.2)
Requirement already satisfied: pytzdata in /usr/local/lib/python3.6/dist-packages (from pendulum<1.3,>=1.2.3->pyattck>=2.0.2)
Requirement already satisfied: pycparser in /home/cape/.local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1->SFlock==0.3.10)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from tzlocal->pendulum<1.3,>=1.2.3->pyattck>=2.0.2)
Installing collected packages: distorm3, et-xmlfile, jdcal, openpyxl, passlib, pycryptodomex, pyzipper, peepdf, python-magic, SFlock, PySocks, maxminddb, geoip2, python-editor, alembic, Socks5man, volatility, pyxlsb2, lark-parser, xlrd2, untangle, XLMMacroDeobfuscator
  Running setup.py install for distorm3 ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x65lz2va/distorm3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xevfg3zj-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/distorm3
    copying python/distorm3/_generated.py -> build/lib.linux-x86_64-3.6/distorm3
    copying python/distorm3/__main__.py -> build/lib.linux-x86_64-3.6/distorm3
    copying python/distorm3/__init__.py -> build/lib.linux-x86_64-3.6/distorm3
    running build_ext
    building '_distorm3' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/python
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DSUPPORT_64BIT_OFFSET -DDISTORM_DYNAMIC -Isrc -Iinclude -I/usr/include/python3.6m -c src/decoder.c -o build/temp.linux-x86_64-3.6/src/decoder.o
    In file included from src/decoder.h:15:0,
                     from src/decoder.c:12:
    src/config.h:18:10: fatal error: string.h: No such file or directory
     #include <string.h> /* memset, memcpy - can be easily self implemented for libc independency. */
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x65lz2va/distorm3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xevfg3zj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-x65lz2va/distorm3/
```

Can you help me how to install and user sflock.

**Comment by doomedraven** [comment]
you just missing python dev library, i would suggest you to start googling this errors it will save you a lot of time as they documented so many times, but more important all this is fixed in cape2.sh so it installs all the dependencies, you can't just pick 1 line from it without install the rest

**Comment by likescam** [comment]
Thanks for supporting me! I will try again!

**Comment by doomedraven** [comment]
Well script is for ubuntu 20 not 18, in your case it fails due to distorm,
if you read the error, remove it or google the errro, that simply ;)
