### ISSUE TITLE
Problem when installing pypiwin32/pywin32 and privoxy.service

### ISSUE THREAD

**Issue by likescam** [kevoreilly/CAPEv2#365]
Hello @doomedraven 

I have a problem when running cape2.sh base cape, during installing, it could not install pypiwin32/pywin32 and privoxy (on mongodb-server). So I need your support, I appreciate about your help!

**The privoxy log is:**
```
session closed for user root
ol server 91.189.89.199
ol server 162.159.200.123
ol server 119.28.230.190
ol server 209.58.185.100
TY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/bin/journalctl -xe
o:session): session opened for user root by cape(uid=0)
 ESCOD
Thg 11 18 03:37:37 cape ntpd[1053]: Soliciting pool server 2001:67c:1560:8003::c8
Thg 11 18 03:37:39 cape ntpd[1053]: Soliciting pool server 45.125.1.20
Thg 11 18 03:37:44 cape ntpd[1053]: Soliciting pool server 223.255.185.3
Thg 11 18 03:37:51 cape ntpd[1053]: Soliciting pool server 2001:470:19:301::123
Thg 11 18 03:38:03 cape sudo[8757]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/u
Thg 11 18 03:38:03 cape sudo[8757]: pam_unix(sudo:session): session opened for user root by cape(ui
Thg 11 18 03:38:04 cape sudo[8757]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:38:29 cape CommAmqpListene[7926]: [CCafException] AmqpCommon::[7926]: CommAmqpListener
Thg 11 18 03:38:32 cape sudo[8781]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/u
Thg 11 18 03:38:32 cape sudo[8781]: pam_unix(sudo:session): session opened for user root by cape(ui
Thg 11 18 03:38:38 cape systemd[1]: Reloading.
Thg 11 18 03:38:38 cape systemd[1]: Reloading.
Thg 11 18 03:38:38 cape systemd[1]: Reloading.
Thg 11 18 03:38:39 cape systemd[1]: Reloading.
Thg 11 18 03:38:41 cape ntpd[1053]: Soliciting pool server 91.189.94.4
Thg 11 18 03:38:41 cape kernel: perf: interrupt took too long (10207 > 10112), lowering kernel.perf
Thg 11 18 03:38:42 cape ntpd[1053]: Soliciting pool server 222.166.0.130
Thg 11 18 03:38:44 cape ntpd[1053]: Soliciting pool server 222.166.0.129
Thg 11 18 03:38:45 cape systemd[1]: Reloading.
Thg 11 18 03:38:48 cape ntpd[1053]: Soliciting pool server 45.124.64.93
Thg 11 18 03:38:48 cape sudo[8781]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:38:56 cape ntpd[1053]: Soliciting pool server 2606:4700:f1::1
Thg 11 18 03:39:11 cape sudo[10236]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/
Thg 11 18 03:39:11 cape sudo[10236]: pam_unix(sudo:session): session opened for user root by cape(u
Thg 11 18 03:39:11 cape sudo[10236]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:39:17 cape sudo[10239]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/
Thg 11 18 03:39:17 cape sudo[10239]: pam_unix(sudo:session): session opened for user root by cape(u
Thg 11 18 03:39:17 cape systemd[1]: Starting Privacy enhancing HTTP Proxy...
-- Subject: Unit privoxy.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit privoxy.service has begun starting up.
Thg 11 18 03:39:18 cape systemd[1]: privoxy.service: Control process exited, code=exited status=1
Thg 11 18 03:39:18 cape systemd[1]: privoxy.service: Failed with result 'exit-code'.
Thg 11 18 03:39:18 cape systemd[1]: Failed to start Privacy enhancing HTTP Proxy.
-- Subject: Unit privoxy.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit privoxy.service has failed.
-- 
-- The result is RESULT.
Thg 11 18 03:39:18 cape sudo[10239]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:39:48 cape ntpd[1053]: Soliciting pool server 91.189.89.199
Thg 11 18 03:39:48 cape ntpd[1053]: Soliciting pool server 162.159.200.123
Thg 11 18 03:39:49 cape ntpd[1053]: Soliciting pool server 119.28.230.190
Thg 11 18 03:39:54 cape ntpd[1053]: Soliciting pool server 209.58.185.100
Thg 11 18 03:39:58 cape sudo[10253]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/
Thg 11 18 03:39:58 cape sudo[10253]: pam_unix(sudo:session): session opened for user root by cape(u
 ESCOD
Thg 11 18 03:37:37 cape ntpd[1053]: Soliciting pool server 2001:67c:1560:8003::c8
Thg 11 18 03:37:39 cape ntpd[1053]: Soliciting pool server 45.125.1.20
Thg 11 18 03:37:44 cape ntpd[1053]: Soliciting pool server 223.255.185.3
Thg 11 18 03:37:51 cape ntpd[1053]: Soliciting pool server 2001:470:19:301::123
Thg 11 18 03:38:03 cape sudo[8757]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/u
Thg 11 18 03:38:03 cape sudo[8757]: pam_unix(sudo:session): session opened for user root by cape(ui
Thg 11 18 03:38:04 cape sudo[8757]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:38:29 cape CommAmqpListene[7926]: [CCafException] AmqpCommon::[7926]: CommAmqpListener
Thg 11 18 03:38:32 cape sudo[8781]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/u
Thg 11 18 03:38:32 cape sudo[8781]: pam_unix(sudo:session): session opened for user root by cape(ui
Thg 11 18 03:38:38 cape systemd[1]: Reloading.
Thg 11 18 03:38:38 cape systemd[1]: Reloading.
Thg 11 18 03:38:38 cape systemd[1]: Reloading.
Thg 11 18 03:38:39 cape systemd[1]: Reloading.
Thg 11 18 03:38:41 cape ntpd[1053]: Soliciting pool server 91.189.94.4
Thg 11 18 03:38:41 cape kernel: perf: interrupt took too long (10207 > 10112), lowering kernel.perf
Thg 11 18 03:38:42 cape ntpd[1053]: Soliciting pool server 222.166.0.130
Thg 11 18 03:38:44 cape ntpd[1053]: Soliciting pool server 222.166.0.129
Thg 11 18 03:38:45 cape systemd[1]: Reloading.
Thg 11 18 03:38:48 cape ntpd[1053]: Soliciting pool server 45.124.64.93
Thg 11 18 03:38:48 cape sudo[8781]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:38:56 cape ntpd[1053]: Soliciting pool server 2606:4700:f1::1
Thg 11 18 03:39:11 cape sudo[10236]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/
Thg 11 18 03:39:11 cape sudo[10236]: pam_unix(sudo:session): session opened for user root by cape(u
Thg 11 18 03:39:11 cape sudo[10236]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:39:17 cape sudo[10239]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/
Thg 11 18 03:39:17 cape sudo[10239]: pam_unix(sudo:session): session opened for user root by cape(u
Thg 11 18 03:39:17 cape systemd[1]: Starting Privacy enhancing HTTP Proxy...
-- Subject: Unit privoxy.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit privoxy.service has begun starting up.
Thg 11 18 03:39:18 cape systemd[1]: privoxy.service: Control process exited, code=exited status=1
Thg 11 18 03:39:18 cape systemd[1]: privoxy.service: Failed with result 'exit-code'.
Thg 11 18 03:39:18 cape systemd[1]: Failed to start Privacy enhancing HTTP Proxy.
-- Subject: Unit privoxy.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit privoxy.service has failed.
-- 
-- The result is RESULT.
Thg 11 18 03:39:18 cape sudo[10239]: pam_unix(sudo:session): session closed for user root
Thg 11 18 03:39:48 cape ntpd[1053]: Soliciting pool server 91.189.89.199
Thg 11 18 03:39:48 cape ntpd[1053]: Soliciting pool server 162.159.200.123
Thg 11 18 03:39:49 cape ntpd[1053]: Soliciting pool server 119.28.230.190
Thg 11 18 03:39:54 cape ntpd[1053]: Soliciting pool server 209.58.185.100
Thg 11 18 03:39:58 cape sudo[10253]:     cape : TTY=pts/1 ; PWD=/opt/CAPEv2 ; USER=root ; COMMAND=/
Thg 11 18 03:39:58 cape sudo[10253]: pam_unix(sudo:session): session opened for user root by cape(u
```
**The pypiwin32 install log is:**

```
sudo pip3 install pypiwin32
The directory '/home/cape/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cape/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pypiwin32
  Downloading https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting pywin32>=223 (from pypiwin32)
  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32)
```

**I tried to run cuckoo.py and it also have error bellow:**
```
cape@cape:/opt/CAPEv2$ sudo python3 cuckoo.py 

  eeee e   e eeee e   e  eeeee eeeee
  8  8 8   8 8  8 8   8  8  88 8  88
  8e   8e  8 8e   8eee8e 8   8 8   8
  88   88  8 88   88   8 8   8 8   8
  88e8 88ee8 88e8 88   8 8eee8 8eee8

 Cuckoo Sandbox 2.1-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

pywin32 is not installed (only is required if you want to use MS Excel)
2020-11-18 10:21:00,999 [root] CRITICAL: CuckooStartupError: The rooter is required but it is either not running or it has been configured to a different Unix socket path. (In order to disable the use of rooter, please set route and internet to none in cuckoo.conf and enabled to no in routing.conf).
```

**Comment by doomedraven** [comment]
will pr it later, `python3 utils/rooter.py -h or systemctl status cape-rooter` will be added to that error msg
that fixes your problem?

**Comment by doomedraven** [comment]
closing as responded, did that solved your issues?

**Comment by likescam** [comment]
> will pr it later, `python3 utils/rooter.py -h or systemctl status cape-rooter` will be added to that error msg
> that fixes your problem?

Thanks @doomedraven , I also fix rooter problem by running it on another terminal, and running cuckoo.py ok. But another problem when I run web interface, I dont know why I can not start web :(

```
cape@cape:/opt/CAPEv2/web$ python3 manage.py runserver 0.0.0.0:8080
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/CAPEv2/web/web/settings.py", line 39, in <module>
    WEB_AUTHENTICATION = web_cfg.web_auth.get("enabled", False)
AttributeError: 'Config' object has no attribute 'web_auth'
```

**Comment by likescam** [comment]
> > will pr it later, `python3 utils/rooter.py -h or systemctl status cape-rooter` will be added to that error msg
> > that fixes your problem?
> 
> Thanks @doomedraven , I also fix rooter problem by running it on another terminal, and running cuckoo.py ok. But another problem when I run web interface, I dont know why I can not start web :(
> 
> ```
> cape@cape:/opt/CAPEv2/web$sudo python3 manage.py runserver 0.0.0.0:8080
> Traceback (most recent call last):
>   File "manage.py", line 15, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 345, in execute
>     settings.INSTALLED_APPS
>   File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 83, in __getattr__
>     self._setup(name)
>   File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 70, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 177, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/opt/CAPEv2/web/web/settings.py", line 39, in <module>
>     WEB_AUTHENTICATION = web_cfg.web_auth.get("enabled", False)
> AttributeError: 'Config' object has no attribute 'web_auth'
> ```

I solved this problem with about error by restarting my Ubuntu.
Thank you so much! maybe next time will ask you more and more and hope you support me again :D

**Comment by doomedraven** [comment]
well that error should be related to missed section on your side https://github.com/kevoreilly/CAPEv2/blob/master/conf/web.conf#L2
