### ISSUE TITLE
Error running malheur

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#389]
I am running malheur and mitre att&ck and seeing the follwing errors in the process log file

> 2020-12-18 18:36:09,635 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Malheur":
Traceback (most recent call last):
File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 794, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/malheur.py", line 156, in run
    outputfile = os.path.join(basedir, "malheur.txt." + hashlib.md5(str(random.random())).hexdigest())
TypeError: Unicode-objects must be encoded before hashing
2020-12-18 18:36:11,012 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MITRE_TTPS":
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 794, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/mitre.py", line 12, in run
    for technique in self.mitre.enterprise.techniques:
  File "/usr/local/lib/python3.8/dist-packages/pyattck/attck.py", line 191, in enterprise
    self.__load_data()
  File "/usr/local/lib/python3.8/dist-packages/pyattck/attck.py", line 379, in __load_data
    Attck.__ENTERPRISE_GENERATED_DATA_JSON = self.__datasets.generated_attck_data(force=force)
  File "/usr/local/lib/python3.8/dist-packages/pyattck/datasets.py", line 84, in generated_attck_data
    input('press')
EOFError: EOF when reading a line

What went wrong and how can I solve this problem ?

**Comment by dforce** [comment]
The problem with mitre att&ck is solved due to the solution mentioned in [https://github.com/kevoreilly/CAPEv2/issues/383](url)

The only problem is still malheur.

> 020-12-18 18:36:09,635 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Malheur":
Traceback (most recent call last):
File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 794, in process
current.run(self.results)
File "/opt/CAPEv2/utils/../modules/reporting/malheur.py", line 156, in run
outputfile = os.path.join(basedir, "malheur.txt." + hashlib.md5(str(random.random())).hexdigest())
TypeError: Unicode-objects must be encoded before hashing

**Comment by doomedraven** [comment]
malheur should be removed, that doesn't have good performance on huge sample set so everyone was lazy to remove it, forget about that, is useless

**Comment by doomedraven** [comment]
about pyattk you using buggy version that was reported already do search in issues, upgrade library see requirements.txt

**Comment by doomedraven** [comment]
FYI next time removing the issue template and posting to wrong issue to wrong repo will be autoclosed
