### ISSUE TITLE
Python errors since upgrade to the latest code (web.err.log)

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#417]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Since the upgraded to the latest code, I see Python errors in web.err.log...

# Current Behavior

It seems to impact the retrieval of analysis results via the API.

# Failure Information (for bugs)

1st error:

```
[21/Jan/2021 16:23:46] "GET /api/tasks/get/pcap/936/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/usr/lib/python3.6/wsgiref/util.py", line 30, in __next__
    data = self.filelike.read(self.blksize)
AttributeError: 'str' object has no attribute 'read'
```

Second error:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
self.handle_error()
File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 119, in handle_error
super().handle_error()
File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
self.finish_response()
File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
self.write(data)
File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
self.send_headers()
File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
if not self.origin_server or self.client_is_modern():
File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
self.handle()
File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 172, in handle
self.handle_one_request()
File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
handler.run(self.server.get_app())
File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
self.close()
File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

## Steps to Reproduce

Just submit a sample...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       |  35fb4493c274b80a26e6fcbd04f9c5977f8c6c93
| OS version       | Ubuntu 18.04.4 LTS

**Comment by doomedraven** [comment]
thank you @xme  just pushed fix
