### ISSUE TITLE
ModuleNotFoundError: No module named 'ratelimit'

### ISSUE THREAD

**Issue by dforce** [kevoreilly/CAPEv2#426]
Hi,

Just did a fresh install of CAPEv2 on Ubuntu.
Everything went fine but when running the following command
`python3 manage.py migrate`

I receive the following error 
`Traceback (most recent call last):
  File "manage.py", line 15, in <module>
     execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ratelimit'`

I have checked and django-ratelimit is installed.

What could be the problem ?

Thanks

**Comment by ClaudioWayne** [comment]
try reinstall django-ratelimit
(sudo) pip3 uninstall django-ratelimit
pip3 install -U django-ratelimit

**Comment by dforce** [comment]
Thanks that solved the problem.

**Comment by doomedraven** [comment]
ok pushed imports fix as that wasn't updated
