### ISSUE TITLE
File Resubmission error 'bytes-like object is required, not str'

### ISSUE THREAD

**Issue by benweber2** [kevoreilly/CAPEv2#5]
# Expected Behavior
Resubmitting a file from an analysis page would restart an analysis

# Current Behavior
After selecting 'Resubmit Sample' on the analysis page and Selecting 'Analyze' on the Submission page, I receive a django traceback error

# Failure Information (for bugs)

Log in web.err.log:

[04/Jan/2020 15:13:21] "GET /submit/resubmit/bc154f8a0b83d7ce9a4e18929dcde5e16730d044af583feac1c35bae7b78c0f4/ HTTP/1.0" 200 39487
Internal Server Error: /submit/resubmit/bc154f8a0b83d7ce9a4e18929dcde5e16730d044af583feac1c35bae7b78c0f4/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/CAPEv2/web/submission/views.py", line 253, in index
    clock, custom, memory, enforce_timeout, referrer, tags, orig_options, task_machines, static)
  File "/opt/CAPEv2/web/../lib/cuckoo/common/web_utils.py", line 191, in download_file
    orig_options, timeout, enforce_timeout = recon(filename, orig_options, timeout, enforce_timeout)
  File "/opt/CAPEv2/web/../lib/cuckoo/common/web_utils.py", line 113, in recon
    if "name" in filename:
TypeError: a bytes-like object is required, not 'str'
[04/Jan/2020 15:13:24] "POST /submit/resubmit/bc154f8a0b83d7ce9a4e18929dcde5e16730d044af583feac1c35bae7b78c0f4/ HTTP/1.0" 500 95566

## Steps to Reproduce

Step 1: Submit a file for analysis.
Step 2: After analysis is complete, Select 'Resubmit Sample' on the analysis page.
Step 3: On the Submission page, select 'Analyze'
Step 4: Receive error

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 29108496869efeef9385b57f008cf4779083f1a8
| OS version       | Ubuntu 18.04.3 LTS

**Comment by doomedraven** [comment]
thanks, weird i though that was fixed, i will check that later

**Comment by benweber2** [comment]
No problem!  Let me know if there is anything else I can provide.

**Comment by doomedraven** [comment]
fixed, somehow i removed the fix from repo, can you test it again please?

**Comment by benweber2** [comment]
Confirmed fixed.  Thanks for the quick turn around!

Love the project!

**Comment by doomedraven** [comment]
you are welcome, let us know if you find more, or have some suggestions/feature reqs
