### ISSUE TITLE
System stops working properly after analyzing some samples that create infinite processes

### ISSUE THREAD

**Issue by labs71** [kevoreilly/CAPEv2#509]
OS: Ubuntu 18.04.5 LTS
Last commit: 3286fb66736d2687dae9570d6d494b2c5ee56720

Description
=========

When analyzing samples that create a lot of processes, like :

7e401514e4e66a34f96afb44d4bcbe912d403905214ba3b39e17833326d1652c 

The system cannot properly handle the logging when a bunch of them are analyzed at the same time and it stops working. The current analysis fails and it also affects other further analysis.

How to reproduce
=============

Just analyze the above sample multiple times in parallel, in our case, it happens with 4 analysis at the same time. Our specifications are:

16vCore: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
RAM: 32gb

I have to say there is no issue in performance, is like it's trying to log too much when that stuff happens.

Expected Behavior
==============

Generate proper reports for all of them, or at least they are 'cut' after logging N processes.

Error message
===========

When the first analysis fails and all the processes need to be logged, there is a cascade error like the following one:

```
2021-06-08 13:14:40,769 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_4 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:40,911 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_5 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:41,271 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_2 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:41,274 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_1 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:41,635 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_3 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:41,777 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_4 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:41,918 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_5 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:42,281 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_1 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:42,281 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_2 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:42,642 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_3 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:42,784 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_4 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:42,938 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_5 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:43,290 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_2 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:43,292 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_1 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:43,649 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_3 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:43,793 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_4 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:43,945 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_5 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:44,300 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_2 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:44,302 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_1 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:44,656 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_3 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:44,799 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_4 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:44,951 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_5 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:45,310 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_2 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:45,314 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_1 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:45,664 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_3 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:45,807 [lib.cuckoo.core.guest] WARNING: Virtual Machine: Win7x64_cape_1G_4 /status failed. This can indicate the guest losing network connectivity
2021-06-08 13:14:45,955 [lib.cuckoo.core.guest] INFO: Win7x64_cape_1G_5: end of analysis reached!
2021-06-08 13:14:45,967 [lib.cuckoo.core.scheduler] ERROR: Cannot connect to libvirt
Traceback (most recent call last):
  File "/capev2_working_directory/lib/cuckoo/common/abstracts.py", line 537, in _connect
    return libvirt.open(self.dsn)
  File "/usr/local/lib/python3.6/dist-packages/libvirt.py", line 277, in open
libvirt.libvirtError: Failed to create socket: Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/capev2_working_directory/lib/cuckoo/core/scheduler.py", line 345, in launch_analysis
    machinery.dump_memory(self.machine.label, dump_path)
  File "/capev2_working_directory/lib/cuckoo/common/abstracts.py", line 473, in dump_memory
    conn = self._connect(label)
  File "/capev2_working_directory/lib/cuckoo/common/abstracts.py", line 539, in _connect
    raise CuckooMachineError("Cannot connect to libvirt")
lib.cuckoo.common.exceptions.CuckooMachineError: Cannot connect to libvirt
2021-06-08 13:14:45,968 [lib.cuckoo.core.scheduler] WARNING: Task #10161: Unable to stop machine Windows7_x64_cape5-1G: Cannot connect to libvirt
```

We already tried increasing max files opened.

**Comment by doomedraven** [comment]
hello, thank you for report, that is your OS limits problem, google for `Too many open files`
