### ISSUE TITLE
Issues in installing requirements.txt dependencies

### ISSUE THREAD

**Issue by javvylx** [kevoreilly/CAPEv2#515]
Hi CAPEv2 Community, we are currently a group of students working on a malware analysis project, which requires setting up of CAPEv2 Sandbox. We have identified an issue upon setting up CAPEv2 as of today. However, we have identify the cause of it, which we have stated down below.

# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior
Python dependencies required for CAPEv2 to function properly should be installed properly when installing using [cape2.sh](https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh)

# Current Behavior
After using cape2.sh to install and using 'sudo python3 manage.py migrate', there will be alot of missing dependencies.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. sudo apt-get update && sudo apt-get upgrade -y && sudo reboot
2. mkdir capesandbox && cd capesandbox
3. sudo wget https://raw.githubusercontent.com/doomedraven/Tools/master/Sandbox/cape2.sh
4. sudo nano http://cape2.sh
5. sudo chmod a+x http://cape2.sh
6. sudo ./cape2.sh base cape | tee cape2_result.txt
7. cd /opt/CAPEv2/web
8. sudo python3 http://manage.py migrate

## Failure Logs

After running Step 8, a prompt came out saying no module named 'django' error. Even after doing a pip install django, it still says other dependencies need to be installed.

Looking back at the cape2_result.txt, it was found out that there was an error saying: 
Collecting git+https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP.git
  Cloning https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP.git to /tmp/pip-req-build-c23xjssf
  Running command git clone -q https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP.git /tmp/pip-req-build-c23xjssf
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-c23xjssf/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-c23xjssf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-c23xjssf/pip-egg-info
         cwd: /tmp/pip-req-build-c23xjssf/
    Complete output (37 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-c23xjssf/setup.py", line 8, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-req-build-c23xjssf/mwcp/__init__.py", line 11, in <module>
        from mwcp.file_object import FileObject
      File "/tmp/pip-req-build-c23xjssf/mwcp/file_object.py", line 18, in <module>
        from mwcp import metadata
      File "/tmp/pip-req-build-c23xjssf/mwcp/metadata.py", line 20, in <module>
        import cattr
    ModuleNotFoundError: No module named 'cattr'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Temporary Solution

1. Line 37 of /opt/CAPEv2/requirements.txt 
2. git+github.com/Defense-Cyber-Crime-Center/DC3-MWCP.git
3. Using this latest release will result in error causing the rest of the dependencies to be skipped. 
4. Use this for temp fix-> git+github.com/Defense-Cyber-Crime-Center/DC3-MWCP.git@3.2.1

Thank you!

From, 
@Vangeance666 @jrdtan @javvylx

**Comment by ClaudioWayne** [comment]
With the new release 3.3.0 they added some new install requirements:

anytree
attrs>=20.3.0
cattrs
pandas
pytest>=6.0.0
pytest-console-scripts
pytest-xdist
tabulate[widechars]

they also changed some objects and attributes that may need additional checks

https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/master/CHANGELOG.md

**Comment by doomedraven** [comment]
Hello, thanks for headups, as you might see that MWCP is 3rd part dependency, and those 3rd part dependencies is always a headache, especially MISP integration, as we are not owners of those projects we trying to make huge effort on bring you solution, but once we got sandbox working, we don't check each new release of those libs, is why we started to hardcode versions of those  libraries

in production we use 
```
 pip3 freeze|grep mwcp
mwcp==3.0.0
```

the best way to solve it is not hardcore obviosly this, but report to the proper repo to fix that
but it can be also fixed by installing their missed deps by hand


__IMPORTANT__ i see you run manage.py as root, __NEVER EVER__ run any thing from CAPE as root, apart of rooter.py

**Comment by doomedraven** [comment]
and i was able to upgrade that with no problems
```
Found existing installation: mwcp 3.0.0
    Uninstalling mwcp-3.0.0:
      Successfully uninstalled mwcp-3.0.0
Successfully installed  mwcp-3.3.0
```

**Comment by doomedraven** [comment]
i have changed the requirements to install it from pypi instead of git, let us know if you find any problem, but be aware, running cape as  root will give you tons of permission problems and other random problems all around, is why it should be executed by cape user as our systemd services does, to use systemd now you have to fix all the permissions inside of the `/tmp` and `/opt/CAPEv2`, for that you can use `chown cape:cape PATH_HERE -R`

**Comment by doomedraven** [comment]
so i have details on this problem

it looks like cattrs is using `get_args` that was introduced in python 3.8 https://docs.python.org/3.8/library/typing.html
most ubuntu 20 is using 3.6,

```
cattrs==1.1.0
```
```
>>> import mwcp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mwcp/__init__.py", line 11, in <module>
    from mwcp.file_object import FileObject
  File "/usr/local/lib/python3.6/dist-packages/mwcp/file_object.py", line 18, in <module>
    from mwcp import metadata
  File "/usr/local/lib/python3.6/dist-packages/mwcp/metadata.py", line 20, in <module>
    import cattr
  File "/usr/local/lib/python3.6/dist-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/usr/local/lib/python3.6/dist-packages/cattr/converters.py", line 18, in <module>
    from ._compat import (
  File "/usr/local/lib/python3.6/dist-packages/cattr/_compat.py", line 31, in <module>
    from typing import get_args, get_origin  # NOQA
ImportError: cannot import name 'get_args'
```

so yes till 3.8 python we should use mwcp 3.2.1
