### ISSUE TITLE
Failed to run the processing module "Sysmon" list index out of range

### ISSUE THREAD

**Issue by YungBinary** [kevoreilly/CAPEv2#624]
## Failure Logs

```
2021-11-13 19:26:13,947 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Sysmon":
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 353, in process
    data = current.run()
  File "/opt/CAPEv2/utils/../modules/processing/sysmon.py", line 56, in run
    lastlog = lastlog[-1]
IndexError: list index out of range
```

**Comment by doomedraven** [comment]
pushed fix, sysmon is community module and not core, that means we don't use that so it should be maintained by community
