### ISSUE TITLE
issues with the agent

### ISSUE THREAD

**Issue by VVelox** [kevoreilly/CAPEv2#679]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I checked the documentation and found no answer
- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

It fires up the VM and begins talking to the agent.

# Current Behavior

What is the current behavior?

VM starts and is immediately stopped after it and the agent can't communicate.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

See the information logs below.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1: Create a windows VM with all the required bits installed.
2: Plop the newest agent.py on there.
3: Start the agent running and save the snapshot.
4: Stop the VM.
5: Submit something to be ran on that VM.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | 40a7d4b278292dbcecf532b579c706a6f3cbcadd
| Guest OS version       | Windows 10
| Host OS version | Ubuntu 20.04.3 LTS

## Failure Logs

Please include any relevant log snippets or files here.

```
2021-12-28 16:21:21,154 [lib.cuckoo.core.scheduler] INFO: Task #12: Starting analysis of FILE '/home/zane/pafish64.exe'
2021-12-28 16:21:21,167 [lib.cuckoo.core.scheduler] INFO: Task #12: File already exists at '/opt/CAPEv2/storage/binaries/ff24b9da6cddd77f8c19169134eb054130567825eee1008b5a32244e1028e76f'
2021-12-28 16:21:21,177 [lib.cuckoo.core.scheduler] INFO: Task #12: acquired machine win10-2 (label=win10-2, arch=x64, platform=windows)
2021-12-28 16:21:27,336 [lib.cuckoo.core.scheduler] WARNING: Unknown network routing destination specified, ignoring routing for this analysis: 0
2021-12-28 16:21:27,337 [lib.cuckoo.core.scheduler] INFO: Enabled route '0'
2021-12-28 16:21:27,358 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 7383 (interface=virbr0, host=192.168.122.71, dump path=/opt/CAPEv2/storage/analyses/12/dump.pcap)
2021-12-28 16:21:27,383 [lib.cuckoo.core.guest] INFO: Starting analysis #12 on guest (id=win10-2, ip=192.168.122.71)
2021-12-28 16:21:27,399 [lib.cuckoo.core.scheduler] ERROR: CAPE Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.10) and notify us if the issue persists
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 111, in get
    r = session.get(url, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 345, in launch_analysis
    guest.start_analysis(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 254, in start_analysis
    r = self.get("/", do_raise=False)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 113, in get
    raise CuckooGuestError(
lib.cuckoo.common.exceptions.CuckooGuestError: CAPE Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.10) and notify us if the issue persists
2021-12-28 16:21:27,871 [lib.cuckoo.core.scheduler] INFO: Task #12: analysis procedure completed
```

On a strange note if I try a version from a few commits ago, I get the following error. Which is strange as that is very much not the file being submitted.

```
2021-12-28 15:10:09,166 [lib.cuckoo.core.guest] INFO: Starting analysis #15 on guest (id=win10-1, ip=192.168.122.70)
2021-12-28 15:10:09,179 [lib.cuckoo.core.guest] INFO: Guest is running CAPE Agent 0.11 (id=win10-1, ip=192.168.122.70)
2021-12-28 15:10:10,704 [lib.cuckoo.core.guest] INFO: Uploading support files to guest (id=win10-1, ip=192.168.122.70)
2021-12-28 15:10:11,507 [lib.cuckoo.core.scheduler] ERROR: Task #15: Failure in AnalysisManager.run: [Errno 13] Permission denied: '/home/zane/.bash_history'
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 449, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 360, in launch_analysis
    guest.start_analysis(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 315, in start_analysis
    self.upload_support_files(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 234, in upload_support_files
    files = {"file": (xf, open(target, "rb"))}
PermissionError: [Errno 13] Permission denied: '/home/zane/.bash_history'
```

EDIT: After a bit more testing it appears if I point submit at a file, it will start trying to upload everything in that directory, not just the specified file. ... ```sudo python3 /opt/CAPEv2/utils/submit.py --machine win10-2 --platform windows /home/zane/pafish64.exe``` will result in the bug above, but ```sudo python3 /opt/CAPEv2/utils/submit.py --machine win10-2 /home/zane/empty/pafish64.exe``` will work, once I plop the exe into a directory by it's self.

**Comment by doomedraven** [comment]
about agent did it work before?
about submit, so agent works with submit from specific folder as that part isn't clear to me

**Comment by TheMythologist** [comment]
I think he means that the error is in `utils/submit.py`, because using `utils/submit.py` to submit a sample will cause CAPE to upload everything in the same directory as the specified file.

**Comment by VVelox** [comment]
> I think he means that the error is in `utils/submit.py`, because using `utils/submit.py` to submit a sample will cause CAPE to upload everything in the same directory as the specified file.
> 
> Just to double-check, do you get this error when submitting this sample through the web UI?

Yup! That is correct.

**Comment by VVelox** [comment]
> about agent did it work before?

Currently using c54436dba11c56c879edf7583e2ce967d306dbaf from June and it works fine. Going to try the second to last and see how that goes. Grabbed one that far back after bashing my head against the wall about why it is trying to grab .bash_history, before realizing it is trying to submit the entire directory.

> about submit, so agent works with submit from specific folder as that part isn't clear to me

It works, just submits everything in that folder. I don't think that is the intended action, from the looks of --help and docs for submission.

**Comment by VVelox** [comment]
Apparently 5b4ebbbbfe22ef7d4b83a3d248454a907c4a0c63, second to latest, is the last agent that I can get to work. The commit on the 21st appears to be breaking it.

If there is anything I can do to help trouble shoot, please let me know.

**Comment by doomedraven** [comment]
If ypu have windows with python just run agent. Py but you need to disable
stringio or something like that that redirects output

**Comment by doomedraven** [comment]
@VVelox found the issue is strange and not make too much sense, this change doesn't work so restoring old if make it works
```
#if "client_ip" in state and request.client_ip != state["client_ip"]:
if state.get("client_ip") != request.client_ip:
```

pushed, thanks

**Comment by doomedraven** [comment]
reopen if still happens

**Comment by VVelox** [comment]
@doomedraven Awesome. Confirmed that the latest one works. Thanks!

**Comment by doomedraven** [comment]
Thanks for confirmation
