### ISSUE TITLE
I want to update the Cape, but I get the database error.

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#698]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

I want to update the Cape.

# Current Behavior

I want to update the one with commit ID dd0bf29c7f0de1f82b5ccb02e2803eb46579bdb3 to new one
However, I get the following database error.（I deleted the task in cleaners.py and then updated it）

```
DB schema version mismatch: found 6ab863a3b510, expected 6dc79a3ee6e4. Try to apply all migrations
cd utils/db_migration/ && alembic upgrade head
```
I executed `cd utils/db_migration/ && alembic upgrade head` according to the error, but the following error occurs
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6ab863a3b510 -> 703266a6bbc5, 2.3.1_square_hammer
Traceback (most recent call last):
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    self.dialect.do_execute(
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "alter": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/venv-cape/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/config.py", line 540, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/config.py", line 534, in main
    self.run_cmd(cfg, options)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/config.py", line 511, in run_cmd
    fn(
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/util/compat.py", line 177, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./env.py", line 69, in <module>
    run_migrations_online()
  File "./env.py", line 61, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/runtime/migration.py", line 362, in run_migrations
    step.migration_fn(**kw)
  File "/opt/CAPEv2/utils/db_migration/versions/2_3_1_square_hammer.py", line 21, in upgrade
    op.execute("ALTER TABLE tasks alter status drop default")
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/operations/ops.py", line 2223, in execute
    return operations.invoke(op)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 175, in execute_sql
    operations.migration_context.impl.execute(
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/ddl/impl.py", line 137, in execute
    self._exec(sql, execution_options)
  File "/root/venv-cape/lib/python3.8/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1201, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1390, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    self._handle_dbapi_exception(
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    util.raise_(
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    self.dialect.do_execute(
  File "/root/venv-cape/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "alter": syntax error
[SQL: ALTER TABLE tasks alter status drop default]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

## Steps to Reproduce

1. clean a task with cleaners.py
2. `git pull` and update the Cape
3. `python3 cuckoo.py` -d but database error occurs

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | dd0bf29c7f0de1f82b5ccb02e2803eb46579bdb3
| OS version       | ubuntu 20.04.1 LTS installed Python 3.8.5

**Comment by ai-suzuki** [comment]
I am always grateful for your help.
I set postgresql in `connection =` and ran `cd utils/db_migration/ && alembic upgrade head`  and it was updated successfully.
By the way, when updating from my environment, I installed the following additionally.
```
#sudo apt-get install p7zip-full lzip rar unace-nonfree cabextract
#pip3 install SFlock2
#pip3 install django-ratelimit
```
