### ISSUE TITLE
Can start analysis: Invalid argument

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#76]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Failure Information (for bugs)

LOG
2020-02-25 06:59:50,691 [root] DEBUG: Starting analyzer from: C:\tmpxxfk82pv
2020-02-25 06:59:50,835 [root] DEBUG: Storing results at: C:\NzOOhPQkuv
2020-02-25 06:59:50,938 [root] DEBUG: Pipe server name: \\.\PIPE\QTeLLjd
2020-02-25 06:59:50,938 [root] DEBUG: Python path: C:\Users\IEUser\AppData\Local\Programs\Python\Python38-32
2020-02-25 06:59:50,938 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2020-02-25 06:59:52,408 [root] ERROR: Traceback (most recent call last):
  File "C:/tmpxxfk82pv/analyzer.py", line 1572, in <module>
    success = analyzer.run()
  File "C:/tmpxxfk82pv/analyzer.py", line 350, in run
    package = choose_package(self.config.file_type, self.config.file_name, self.config.exports, self.target)
  File "C:\tmpxxfk82pv\lib\core\packages.py", line 20, in choose_package
    file_content = open(target, "rb").read()
OSError: [Errno 22] Invalid argument: 'C:\\Users\\IEUser\\AppData\\Local\\Temp\\xxx.ps1'
Traceback (most recent call last):
  File "C:/tmpxxfk82pv/analyzer.py", line 1572, in <module>
    success = analyzer.run()
  File "C:/tmpxxfk82pv/analyzer.py", line 350, in run
    package = choose_package(self.config.file_type, self.config.file_name, self.config.exports, self.target)
  File "C:\tmpxxfk82pv\lib\core\packages.py", line 20, in choose_package
    file_content = open(target, "rb").read()
OSError: [Errno 22] Invalid argument: 'C:\\Users\\IEUser\\AppData\\Local\\Temp\\xxx.ps1'
2020-02-25 06:59:52,476 [root] WARNING: Folder at path "C:\NzOOhPQkuv\debugger" does not exist, skip.
2020-02-25 06:59:52,476 [root] INFO: Analysis completed.

I don't know why they're escaped '\', is it normal?

**Comment by doomedraven** [comment]
hello, thanks for feedback, could you point me where it escapes '' ? i doubt that is normal, does this happens to all powershell scripts? i will need to test it

**Comment by xme** [comment]
Ok, my bad... There was an issue with the sandbox and Windows Defender was not disabled (it was before)... So, it removed the file while the analysis was running. Sorry for this... :(

But, I've another one no:

2020-02-25 12:31:16,541 [root] INFO: Analyzer: Package modules.packages.exe does not specify a DLL option
2020-02-25 12:31:16,541 [root] INFO: Analyzer: Package modules.packages.exe does not specify a DLL_64 option
2020-02-25 12:31:16,588 [lib.api.process] INFO: Successfully executed process from path "C:\Users\IEUser\AppData\Local\Temp\xxx.exe" with arguments "" with pid 1652
2020-02-25 12:31:16,604 [root] ERROR: Traceback (most recent call last):
  File "C:/tmph36vr9vs/analyzer.py", line 509, in run
    pids = pack.start(self.target)
  File "C:\tmph36vr9vs\modules\packages\exe.py", line 37, in start
    return self.execute(path, args, path)
  File "C:\tmph36vr9vs\lib\common\abstracts.py", line 144, in execute
    p.inject(INJECT_QUEUEUSERAPC, interest)
  File "C:\tmph36vr9vs\lib\api\process.py", line 569, in inject
    self.write_monitor_config(interest, nosleepskip)
  File "C:\tmph36vr9vs\lib\api\process.py", line 485, in write_monitor_config
    with open(config_path, "w", encoding="utf-8") as config:
PermissionError: [Errno 13] Permission denied: 'C:\\1652.ini'

What is this ini file?

**Comment by doomedraven** [comment]
i think that is new windows config for windows10 support, not really sure, @kevoreilly what is that?

**Comment by xme** [comment]
Ok, found again the problem... Event if the local user was "administrator", he has no rights to write to the root of C:... I switched from a 'startup' folder setup to a scheduled task that runs with "all privileges"... It's ok now! My sandbox seems to be running fine now... (Yes, my sandbox is Win10 64bits)

**Comment by doomedraven** [comment]
ah yes on windows 10 is different, we will need to add note about that, so all fixed?

**Comment by doomedraven** [comment]
reopen this if you need any other help

**Comment by kevoreilly** [comment]
Hi guys - sorry to be slow to respond on this. xme I am glad you found a work-around for this issue, Win10 does not like the inis in the root of C: and it's very untidy, so I've moved the monitor configs to the same directory as the monitors :)

https://github.com/kevoreilly/CAPEv2/commit/d32158d8ff76d582ae82c8f9825bb5892d778384
