### ISSUE TITLE
JS analysis failing with FileNotFound error (missing upload file)

### ISSUE THREAD

**Issue by ag-michael** [kevoreilly/CAPEv2#774]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I'm have read all configs with all optional parts

# Expected Behavior

Uploading a JS file for static analysis should work.

# Current Behavior

What is the current behavior?

FileNotFound error, the directory for the upload exists, but the file does not.
This happens with Unpacker_js and js_antivm, the only thing consistent is that the analysis is for JS files.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Logs show this:
```
Feb 21 03:27:25 cuckoo python3.8[17365]: 2022-02-21 03:27:25,898 [lib.cuckoo.core.scheduler] DEBUG: Task #118: Processing task
Feb 21 03:27:25 cuckoo python3.8[17365]: 2022-02-21 03:27:25,900 [lib.cuckoo.core.scheduler] INFO: Task #118: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_fdjr89sx/malware.js'
Feb 21 03:27:25 cuckoo python3.8[17365]: 2022-02-21 03:27:25,900 [lib.cuckoo.core.scheduler] ERROR: Task #118: Failure in AnalysisManager.run: [Errno 2] No such file or directory: '/tmp/cuckoo-tmp/upload_fdjr89sx/malware.js'
Feb 21 03:27:25 cuckoo python3.8[17365]: Traceback (most recent call last):
Feb 21 03:27:25 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/core/scheduler.py", line 434, in run
Feb 21 03:27:25 cuckoo python3.8[17365]:     success = self.launch_analysis()
Feb 21 03:27:25 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/core/scheduler.py", line 293, in launch_analysis
Feb 21 03:27:25 cuckoo python3.8[17365]:     category_early_escape = self.category_checks()
Feb 21 03:27:25 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/core/scheduler.py", line 247, in category_checks
Feb 21 03:27:25 cuckoo python3.8[17365]:     sha256 = File(self.task.target).get_sha256()
Feb 21 03:27:25 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/common/objects.py", line 362, in get_sha256
Feb 21 03:27:25 cuckoo python3.8[17365]:     self.calc_hashes()
Feb 21 03:27:25 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/common/objects.py", line 294, in calc_hashes
Feb 21 03:27:25 cuckoo python3.8[17365]:     for chunk in self.get_chunks():
Feb 21 03:27:25 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/common/objects.py", line 275, in get_chunks
Feb 21 03:27:25 cuckoo python3.8[17365]:     with open(self.file_path, "rb") as fd:
Feb 21 03:27:25 cuckoo python3.8[17365]: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cuckoo-tmp/upload_fdjr89sx/malware.js'
```
| Question         | Answer
|------------------|--------------------
| Git commit       | c8b46c6a2fe1c653b64544e29c4223a4278c29b2
| OS version       | Ubuntu  Xenial

## Failure Logs

See above

**Comment by doomedraven** [comment]
what about `ls -lah /tmp/cuckoo-tmp/upload_fdjr89sx/malware.js`?

**Comment by ag-michael** [comment]
@doomedraven that directory is empty,  the command returns no such file or directory. but the directory does exist.

**Comment by doomedraven** [comment]
well then issue is normal, if file doesn't exist, it wont work, can you share hash? ensure that you don't have IDS/IPS in mid and using cape without https might generate this

**Comment by ag-michael** [comment]
@doomedraven, Here is output and a sample I can share:

```
Feb 22 15:55:08 cuckoo python3.8[17365]: 2022-02-22 15:55:08,441 [modules.machinery.virtualbox] DEBUG: Stopping vm win10
Feb 22 15:55:08 cuckoo python3.8[17365]: 2022-02-22 15:55:08,442 [modules.machinery.virtualbox] DEBUG: Getting status for win10
Feb 22 15:55:09 cuckoo python3.8[17365]: 2022-02-22 15:55:09,070 [modules.machinery.virtualbox] DEBUG: Machine win10 status running
Feb 22 15:55:11 cuckoo python3.8[17365]: 2022-02-22 15:55:11,209 [modules.machinery.virtualbox] DEBUG: Getting status for win10
Feb 22 15:55:11 cuckoo python3.8[17365]: 2022-02-22 15:55:11,403 [modules.machinery.virtualbox] DEBUG: Machine win10 status poweroff
Feb 22 15:55:11 cuckoo python3.8[17365]: 2022-02-22 15:55:11,436 [lib.cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.56.110 for task #130
Feb 22 15:55:11 cuckoo python3.8[17365]: 2022-02-22 15:55:11,437 [lib.cuckoo.core.scheduler] INFO: Disabled route 'internet'
Feb 22 15:55:11 cuckoo python3.8[17365]: 2022-02-22 15:55:11,458 [lib.cuckoo.core.scheduler] ERROR: Task #130: Failure in AnalysisManager.run: [Errno 2] No such file or directory: '/tmp/cuckoo-tmp/upload_15akbnr9/am.js'
Feb 22 15:55:11 cuckoo python3.8[17365]: Traceback (most recent call last):
Feb 22 15:55:11 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/core/scheduler.py", line 434, in run
Feb 22 15:55:11 cuckoo python3.8[17365]:     success = self.launch_analysis()
Feb 22 15:55:11 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/core/scheduler.py", line 343, in launch_analysis
Feb 22 15:55:11 cuckoo python3.8[17365]:     guest.start_analysis(options)
Feb 22 15:55:11 cuckoo python3.8[17365]:   File "/datadrive/CAPEv2/lib/cuckoo/core/guest.py", line 307, in start_analysis
Feb 22 15:55:11 cuckoo python3.8[17365]:     "file": ("sample.bin", open(options["target"], "rb")),
Feb 22 15:55:11 cuckoo python3.8[17365]: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cu
ckoo-tmp/upload_15akbnr9/am.js'
```
[am.js.zip](https://github.com/kevoreilly/CAPEv2/files/8118127/am.js.zip)

The connection is through an SSH tunnel to the CAPE server (no middle box). I'm using the builtin manage.py server as well.

**Comment by doomedraven** [comment]
all works fine here so far, so first of all i would suggest you to update to latest cape and then check again  here is proof https://capesandbox.com/analysis/243298/ you need to search what is wrong with your setup
