### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.cuckoo' when trying to run the web server

### ISSUE THREAD

**Issue by enceladus3** [kevoreilly/CAPEv2#795]
/opt/CAPEv2/web$ sudo python3 manage.py runserver 0.0.0.0:8080
[sudo] password for ks: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/CAPEv2/web/web/settings.py", line 20, in <module>
    from lib.cuckoo.common.config import Config
ModuleNotFoundError: No module named 'lib.cuckoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/CAPEv2/web/web/settings.py", line 20, in <module>
    from lib.cuckoo.common.config import Config
ModuleNotFoundError: No module named 'lib.cuckoo'

- >  running cuckoo.py works as expected however I encounter this issue ^
- Initially I got ModuleNotFoundError: No module named 'lib' **(just lib)** then I installed lib with pip3/pip and now I got this on Ubuntu 20.04

**Comment by enceladus3** [comment]
fixed

**Comment by ClaudioWayne** [comment]
Hi,

for me, this error occurs when I do not run manage.py within the directory /opt/CAPEv2/web so what you can try:
- `cd /opt/CAPEv2/web/ && python3 manage.py runserver`
- i guess it is not good idea to start manage.py with sudo, try without sudo
- normally cape-webservice should already be running, check systemctl status for cape-webservice

**Comment by ClaudioWayne** [comment]
what was the problem?

**Comment by enceladus3** [comment]
I had to run first `manage.py runserver` adn then the usual command `manage.py runserver 0.0.0.0:8080`
