### ISSUE TITLE
Analysis processing fails since upgrade

### ISSUE THREAD

**Issue by xme** [kevoreilly/CAPEv2#858]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

Upgrade CAPEv2 to the latest release and now processing of analysis results fails...

# Current Behavior

Python error returned in process.log and console reports "failed_processing" for all samples

# Failure Information (for bugs)

2022-05-24 07:27:22,652 [lib.cuckoo.core.plugins] ERROR: Failed to load signature "<class 'modules.signatures.antisandbox_unhook.Unhook'>": 'target'
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 412, in process
    current = signature(self.results)
  File "/opt/CAPEv2/utils/../modules/signatures/antisandbox_unhook.py", line 37, in __init__
    if self.results["target"]["category"] != "file":
KeyError: 'target'
2022-05-24 07:27:22,816 [root] ERROR: Exception when processing task 1592: 'target'
2022-05-24 07:27:48,794 [root] INFO: Processing analysis data

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | bba6bbe705c00f9d02e86177e72a45948a0a756c
| OS version       | Ubuntu 18.04

**Comment by kevoreilly** [comment]
Would you try restarting all cape services? I have heard this may solve this issue.

**Comment by doomedraven** [comment]
btw @xme if you still on python 3.6 as you using ubuntu 18. you might start getting more problems, as our py requirement now is 3.8

**Comment by xme** [comment]
Tx for the warning, will upgrade! I restarted all processes, same issue.
I did not update the agent on guests, is there a recent change in agent.py that could be the root cause?

**Comment by xme** [comment]
Ok, I upgraded everything... Ubuntu, now running a 3.8 Python, etc. The initial problem has been magically fixed ;-)
I'm still having some small issues to fix one by one but this one looks more interesting:

```
2022-05-25 07:36:06,909 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Retention": mongo_delete_data() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 682, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/retention.py", line 145, in run
    mongo_delete_data(curtask, lastTask)
TypeError: mongo_delete_data() takes 1 positional argument but 2 were given
```

**Comment by doomedraven** [comment]
fixed now, thank you for reporting, closing as original issue solved, but if you see something else let me know ASAP
