### ISSUE TITLE
exe package fails for some items

### ISSUE THREAD

**Issue by VVelox** [kevoreilly/CAPEv2#947]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I'm have read all configs with all optional parts

# Expected Behavior

Does not fail to run some executable files.

# Current Behavior

Some executables will do nothing, just fail to run.

# Failure Information (for bugs)

SetupRST.exe from Intel below is a example of this. Ended up ran in our env and came to our attention that it won't run at all. Expected behaviour for this one in question is it runs and then throws a error window about not being the HW being unsupported.

https://www.intel.com/content/www/us/en/download/15667/intel-rapid-storage-technology-intel-rst-user-interface-and-driver.html

## Steps to Reproduce

1. Grab SetupRST.exe from https://www.intel.com/content/www/us/en/download/15667/intel-rapid-storage-technology-intel-rst-user-interface-and-driver.html
2. Run it, with the package either set to auto or exe(which will be choosen automatically).
3. Wait for it to complete.
4. Check the logs.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       | 9884daec105144fa02eb736d8385f6450e36a686
| OS version       | Ubuntu 20.04
| Guest OS | Win10

## Failure Logs

```
2022-06-16 00:57:23,456 [root] INFO: Date set to: 20220621T18:03:10, timeout set to: 200
2022-06-16 00:57:23,471 [root] DEBUG: Starting analyzer from: C:\tmpfyh9ql4u
2022-06-16 00:57:23,471 [root] DEBUG: Storing results at: C:\NzkDuv
2022-06-16 00:57:23,471 [root] DEBUG: Pipe server name: \\.\PIPE\wPGToh
2022-06-16 00:57:23,471 [root] DEBUG: Python path: C:\Program Files (x86)\Python310-32
2022-06-16 00:57:23,471 [root] INFO: Analysis package "exe" has been specified
2022-06-16 00:57:23,471 [root] DEBUG: Importing analysis package "exe"...
2022-06-16 00:57:23,471 [root] DEBUG: Initializing analysis package "exe"...
2022-06-16 00:57:23,471 [root] INFO: Analyzer: Package modules.packages.exe does not specify a DLL option
2022-06-16 00:57:23,471 [root] INFO: Analyzer: Package modules.packages.exe does not specify a DLL_64 option
2022-06-16 00:57:23,471 [root] INFO: Analyzer: Package modules.packages.exe does not specify a loader option
2022-06-16 00:57:23,471 [root] INFO: Analyzer: Package modules.packages.exe does not specify a loader_64 option
2022-06-16 00:57:23,503 [root] DEBUG: Importing auxiliary module "modules.auxiliary.browser"...
2022-06-16 00:57:23,503 [root] DEBUG: Importing auxiliary module "modules.auxiliary.curtain"...
2022-06-16 00:57:23,503 [root] DEBUG: Importing auxiliary module "modules.auxiliary.digisig"...
2022-06-16 00:57:23,518 [root] DEBUG: Importing auxiliary module "modules.auxiliary.disguise"...
2022-06-16 00:57:23,534 [root] DEBUG: Importing auxiliary module "modules.auxiliary.evtx"...
2022-06-16 00:57:23,534 [root] DEBUG: Importing auxiliary module "modules.auxiliary.human"...
2022-06-16 00:57:23,549 [root] DEBUG: Importing auxiliary module "modules.auxiliary.procmon"...
2022-06-16 00:57:23,549 [root] DEBUG: Importing auxiliary module "modules.auxiliary.screenshots"...
2022-06-16 00:57:23,549 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2022-06-16 00:57:23,596 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageGrab'
2022-06-16 00:57:23,612 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2022-06-16 00:57:23,628 [root] DEBUG: Importing auxiliary module "modules.auxiliary.sysmon"...
2022-06-16 00:57:23,628 [root] DEBUG: Importing auxiliary module "modules.auxiliary.tlsdump"...
2022-06-16 00:57:23,643 [root] DEBUG: Importing auxiliary module "modules.auxiliary.usage"...
2022-06-16 00:57:23,643 [root] DEBUG: Initializing auxiliary module "Browser"...
2022-06-16 00:57:23,643 [root] DEBUG: Started auxiliary module Browser
2022-06-16 00:57:23,643 [root] DEBUG: Initializing auxiliary module "Curtain"...
2022-06-16 00:57:23,643 [root] DEBUG: Started auxiliary module Curtain
2022-06-16 00:57:23,643 [root] DEBUG: Initializing auxiliary module "DigiSig"...
2022-06-16 00:57:23,643 [modules.auxiliary.digisig] DEBUG: Checking for a digital signature
2022-06-16 00:57:24,378 [modules.auxiliary.digisig] DEBUG: File has an invalid signature
2022-06-16 00:57:24,378 [modules.auxiliary.digisig] INFO: Uploading signature results to aux/DigiSig.json
2022-06-16 00:57:24,393 [root] DEBUG: Started auxiliary module DigiSig
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "Disguise"...
2022-06-16 00:57:24,393 [root] WARNING: Cannot execute auxiliary module Disguise: [WinError 5] Access is denied
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "Evtx"...
2022-06-16 00:57:24,393 [root] DEBUG: Started auxiliary module Evtx
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "Human"...
2022-06-16 00:57:24,393 [root] DEBUG: Started auxiliary module Human
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "Procmon"...
2022-06-16 00:57:24,393 [root] DEBUG: Started auxiliary module Procmon
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "Screenshots"...
2022-06-16 00:57:24,393 [root] DEBUG: Started auxiliary module Screenshots
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "Sysmon"...
2022-06-16 00:57:24,393 [root] DEBUG: Started auxiliary module Sysmon
2022-06-16 00:57:24,393 [root] DEBUG: Initializing auxiliary module "TLSDumpMasterSecrets"...
2022-06-16 00:57:24,409 [modules.auxiliary.tlsdump] INFO: lsass.exe found, pid 608
2022-06-16 00:57:24,409 [lib.api.process] INFO: Monitor config for process 608: C:\tmpfyh9ql4u\dll\608.ini
2022-06-16 00:57:27,659 [lib.api.process] INFO: Option 'tlsdump' with value '1' sent to monitor
2022-06-16 00:57:27,659 [lib.api.process] INFO: 32-bit DLL to inject is C:\tmpfyh9ql4u\dll\SCBDPe.dll, loader C:\tmpfyh9ql4u\bin\XTrvnyx.exe
2022-06-16 00:57:27,690 [root] DEBUG: Loader: Injecting process 608 with C:\tmpfyh9ql4u\dll\SCBDPe.dll.
2022-06-16 00:57:27,690 [root] DEBUG: Error 5 (0x5) - InjectDll: Failed to open process: Access is denied.
2022-06-16 00:57:27,706 [root] DEBUG: Successfully injected DLL C:\tmpfyh9ql4u\dll\SCBDPe.dll.
2022-06-16 00:57:27,706 [root] DEBUG: Started auxiliary module TLSDumpMasterSecrets
2022-06-16 00:57:27,706 [root] DEBUG: Initializing auxiliary module "Usage"...
2022-06-16 00:57:27,706 [root] DEBUG: Started auxiliary module Usage
2022-06-16 00:57:28,284 [root] INFO: Restarting WMI Service
2022-06-16 00:57:29,143 [lib.api.process] ERROR: Failed to execute process from path "C:\Users\Fifi\AppData\Local\Temp\SetupRST.exe" with arguments "None" (Error: 740)
2022-06-16 00:57:29,143 [root] INFO: You probably submitted the job with wrong package
Traceback (most recent call last):
  File "C:\tmpfyh9ql4u\analyzer.py", line 510, in run
    pids = self.package.start(self.target)
  File "C:\tmpfyh9ql4u\modules\packages\exe.py", line 37, in start
    return self.execute(path, args, path)
  File "C:\tmpfyh9ql4u\lib\common\abstracts.py", line 119, in execute
    raise CuckooPackageError("Unable to execute the initial process, analysis aborted")
lib.common.exceptions.CuckooPackageError: Unable to execute the initial process, analysis aborted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tmpfyh9ql4u\analyzer.py", line 1378, in <module>
    success = analyzer.run()
  File "C:\tmpfyh9ql4u\analyzer.py", line 514, in run
    raise CuckooError(f'The package "{package_name}" start function raised an error: {e}') from e
lib.common.exceptions.CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted
2022-06-16 00:57:29,159 [root] WARNING: Folder at path "C:\NzkDuv\debugger" does not exist, skipping
2022-06-16 00:57:29,159 [root] WARNING: Folder at path "C:\NzkDuv\tlsdump" does not exist, skipping
2022-06-16 00:57:29,159 [root] INFO: Analysis completed
```

**Comment by VVelox** [comment]
Derp. Just realized I had not updated and am 25 days out of date for the core stuff before submitting this. Let me update and try again.

**Comment by doomedraven** [comment]
hello does it works after update?

**Comment by VVelox** [comment]
> hello does it works after update?

Hey, been busy since I've submitted this. I'll be able to tell you in a few hours hopefully. :) Sorry about that.

**Comment by VVelox** [comment]
> hello does it works after update?

So apparently post update it is completely broken. Everything is complaining about peotry not being able to find various modules.

```
kitsune@nagi:/opt/CAPEv2/web$ sudo -u cape /usr/bin/python3 -m poetry run python manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
kitsune@nagi:/opt/CAPEv2$ sudo pip3 install django
Requirement already satisfied: django in /usr/local/lib/python3.8/dist-packages (4.0.4)
Requirement already satisfied: asgiref<4,>=3.4.1 in /usr/local/lib/python3.8/dist-packages (from django) (3.5.0)
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.8/dist-packages (from django) (0.4.2)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from django) (0.2.1)
```

Requirements does throw this error though when `sudo pip3 install -r requirements.txt` is ran...

```
kitsune@nagi:/opt/CAPEv2$ sudo pip3 install -r requirements.txt 
Ignoring altgraph: markers 'sys_platform == "darwin" and python_version >= "3.6"' don't match your environment
Collecting batch-deobfuscator@ git+https://github.com/DissectMalware/batch_deobfuscator.git@a0d9d51e28cf519a42b35587fde7f8df09c78be3
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    batch-deobfuscator@ git+https://github.com/DissectMalware/batch_deobfuscator.git@a0d9d51e28cf519a42b35587fde7f8df09c78be3 from git+https://github.com/DissectMalware/batch_deobfuscator.gi
t@a0d9d51e28cf519a42b35587fde7f8df09c78be3 (from -r requirements.txt (line 27))
kitsune@nagi:/opt/CAPEv2$ 
```

**Comment by doomedraven** [comment]
do not install cape deps as root. CAPE won't see them is how python now splits packages between global and local user. you need to use `poetry install`

**Comment by VVelox** [comment]
> do not install cape deps as root. CAPE won't see them is how python now splits packages between global and local user. you need to use `poetry install`

Hmm, looks like that is missing from cape2.sh. Never does a `sudo -u cape poetry install`. Did that and it is going through installing stuff.

**Comment by doomedraven** [comment]
`sudo -u cape poetry install` is run as cape user, but your `sudo pip3 install -r requirements.txt ` is run as root

**Comment by VVelox** [comment]
> `sudo -u cape poetry install` is run as cape user, but your `sudo pip3 install -r requirements.txt ` is run as root

Right. What I mean is it was never reeled in by the update. If you check `https://github.com/doomedraven/Tools/blob/master/Sandbox/cape2.sh` it never calls that.

`sudo -u cape poetry install` does not appear to fix it though.

```
kitsune@nagi:/opt/CAPEv2$ sudo -u cape /usr/bin/python3 -m poetry run python cuckoo.py
Traceback (most recent call last):
  File "cuckoo.py", line 21, in <module>
    from lib.cuckoo.core.resultserver import ResultServer
  File "/opt/CAPEv2/lib/cuckoo/core/resultserver.py", line 16, in <module>
    from lib.cuckoo.common.abstracts import ProtocolHandler
  File "/opt/CAPEv2/lib/cuckoo/common/abstracts.py", line 32, in <module>
    from lib.cuckoo.common.utils import create_folder, get_memdump_path, load_categories
  File "/opt/CAPEv2/lib/cuckoo/common/utils.py", line 84, in <module>
    zippwd = web_cfg.zipped_download.get("zip_pwd", b"infected")
AttributeError: 'Config' object has no attribute 'zipped_download'
kitsune@nagi:/opt/CAPEv2$ 
```

**Comment by doomedraven** [comment]
so go over all 24d of all changes in conf folder and add them to your configs

**Comment by doomedraven** [comment]
ah now i see what do you mean about `sudo -u cape poetry install`. the problem is that it changes so much since ubuntu 16 when that script was born. before global install worked. but with each new version the cut that down. i have added that `sudo -u cape poetry install` thanks

**Comment by VVelox** [comment]
> well if you do git pull and you have any config modified how do you backup it? do you move it and then restore? as obviously it will have missing all new options there if you restore old config.

That was with the configs generated via cape2.sh. That was a complete refresh I started of CAPE. Only change I was making was to the PW and IP stuff at the top. Had not put my config stuff back into place yet.

I think I had some sort of bad drek cached by python or the like. `mv /opt/CAPEv2/ /opt/CAPEv2.odd` fixed the issue.

Okay, this sucked up more time than I was anticipating. Was hoping to get the test to you a bit sooner, but should some time in a few hours.

Sorry about this all and thanks! :)

**Comment by doomedraven** [comment]
np :) i know that never ending hole of problems

**Comment by doomedraven** [comment]
thanks, fixed

**Comment by VVelox** [comment]
And the results with are...

```
2022-06-16 00:56:03,865 [root] INFO: Date set to: 20220622T14:19:06, timeout set to: 200
2022-06-16 00:56:03,943 [root] DEBUG: Starting analyzer from: C:\tmppbk7pxlm
2022-06-16 00:56:03,943 [root] DEBUG: Storing results at: C:\JIpDTg
2022-06-16 00:56:03,943 [root] DEBUG: Pipe server name: \\.\PIPE\HXuOHJND
2022-06-16 00:56:03,943 [root] DEBUG: Python path: C:\Program Files (x86)\Python310-32
2022-06-16 00:56:03,943 [root] INFO: Analysis package "exe" has been specified
2022-06-16 00:56:03,943 [root] DEBUG: Importing analysis package "exe"...
2022-06-16 00:56:03,959 [root] DEBUG: Initializing analysis package "exe"...
2022-06-16 00:56:03,959 [root] INFO: Analyzer: Package modules.packages.exe does not specify a DLL option
2022-06-16 00:56:03,959 [root] INFO: Analyzer: Package modules.packages.exe does not specify a DLL_64 option
2022-06-16 00:56:03,959 [root] INFO: Analyzer: Package modules.packages.exe does not specify a loader option
2022-06-16 00:56:03,959 [root] INFO: Analyzer: Package modules.packages.exe does not specify a loader_64 option
2022-06-16 00:56:04,162 [root] DEBUG: Importing auxiliary module "modules.auxiliary.browser"...
2022-06-16 00:56:04,178 [root] DEBUG: Importing auxiliary module "modules.auxiliary.curtain"...
2022-06-16 00:56:04,193 [root] DEBUG: Importing auxiliary module "modules.auxiliary.digisig"...
2022-06-16 00:56:04,209 [root] DEBUG: Importing auxiliary module "modules.auxiliary.disguise"...
2022-06-16 00:56:04,240 [root] DEBUG: Importing auxiliary module "modules.auxiliary.evtx"...
2022-06-16 00:56:04,256 [root] DEBUG: Importing auxiliary module "modules.auxiliary.filepickup"...
2022-06-16 00:56:04,256 [root] DEBUG: Importing auxiliary module "modules.auxiliary.human"...
2022-06-16 00:56:04,256 [root] DEBUG: Importing auxiliary module "modules.auxiliary.permissions"...
2022-06-16 00:56:04,271 [root] DEBUG: Importing auxiliary module "modules.auxiliary.procmon"...
2022-06-16 00:56:04,271 [root] DEBUG: Importing auxiliary module "modules.auxiliary.screenshots"...
2022-06-16 00:56:04,271 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2022-06-16 00:56:04,569 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageGrab'
2022-06-16 00:56:04,584 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2022-06-16 00:56:07,100 [root] DEBUG: Importing auxiliary module "modules.auxiliary.sysmon"...
2022-06-16 00:56:07,100 [root] DEBUG: Importing auxiliary module "modules.auxiliary.tlsdump"...
2022-06-16 00:56:07,209 [root] DEBUG: Importing auxiliary module "modules.auxiliary.usage"...
2022-06-16 00:56:07,318 [root] DEBUG: Initialized auxiliary module "Browser"
2022-06-16 00:56:07,318 [root] DEBUG: Trying to start auxiliary module "Browser"...
2022-06-16 00:56:07,318 [root] DEBUG: Started auxiliary module "Browser"
2022-06-16 00:56:07,318 [root] DEBUG: Started auxiliary module Browser
2022-06-16 00:56:07,318 [root] DEBUG: Initialized auxiliary module "Curtain"
2022-06-16 00:56:07,318 [root] DEBUG: Auxiliary module "Curtain" is disabled.
2022-06-16 00:56:07,318 [root] DEBUG: Initialized auxiliary module "DigiSig"
2022-06-16 00:56:07,318 [root] DEBUG: Trying to start auxiliary module "DigiSig"...
2022-06-16 00:56:07,318 [modules.auxiliary.digisig] DEBUG: Checking for a digital signature
2022-06-16 00:56:08,787 [modules.auxiliary.digisig] DEBUG: File has an invalid signature
2022-06-16 00:56:08,802 [modules.auxiliary.digisig] INFO: Uploading signature results to aux/DigiSig.json
2022-06-16 00:56:08,818 [root] DEBUG: Started auxiliary module "DigiSig"
2022-06-16 00:56:08,818 [root] DEBUG: Started auxiliary module DigiSig
2022-06-16 00:56:08,818 [root] DEBUG: Initialized auxiliary module "Disguise"
2022-06-16 00:56:08,818 [root] DEBUG: Trying to start auxiliary module "Disguise"...
2022-06-16 00:56:08,818 [root] WARNING: Cannot execute auxiliary module Disguise: [WinError 5] Access is denied
2022-06-16 00:56:08,818 [root] DEBUG: Initialized auxiliary module "Evtx"
2022-06-16 00:56:08,818 [root] DEBUG: Auxiliary module "Evtx" is disabled.
2022-06-16 00:56:08,834 [root] WARNING: Auxiliary module FilePickup was not implemented: 'Config' object has no attribute 'file_pickup'
2022-06-16 00:56:08,834 [root] DEBUG: Initialized auxiliary module "Human"
2022-06-16 00:56:08,834 [root] DEBUG: Trying to start auxiliary module "Human"...
2022-06-16 00:56:08,834 [root] DEBUG: Started auxiliary module "Human"
2022-06-16 00:56:08,834 [root] DEBUG: Started auxiliary module Human
2022-06-16 00:56:08,834 [root] WARNING: Auxiliary module Permissions was not implemented: 'Config' object has no attribute 'file_pickup'
2022-06-16 00:56:08,834 [root] DEBUG: Initialized auxiliary module "Procmon"
2022-06-16 00:56:08,834 [root] DEBUG: Auxiliary module "Procmon" is disabled.
2022-06-16 00:56:08,834 [root] DEBUG: Initialized auxiliary module "Screenshots"
2022-06-16 00:56:08,834 [root] DEBUG: Trying to start auxiliary module "Screenshots"...
2022-06-16 00:56:08,849 [root] DEBUG: Started auxiliary module "Screenshots"
2022-06-16 00:56:08,849 [root] DEBUG: Started auxiliary module Screenshots
2022-06-16 00:56:08,849 [root] DEBUG: Initialized auxiliary module "Sysmon"
2022-06-16 00:56:08,849 [root] DEBUG: Auxiliary module "Sysmon" is disabled.
2022-06-16 00:56:08,849 [root] DEBUG: Initialized auxiliary module "TLSDumpMasterSecrets"
2022-06-16 00:56:08,849 [root] DEBUG: Trying to start auxiliary module "TLSDumpMasterSecrets"...
2022-06-16 00:56:08,849 [modules.auxiliary.tlsdump] INFO: lsass.exe found, pid 600
2022-06-16 00:56:08,849 [lib.api.process] INFO: Monitor config for process 600: C:\tmppbk7pxlm\dll\600.ini
2022-06-16 00:56:08,849 [lib.api.process] INFO: Option 'tlsdump' with value '1' sent to monitor
2022-06-16 00:56:08,849 [lib.api.process] INFO: 32-bit DLL to inject is C:\tmppbk7pxlm\dll\TQntyKzn.dll, loader C:\tmppbk7pxlm\bin\nzNahkW.exe
2022-06-16 00:56:08,959 [root] DEBUG: Loader: Injecting process 600 with C:\tmppbk7pxlm\dll\TQntyKzn.dll.
2022-06-16 00:56:08,974 [root] DEBUG: Error 5 (0x5) - InjectDll: Failed to open process: Access is denied.
2022-06-16 00:56:08,974 [root] DEBUG: Successfully injected DLL C:\tmppbk7pxlm\dll\TQntyKzn.dll.
2022-06-16 00:56:09,256 [root] DEBUG: Started auxiliary module "TLSDumpMasterSecrets"
2022-06-16 00:56:09,256 [root] DEBUG: Started auxiliary module TLSDumpMasterSecrets
2022-06-16 00:56:09,256 [root] DEBUG: Initialized auxiliary module "Usage"
2022-06-16 00:56:09,256 [root] DEBUG: Auxiliary module "Usage" is disabled.
2022-06-16 00:56:14,990 [root] INFO: Restarting WMI Service
2022-06-16 00:56:16,193 [lib.api.process] ERROR: Failed to execute process from path "C:\Users\Fifi\AppData\Local\Temp\SetupRST.exe" with arguments "None" (Error: 740)
2022-06-16 00:56:16,193 [root] INFO: You probably submitted the job with wrong package
Traceback (most recent call last):
  File "C:\tmppbk7pxlm\analyzer.py", line 516, in run
    pids = self.package.start(self.target)
  File "C:\tmppbk7pxlm\modules\packages\exe.py", line 36, in start
    return self.execute(path, args, path)
  File "C:\tmppbk7pxlm\lib\common\abstracts.py", line 118, in execute
    raise CuckooPackageError("Unable to execute the initial process, analysis aborted")
lib.common.exceptions.CuckooPackageError: Unable to execute the initial process, analysis aborted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tmppbk7pxlm\analyzer.py", line 1384, in <module>
    success = analyzer.run()
  File "C:\tmppbk7pxlm\analyzer.py", line 520, in run
    raise CuckooError(f'The package "{package_name}" start function raised an error: {e}') from e
lib.common.exceptions.CuckooError: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted
2022-06-16 00:56:16,209 [root] WARNING: Folder at path "C:\JIpDTg\debugger" does not exist, skipping
2022-06-16 00:56:16,209 [root] WARNING: Folder at path "C:\JIpDTg\tlsdump" does not exist, skipping
2022-06-16 00:56:16,209 [root] INFO: Analysis completed
```

**Comment by doomedraven** [comment]
is that happens to only this binary or all? due to `Failed to open process: Access is denied.`

**Comment by doomedraven** [comment]
can you submit that sample capesandbox.com?

**Comment by VVelox** [comment]
> can you submit that sample capesandbox.com?

Registered. `vvelox` just needs a account approved and I can. :)

**Comment by doomedraven** [comment]
Done

**Comment by doomedraven** [comment]
Lol me too but only for that file, the rest works. So I guess it will keep magic till someone test that on their side

**Comment by VVelox** [comment]
So problem found.

`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` does not start it with the proper perms and causes various issues on Win10.

The proper way to do it is drop the agent some place and set up a scheduled task to run it upon user login and have it run tell it to run with the highest privileges.

**Comment by VVelox** [comment]
I'll get docs updated and will submit a pull request when I have time later. :)

**Comment by doomedraven** [comment]
Oh I remember to suffer that, but I don’t remember how I executed that finally, but it was pretty similar. Thanks PR will be appreciated

**Comment by doomedraven** [comment]
Cant, try it and you will see why, im on phone

**Comment by VVelox** [comment]
Sure you can, it just requires calling a script with all the required steps in it as it can't accept complex commands. :)

Submitted a PR for that and documenting the agent stuff.
